/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:26 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AccountingArchive]

	@ID		INT,
	@ModifiedByID	INT

AS

	UPDATE Accounting
	SET	Deleted = 1,
		ModifiedDate = GETDATE(),
		ModifiedBy = @ModifiedByID
	WHERE ID = @ID
GO
GRANT VIEW DEFINITION ON [AccountingArchive] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [AccountingArchive] TO [db_dml]
GO
