/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:26 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AgencyGetBillingInvoiceHeader] 
	@AgencyID int
AS
BEGIN
	SET NOCOUNT ON;

SELECT
	ag.Agency, 
	ag.Streetline1, 
	ag.Streetline2, 
	ag.City, 
	(SELECT Abbreviation FROM State st WHERE st.StateID = ag.StateID) AS 'StateID', 
	ag.PostalCode, 
	ag.Phone,
	acc.TaxRate AS 'tax', 
	acc.CustomerAccountID
FROM 
	Agency ag
	INNER JOIN Accounting acc ON acc.ID = ag.AgencyID AND acc.Deleted = 0
	LEFT JOIN TimeZone tz ON tz.TimeZoneID = ag.TimeZoneID AND tz.Deleted = 0
WHERE 
	ag.AgencyID = @AgencyID

END
GO
GRANT EXECUTE ON [AgencyGetBillingInvoiceHeader] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [AgencyGetBillingInvoiceHeader] TO [db_object_def_viewers]
GO
