/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:26 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AgencyUpdate]
	@AgencyID		INT,
	@Agency			NVARCHAR(50),
	@StreetLine1	NVARCHAR(50),
	@StreetLine2	NVARCHAR(50),
	@City			NVARCHAR(50),
	@StateID		INT,
	@PostalCode		NVARCHAR(25),
	@CountryID		INT,
	@Phone			NVARCHAR(25),
	@Fax			NVARCHAR(25),
	@URL			NVARCHAR(50),
	@EmailAddress	NVARCHAR(50),
	@ModifiedByID	INT, 
	@OnCallPhone	NVARCHAR(50),
	@OnCallPager	NVARCHAR(50),
	@OnCallEmail	NVARCHAR(50),
	@TimeZoneID		INT,
	@DaylightSavings BIT,
	@DistributorID	INT,
	@SMSAddress     NVARCHAR(50) = null,
	@SMSGatewayID   INT
AS
	UPDATE Agency
	SET	Agency = @Agency, 
		StreetLine1 = @StreetLine1,
		StreetLine2 = @StreetLine2,
		City = @City,
		StateID = @StateID,
		PostalCode = @PostalCode,
		CountryID = @CountryID,
		Phone = @Phone,
		Fax = @Fax,
		URL = @URL,
		EmailAddress = @EmailAddress,
		ModifiedDate = GETDATE(),
		ModifiedByID = @ModifiedByID,
		OnCallPhone = @OnCallPhone,
		OnCallPager = @OnCallPager,
		OnCallEmail = @OnCallEmail,
		TimeZoneID = @TimeZoneID,
		DaylightSavings = @DaylightSavings,
		DistributorID = @DistributorID,
		SMSAddress = @SMSAddress,
		SMSGatewayID = @SMSGatewayID
	WHERE AgencyID = @AgencyID
GO
GRANT EXECUTE ON [AgencyUpdate] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [AgencyUpdate] TO [db_object_def_viewers]
GO
