/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:26 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AgencyGetByID]
	@AgencyID	INT,
	@GetDeleted BIT = 0
AS
	SELECT	a.AgencyID, 
			ISNULL(Agency, '') AS 'Agency',
			ISNULL(StreetLine1, '') AS 'StreetLine1', 
			ISNULL(StreetLine2, '') AS 'StreetLine2',
			ISNULL(City, '') AS 'City',
			ISNULL(StateID, 0) AS 'StateID', 
			ISNULL(PostalCode, '') AS 'PostalCode',
			ISNULL(CountryID, 0) AS 'CountryID',
			ISNULL(Phone, '') AS 'Phone',
			ISNULL(Fax, '') AS 'Fax',
			ISNULL(URL, '') AS 'URL',
			ISNULL(EmailAddress, '') AS 'EmailAddress',
			ISNULL(OnCallPhone, '') AS 'OnCallPhone',
			ISNULL(OnCallPager, '') AS 'OnCallPager',
			ISNULL(OnCallEmail, '') AS 'OnCallEmail',
			ISNULL(TimeZoneID, 0) AS 'TimeZoneID',
			ISNULL(DaylightSavings, 1) AS 'DaylightSavings', --Default to true
			ISNULL(DistributorID, 0) AS 'DistributorID',
			ISNULL(SMSAddress, '') AS 'SMSAddress', --Default to true
			ISNULL(SMSGatewayID, 0) AS 'SMSGateway',
			CreatedDate,
			CreatedByID,
			ModifiedDate,
			ModifiedByID,
			Deleted,	
			CASE ISNULL(apaa.AlarmProtocolActionListID, 0) 
				WHEN 8 THEN 1
				WHEN 0 THEN 0 
				END AS 'Autocall',
			ISNULL(SFDCAccount,'') AS 'SFDCAccount',
            ISNULL(MapsType, 0) AS 'MapsType',
			GraceEarly,
			GraceLate,
			GraceEnable,
			HealCount
	FROM	Agency a LEFT JOIN AgencyProtocolActionsAllowed apaa ON a.AgencyID = apaa.AgencyID
	WHERE	a.AgencyID = @AgencyID AND (@GetDeleted = 1 OR a.Deleted = 0)

GO
GRANT VIEW DEFINITION ON [AgencyGetByID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [AgencyGetByID] TO [db_dml]
GO
