/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:26 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AgencyGetOverviewBySearch]
	@DistributorID INT = -1,
	@UserID INT
	

AS

	
		SELECT	d.DistributorID, a.AgencyID, d.DistributorName, a.Agency
		from distributor d
		left join	Agency a on d.DistributorID= a.DistributorID and a.Deleted = 0  --and d.TamID=@UserID
		WHERE	
		
		 d.TamID=@UserID
		AND
		(
		(@DistributorID<=0)
		OR 
		(a.DistributorID=@DistributorID)
		)	 
				
	ORDER BY d.DistributorName , a.Agency
GO
GRANT VIEW DEFINITION ON [AgencyGetOverviewBySearch] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [AgencyGetOverviewBySearch] TO [db_dml]
GO
