/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ContactBackupAdd]
	@iContactBackupID int OUTPUT,
	@iUserID int,
	@iPriority int,
	@iContactUserID int,
	@sContactPhone nvarchar(25),
	@sContactEmail nvarchar(50)

AS
	INSERT INTO ContactBackup
	(UserID, Priority, ContactUserID, ContactPhone, ContactEmail)
	VALUES
	(@iUserID, @iPriority, @iContactUserID, @sContactPhone, @sContactEmail)

	SET @iContactBackupID = @@IDENTITY
GO
GRANT VIEW DEFINITION ON [ContactBackupAdd] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [ContactBackupAdd] TO [db_dml]
GO
