/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [DaylightProgressUpdateFile]
	@TrackerID int,
	@FileID int
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE	DaylightUpdateProgress
	SET		FileID = @FileID,
			FileIDTime = GetDate()
	WHERE	TrackerID = @TrackerID
END

GO
GRANT EXECUTE ON [DaylightProgressUpdateFile] TO [db_dml]
GO
