/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mAlarmTypeProtocolActionTimeStartAll]

	

AS
	select g.AlarmProtocolActionFromID, g.AlarmProtocolActionFrom, g.RoleID
	from AlarmProtocolActionFrom  g 
GO
GRANT EXECUTE ON [mAlarmTypeProtocolActionTimeStartAll] TO [db_dml]
GO
