/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmProtocolActionToGetByActionID]

	@ActionID	INT

AS

	SELECT	AlarmProtocolActionToID, AlarmProtocolActionTo
	FROM	AlarmProtocolActionTo
	WHERE	AlarmProtocolActionToID > @ActionID

GO
GRANT VIEW DEFINITION ON [AlarmProtocolActionToGetByActionID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [AlarmProtocolActionToGetByActionID] TO [db_dml]
GO
