/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderServicesAddNew] @OffenderID INT, @ServiceID INT  
AS  
--Adds a new Offender/service relationship.  
BEGIN TRAN  
INSERT INTO OffenderServices(OffenderID,ServiceID,ServiceAttributes)  
VALUES(@OffenderID,@ServiceID,'<ServiceAttributes><Attribute Name="Root"><DataType/><AttributeValue/></Attribute></ServiceAttributes>');  
COMMIT TRAN  
  
  
    
GO
GRANT EXECUTE ON [OffenderServicesAddNew] TO [db_dml]
GO
