/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mAlarmSuspendedArchive]
	@AlarmSuspendedID bigint,
	@Deleted	bit
	
AS

UPDATE AlarmSuspended
SET Deleted = @Deleted
	
WHERE AlarmSuspendedID  = @AlarmSuspendedID



GO
GRANT EXECUTE ON [mAlarmSuspendedArchive] TO [db_dml]
GO
