/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportDeviceList]

	@EndDate			DATETIME
	
AS
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT DISTINCT TOP 5000
		t.deleted,
		t.ModifiedDate,
		t.TrackerID, 
		d.Name AS DeviceName,
		t.TrackerNumber, 
--		ISNULL(P.propertyValue,'') AS PhoneNumber,
--		ISNULL(P2.propertyValue,'') AS PhoneNumber1,
--		ISNULL(d.PhoneNumber,'') AS PhoneNumber2,
		a.Agency,
		ISNULL(officer.FirstName, '')+ ' '+
		ISNULL(officer.MiddleName, '')+' '+
		ISNULL(officer.LastName, '') AS 'officerName',
		ISNULL(o.FirstName, '')+ ' '+
		ISNULL(o.MiddleName, '')+' '+
		ISNULL(o.LastName, '') AS 'OffenderName'
		FROM	Tracker t
		LEFT JOIN Agency a ON t.AgencyID = a.AgencyID
        LEFT JOIN Gateway.dbo.Devices d ON t.TrackerID = d.DeviceID
		LEFT JOIN TrackerAssignment ta ON ta.TrackerID = t.TrackerID
			AND ta.TrackerAssignmentID = (SELECT MAX(TrackerAssignmentID) FROM TrackerAssignment TA WHERE TA.TrackerID = t.TrackerID AND AssignmentDate<=@EndDate  )
	    LEFT JOIN Offender o ON (ta.OffenderID = o.OffenderID AND o.Deleted = 0 AND ta.TrackerAssignmentTypeID=1)
		LEFT JOIN Offender_Officer oo ON o.OffenderID = oo.OffenderID
		LEFT JOIN officer  ON officer.OfficerID = oo.OfficerID 
--		LEFT JOIN Gateway.dbo.deviceProperties P ON P.deviceid =t.TrackerID  AND P.propertyID='8203'
--		LEFT JOIN Gateway.dbo.deviceProperties P2 ON P2.deviceid =t.TrackerID  AND P2.propertyID='8206'
				
		WHERE	
				(t.Deleted = 0)
				OR
				(T.DELETED = 1 AND T.ModifiedDate > @EndDate )		
				AND t.TrackerUniqueID = (SELECT MAX(TrackerUniqueID) FROM Tracker WHERE TrackerID= t.TrackerID) 

		AND
			(	 
				d.Address!=''
			)
		ORDER BY 	t.TrackerNumber
GO
GRANT VIEW DEFINITION ON [ReportDeviceList] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [ReportDeviceList] TO [db_dml]
GO
