/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderClearDefault]
@iOffenderID INT

AS
BEGIN
UPDATE OffenderImage 
SET DefaultImage = 0
WHERE OffenderID = @iOffenderID
           
END
GO
GRANT EXECUTE ON [OffenderClearDefault] TO [db_dml]
GO
