/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OfficerAdd]

	@OfficerID		INT OUTPUT,
	@UserID			INT,
	@AgencyID		INT,
	@Title			NVARCHAR(50),
	@Department		NVARCHAR(50),
	@SalutationID	INT,
	@FirstName		NVARCHAR(50),
	@MiddleName		NVARCHAR(50),
	@LastName		NVARCHAR(50),
	@SuffixID		INT,
	@StreetLine1	NVARCHAR(50),
	@StreetLine2	NVARCHAR(50),
	@City			NVARCHAR(50),
	@StateID		INT,
	@PostalCode		NVARCHAR(25),
	@CountryID		INT,
	@DayPhone		NVARCHAR(25),
	@EveningPhone	NVARCHAR(25),
	@ExtDayPhone    NVARCHAR(20),
	@ExtEveningPhone NVARCHAR(20),
	@MobilePhone	NVARCHAR(25),
	@Pager			NVARCHAR(25),
	@Fax			NVARCHAR(25),
	@EmailAddress1	NVARCHAR(50),
	@EmailAddress2	NVARCHAR(50),
	@CreatedByID	INT,
	@CreatedDate    DATETIME = null OUTPUT,
	@SMSAddress     NVARCHAR(50),
	@SMSGatewayID   INT

AS 
    SET @CreatedDate = GETDATE()

	INSERT INTO Officer
	(UserID, AgencyID, Title, Department, SalutationID, FirstName, MiddleName,
	 LastName, SuffixID, StreetLine1, StreetLine2, City, StateID, PostalCode, 
	 CountryID, DayPhone, EveningPhone, MobilePhone, Pager, Fax, EmailAddress1, 
	 EmailAddress2, CreatedByID, CreatedDate, SMSAddress, SMSGatewayID,ExtDayPhone,ExtEveningPhone)
	VALUES
	(@UserID, @AgencyID, @Title, @Department, @SalutationID, @FirstName, @MiddleName,
	 @LastName, @SuffixID, @StreetLine1, @StreetLine2, @City, @StateID, @PostalCode, 
	 @CountryID, @DayPhone, @EveningPhone, @MobilePhone, @Pager, @Fax, @EmailAddress1, 
	 @EmailAddress2, @CreatedByID, @CreatedDate, @SMSAddress, @SMSGatewayID,@ExtDayPhone,@ExtEveningPhone)

	SET @OfficerID = @@IDENTITY
GO
GRANT VIEW DEFINITION ON [OfficerAdd] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OfficerAdd] TO [db_dml]
GO
