/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:26 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmDetailByDevice]

@StartDate DateTime,
@EndDate DateTime
AS

SELECT
--CONVERT(CHAR(10),DATEADD(mi,-360,a.Eventdisplaytime),110)  AS Date
dp.Propertyvalue AS 'Deviceserial'
,o.FirstNAme+' '+o.LastName AS 'OffenderName'
,ofi.FirstNAme+' '+ofi.LastName AS 'OfficerName'
,ag.Agency
--,MAX(CONVERT(varchar(25),DATEADD (mi,-360,ota.activatedate),110))AS 'Activation Date'
--,(CASE WHEN MAX(ota.deactivatedate) is NULL THEN '' 
--ELSE MAX(CONVERT(varchar(25),DATEADD (mi,-360,ota.deactivatedate),110))END)AS 'Deactivation Date' 

,SUM(CASE When a.eventtypeID = 25 THEN 1
ELSE 0 END) AS 'Bat Crit'

,SUM(CASE When a.eventtypeID = 65 THEN 1
ELSE 0 END) AS 'StrapOptical'

,SUM(CASE When a.eventtypeID = 44 THEN 1
ELSE 0 END) AS 'Incl Violate'

,SUM(CASE When a.eventtypeID = 45 THEN 1
ELSE 0 END) AS 'Incl Cmplnce'

,SUM(CASE When a.eventtypeID = 36 THEN 1
ELSE 0 END) AS 'Excl Violate'

,SUM(CASE When a.eventtypeID = 37 THEN 1
ELSE 0 END) AS 'Excl Cmplnce'

,SUM(CASE When a.eventtypeID = 21 THEN 1
ELSE 0 END) AS 'Ext BatTmout'

,SUM(CASE When a.eventtypeID = 26 THEN 1
ELSE 0 END) AS 'Shutdown Pend'

,SUM(CASE When a.eventtypeID = 256 THEN 1
ELSE 0 END) AS 'NoEventTimeout'

,SUM(CASE When a.eventtypeID = 258 THEN 1
ELSE 0 END) AS 'NoEventTimeoutEsc'

,SUM(CASE When a.eventtypeID = 257 THEN 1
ELSE 0 END) AS 'CommResumed'

,SUM(CASE When a.eventtypeID = 194 THEN 
1  ELSE 0 END) AS 'eArrestViol'

,SUM(CASE When a.eventtypeID = 195 THEN 
1  ELSE 0 END) AS 'eArrestComply'

,SUM(CASE When a.eventtypeID = 177 THEN 
1  ELSE 0 END) AS 'eBeaconMoved'

,SUM(CASE When a.eventtypeID = 182 THEN 
1  ELSE 0 END) AS 'eBeaconBatCrit'

,SUM(CASE When a.eventtypeID = 210 THEN 
1  ELSE 0 END) AS 'Batt Crit-TP2'

,SUM(CASE When a.eventtypeID = 211 THEN 
1  ELSE 0 END) AS 'Batt Crit Esc-TP2'

,SUM(CASE When a.eventtypeID = 212 THEN 
1  ELSE 0 END) AS 'Shutdown Now-TP2'


,SUM(1) AS 'Total Alarms' 

From Alarm a WITH (NOLOCK)
JOIN Offender o ON o.Offenderid = a.Offenderid
JOIN Offender_Officer oo ON oo.Offenderid = a.Offenderid
JOIN Officer ofi ON ofi.Officerid = oo.Officerid
JOIN Agency ag ON ag.agencyid = o.agencyid
JOIN Gateway.dbo.deviceproperties dp ON dp.deviceid= a.trackerid and dp.propertyid = '8012'
--JOIN Offendertrackeractivation ota ON ota.Offenderid = a.Offenderid ANd ota.trackerid = a.trackerid 

Where DATEADD(mi,-360,EventDisplayTime) BETWEEN @StartDate AND @EndDate 


GROUP BY 
--CONVERT(CHAR(10),DATEADD(mi,-360,a.Eventdisplaytime),110)
dp.Propertyvalue
,o.FirstName+' '+o.LastName
,ofi.FirstName+' '+ofi.LastName
,ag.Agency

Order BY 'Total Alarms' DESC



GO
GRANT EXECUTE ON [AlarmDetailByDevice] TO [db_dml]
GO
