/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportStandardActiveMonitoringAgencySummary]




@Agencyid int
--
--Set @Officerid = 4616
--Set @Agencyid = 830
AS
Select rpt.* INTO 
#tmplast24events
From rprteventsbucket1 rpt
JOIN OptionalBillingServiceOptionOffender obsoo ON obsoo.Offenderid = rpt.Offenderid
JOIN BillingServiceOption bso ON bso.id = obsoo.BillingServiceOptionid
JOIN ClassicBillingservice cbs ON cbs.Billingserviceid = bso.Billingserviceid
WHERE dbo.fnUtcToLocal(@Agencyid,rpt.EventDateTime) BETWEEN DATEADD(hh,-24,CONVERT(DATETIME, FLOOR(CONVERT(FLOAT,dbo.fnUtcToLocal(@Agencyid,GETDATE())))))
AND CONVERT(DATETIME, FLOOR(CONVERT(FLOAT,dbo.fnUtcToLocal(@Agencyid,GETDATE()))))
ANd rpt.alarmtype > 1
AND rpt.Agencyid = @Agencyid
AND cbs.Serviceid = 3

 
Select
ofi.LastNAme+', '+ofi.firstname AS OfficerName
,SUM(Case When tmp.eventid IS NULL THEN 0 Else 1 END) AS AlarmTotal

From Offender o
Left JOIN #tmplast24events tmp ON tmp.Offenderid = o.Offenderid
JOIN OptionalBillingServiceOptionOffender obsoo ON obsoo.Offenderid = o.Offenderid
JOIN BillingServiceOption bso ON bso.id = obsoo.BillingServiceOptionid
JOIN ClassicBillingservice cbs ON cbs.Billingserviceid = bso.Billingserviceid
JOIN Offender_Officer oo ON oo.Offenderid = o.Offenderid
JOIN Officer ofi on ofi.Officerid = oo.officerid
Where o.deleted = 0 AND o.agencyid = @Agencyid AND cbs.serviceid = 3
GROUP BY ofi.LastNAme+', '+ofi.firstname
Order BY ofi.LastNAme+', '+ofi.firstname

drop table #tmplast24events




GO
GRANT EXECUTE ON [ReportStandardActiveMonitoringAgencySummary] TO [db_dml]
GO
