/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoZoneAdd]
    @GeoZoneId             uniqueidentifier OUTPUT,
    @Name                  NCHAR(50),
    @Description           NCHAR(50),
    @Type                  Int,
    @ShapeData             NVARCHAR(MAX)=null
AS
SET NOCOUNT ON;
BEGIN
	BEGIN TRAN
		SET @GeoZoneId= NewId();
		INSERT INTO GeoZone(Id,Name,Description,Type,ShapeData)
			VALUES (@GeoZoneId, @Name, @Description, @Type, @ShapeData)
	COMMIT TRAN
END





GO
GRANT EXECUTE ON [GeoZoneAdd] TO [db_dml]
GO
