/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmProtocolActionContactInfoGetByRoleID]

	@RoleID	INT

AS

	SELECT	AlarmProtocolActionContactInfoID, AlarmProtocolActionContactInfo
	FROM	AlarmProtocolActionContactInfo
	WHERE	RoleID <= @RoleID order by displayorder
GO
GRANT VIEW DEFINITION ON [AlarmProtocolActionContactInfoGetByRoleID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [AlarmProtocolActionContactInfoGetByRoleID] TO [db_dml]
GO
