/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoRule_OffenderDeleteByArea]
@OffenderID INT,
@AreaID INT
AS
DELETE FROM GeoRule_Offender
WHERE ((AreaID=@AreaID) AND (OffenderID=@OffenderID))

GO
GRANT EXECUTE ON [GeoRule_OffenderDeleteByArea] TO [db_dml]
GO
