/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoRule_OffenderUpdateZoneID]
@iGeoRuleID INT,
@iZoneID INT
AS
UPDATE GeoRule_Offender
SET ZoneID=@iZoneID
WHERE GeoRuleID = @iGeoRuleID

GO
GRANT EXECUTE ON [GeoRule_OffenderUpdateZoneID] TO [db_dml]
GO
