/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OfficerGetBySearch]

	@FirstName	NVARCHAR(50),
	@LastName	NVARCHAR(50),
	@AgencyID	INT,
	@RoleID INT = -1,
	@UserID INT = -1
AS

IF @RoleID = 19 --TAM
	BEGIN

		SELECT	o.OfficerID, o.FirstName, o.LastName, r.[Role], a.Agency
				FROM	Officer o
				left JOIN User_Role ur ON o.UserID = ur.UserID
				left JOIN [Role] r ON ur.RoleID = r.RoleID
				LEFT JOIN Agency a ON o.AgencyID = a.AgencyID
				INNER JOIN distributor d on d.DistributorID= a.DistributorID and d.TamID=@UserID
				WHERE
				(
					(LEN(@FirstName) <= 0)
					OR
					(o.FirstName LIKE '%' + @FirstName + '%')
				)	
				AND
				(
					(LEN(LastName) <= 0)
					OR
					(o.LastName Like '%' + @LastName + '%')
				)	

				AND
				(
					(@AgencyID = 0)
					OR
					(a.AgencyID = @AgencyID)
				)	
				 AND
					o.Deleted = 0
				ORDER BY a.Agency, r.[Role], o.LastName, o.FirstName
	END
ELSE
	BEGIN
		SELECT	o.OfficerID, o.FirstName, o.LastName, r.[Role], a.Agency
				FROM	Officer o
				left JOIN User_Role ur ON o.UserID = ur.UserID
				left JOIN [Role] r ON ur.RoleID = r.RoleID
				LEFT JOIN Agency a ON o.AgencyID = a.AgencyID
				WHERE
				(
					(LEN(@FirstName) <= 0)
					OR
					(o.FirstName LIKE '%' + @FirstName + '%')
				)	
				AND
				(
					(LEN(LastName) <= 0)
					OR
					(o.LastName Like '%' + @LastName + '%')
				)	

				AND
				(
					(@AgencyID = 0)
					OR
					(a.AgencyID = @AgencyID)
				)	
				 AND
					o.Deleted = 0
				ORDER BY a.Agency, r.[Role], o.LastName, o.FirstName
	END
GO
GRANT VIEW DEFINITION ON [OfficerGetBySearch] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OfficerGetBySearch] TO [db_dml]
GO
