/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderServiceAttributesAdd] @OffenderID INT, @ServiceID INT, @AttributeName VARCHAR(MAX), @AttributeValue VARCHAR(MAX), @DataType VARCHAR(35)      
AS      
      
--Adds a new attribute node.      
BEGIN TRAN      
UPDATE OffenderServices      
SET ServiceAttributes.modify('insert (<Attribute Name="{sql:variable("@AttributeName")}"><DataType>{sql:variable("@DataType")}</DataType><AttributeValue>{sql:variable("@AttributeValue")}</AttributeValue></Attribute>) as last into /ServiceAttributes[1]')  
    
WHERE OffenderID = @OffenderID AND ServiceID = @ServiceID AND ServiceAttributes.exist('/ServiceAttributes/Attribute [@Name=sql:variable("@AttributeName")]') = 0   
COMMIT TRAN;   
GO
GRANT EXECUTE ON [OffenderServiceAttributesAdd] TO [db_dml]
GO
