/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mAlarmProtocolSetByID]

	@ProtocolSetID	INT

AS
	select g.AlarmProtocolSetName, g.AlarmProtocolSetTypeID, g.AgencyID,g.OfficerID, g.OffenderID,g.CreatedByID
	from AlarmProtocolSet  g 
	WHERE g.AlarmProtocolSetID=@ProtocolSetID



GO
GRANT EXECUTE ON [mAlarmProtocolSetByID] TO [db_dml]
GO
