/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mBeaconGetAddressBySerialNumbertest]

@Beaconserial nvarchar(50),
@Offenderid Int,
@Address varchar(100) OUTPUT, 
@Latitude float OUTPUT, 
@Longitude float OUTPUT


AS 

Select 
@Address = ad.Street1+' '+ad.City+', '+st.Abbreviation+' '+ad.ZipCode,
@Longitude = gpl.longitude,
@Latitude = gpl.latitude

FROM Address ad
JOIN Beacon b ON b.addressid = ad.id
JOIN Gpslocation gpl ON gpl.addressid = ad.id
JOIN State st ON st.stateid = ad.stateid
JOIN BEaconOffender bo ON bo.Beaconid = b.id AND b.identifier = @Beaconserial AND bo.Offenderid = @offenderid





GO
GRANT EXECUTE ON [mBeaconGetAddressBySerialNumbertest] TO [db_dml]
GO
