/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [HeightMeasurementGetAll]

AS

	SELECT	HeightMeasurementID, HeightMeasurement
	FROM	HeightMeasurement
GO
GRANT VIEW DEFINITION ON [HeightMeasurementGetAll] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [HeightMeasurementGetAll] TO [db_dml]
GO
