/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [BillingServiceUpdate] 
@BillingServiceID INT, 
@StartDateTime DATETIME, 
@BillingServiceTypeID INT,
@NumberOfBeacons INT,
@Rate FLOAT,
@Price FLOAT,
@IsEArrest BIT
AS
--Adds new Billing Service record to BillingService.
SET NOCOUNT ON;

--Check for latent transcations.
IF @@TRANCOUNT > 0
	BEGIN
		ROLLBACK TRANSACTION
	END;

BEGIN TRANSACTION;
BEGIN TRY
	UPDATE dbo.BillingService
	SET		StartDateTime = @StartDateTime,
			BillingServiceTypeID = @BillingServiceTypeID
	WHERE	ID = @BillingServiceID
	
	IF (@IsEArrest = 1)
	BEGIN
		UPDATE dbo.EArrestService
		SET		PricePerBeacon = @Price,
				BeaconLimit = @NumberOfBeacons,
				Rate = @Rate
		WHERE	ClassicBillingServiceID = (SELECT ID FROM ClassicBillingService WHERE BillingServiceID = @BillingServiceID)
	END
END TRY
BEGIN CATCH
	--Catch and return error.
    SELECT 
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_SEVERITY() AS ErrorSeverity,
        ERROR_STATE() as ErrorState,
        ERROR_PROCEDURE() as ErrorProcedure,
        ERROR_LINE() as ErrorLine,
        ERROR_MESSAGE() as ErrorMessage;
	--Rollback outstanding transactions.
	IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION
		END;
END CATCH;

IF @@TRANCOUNT > 0
	BEGIN
		COMMIT TRANSACTION
	END;

GO
GRANT EXECUTE ON [BillingServiceUpdate] TO [db_dml]
GO
