/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mProtocolActionContactInfoAll]


AS
	select g.AlarmProtocolActionContactInfoID, g.AlarmProtocolActionContactInfo, 
		g.RoleID, g.DisplayOrder
			
	from AlarmProtocolActionContactInfo  g 
GO
GRANT EXECUTE ON [mProtocolActionContactInfoAll] TO [db_dml]
GO
