/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoScheduleItemUpdatePrority]
	@GeoScheduleItemId uniqueidentifier,
	@SchedulePriority int	
AS

SET NOCOUNT ON;
BEGIN
	BEGIN TRAN
		UPDATE  GeoScheduleItem
		SET	SchedulePriority = @SchedulePriority		
		WHERE GeoScheduleItemId = @GeoScheduleItemId
	COMMIT TRAN
END










GO
GRANT EXECUTE ON [GeoScheduleItemUpdatePrority] TO [db_dml]
GO
