/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [BloodTypeGetAllTypes]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT *
	FROM BloodType
END

GO
GRANT VIEW DEFINITION ON [BloodTypeGetAllTypes] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [BloodTypeGetAllTypes] TO [db_dml]
GO
