/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [StaticOffenderGetLastAlarm]

	@OffenderID	INT

AS
	SELECT	top 1 * FROM  Alarm a INNER JOIN EventType et ON et.EventTypeID=a.EventTypeID
	WHERE a.OffenderID=@OffenderID ORDER BY a.eventtime desc
	



GO
GRANT VIEW DEFINITION ON [StaticOffenderGetLastAlarm] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [StaticOffenderGetLastAlarm] TO [db_dml]
GO
