/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmProtocolEventGetAll]

AS

	SELECT	AlarmProtocolEventID, GatewayEventID, AlarmName
	FROM	AlarmProtocolEvent
	Where     Visible = 1
	ORDER BY DisplayOrder
GO
GRANT VIEW DEFINITION ON [AlarmProtocolEventGetAll] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [AlarmProtocolEventGetAll] TO [db_dml]
GO
