/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoRuleGroupOwnerGetByOwner]
	@OwnerType	INT,
	@OwnerID	INT
AS

SELECT
	grgo.GeoRuleGroupOwnerID,
	grgo.OwnerType,
	grgo.OwnerID,
	grgo.GeoRuleGroupID
FROM
	GeoRuleGroupOwner grgo
WHERE
	@OwnerType = grgo.OwnerType AND
	@OwnerID = grgo.OwnerID
GO
GRANT EXECUTE ON [GeoRuleGroupOwnerGetByOwner] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [GeoRuleGroupOwnerGetByOwner] TO [db_object_def_viewers]
GO
