/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmProtocolSetGetByOfficerID]

	@OfficerID	INT

AS

	SELECT	AlarmProtocolSetID, AlarmProtocolSetName
	FROM	AlarmProtocolSet
	WHERE	OfficerID = @OfficerID AND (Deleted=0 OR Deleted IS NULL)
	ORDER BY AlarmProtocolSetName
GO
GRANT EXECUTE ON [AlarmProtocolSetGetByOfficerID] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [AlarmProtocolSetGetByOfficerID] TO [db_object_def_viewers]
GO