/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ContactBackupGetByUserID]    
 @iUserID int    
AS    
BEGIN    
 SET NOCOUNT ON;    
    
 SELECT c.*, u.UserTypeId    
 FROM ContactBackup c  JOIN [User]u ON u.UserID= c.ContactUserID    
 WHERE c.UserID = @iUserID   
END  
GO
GRANT EXECUTE ON [ContactBackupGetByUserID] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [ContactBackupGetByUserID] TO [db_object_def_viewers]
GO
