/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OperatorGetGridInfo]

	AS

	SELECT	o.OperatorID, o.FirstName, o.LastName, r.[Role]
	FROM	Operator o
	LEFT JOIN [User] u ON o.UserID = u.UserID
	LEFT JOIN User_Role ur ON u.UserID = ur.UserID
	LEFT JOIN [Role] r ON ur.RoleID = r.RoleID
	ORDER BY r.[Role], o.LastName, o.FirstName
GO
GRANT VIEW DEFINITION ON [OperatorGetGridInfo] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OperatorGetGridInfo] TO [db_dml]
GO
