/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [GetAlarmProtocolActionRecipientOffender] 
	-- Add the parameters for the stored procedure here
	
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT DISTINCT  aps.AlarmProtocolSetName ,aps.AlarmProtocolSetID, apa.alarmprotocolactionID
	FROM alarmprotocolaction apa 
		LEFT JOIN AlarmProtocolSet aps ON    
        apa.alarmprotocolsetID = aps.alarmprotocolsetID   
	WHERE recipient= 'offender'
END


GO
GRANT EXECUTE ON [GetAlarmProtocolActionRecipientOffender] TO [db_dml]
GO
