/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderAddCharge]
	@iOffenderCurrentChargeID int OUTPUT,
	@iOffenderID int,
	@sCaseChargeDescription nvarchar(100),
	@sCaseChargeCode nvarchar(50)
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO OffenderCurrentCharge
	(OffenderID, OffenderCharge, OffenderChargeCode)
	VALUES
	(@iOffenderID, @sCaseChargeDescription, @sCaseChargeCode)

	SET @iOffenderCurrentChargeID = @@IDENTITY
END

GO
GRANT VIEW DEFINITION ON [OffenderAddCharge] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OffenderAddCharge] TO [db_dml]
GO
