/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [rprtMoveBucket2ToBucket3]
AS
BEGIN
	DECLARE @bucket2MaxDate DateTime
	DECLARE @movedRecordCount bigint
	SELECT @bucket2MaxDate = DateADD(month,-5,getdate())
	SELECT top 1000 *
INTO #rprtMoveBucket2ToBucket3 
FROM rprtEventsBucket2 WITH (NOLOCK) WHERE EventDateTime<@bucket2MaxDate
ORDER BY EventDatetime
	SELECT @movedRecordCount=COUNT(*) FROM #rprtMoveBucket2ToBucket3
	--insert into bucket2	
	INSERT rprtEventsBucket3 
		( EventID,DeviceID,EventTime,EventDateTime,EventParameter,TrackerNumber,EventName,ReceivedTime,OfficerID,
		OffenderID,AgencyID,Latitude,Longitude,OPR,SO,NoteCount,AlarmType,AlarmID,GeoRule,AlarmAssignmentStatusID,
		AlarmAssignmentStatusName,AcceptedBy,ActivateDate,DeActivateDate,GpsValid,GpsValidSatellites,AcceptedDate,
		EventTypeGroupID,EventQueueID,OffenderName,OffenderDeleted,Address )
	SELECT EventID,DeviceID,EventTime,EventDateTime,EventParameter,TrackerNumber,EventName,ReceivedTime,OfficerID,
		OffenderID,AgencyID,Latitude,Longitude,OPR,SO,NoteCount,AlarmType,AlarmID,GeoRule,AlarmAssignmentStatusID,
		AlarmAssignmentStatusName,AcceptedBy,ActivateDate,DeActivateDate,GpsValid,GpsValidSatellites,AcceptedDate,
		EventTypeGroupID,EventQueueID,OffenderName,OffenderDeleted,Address
	FROM #rprtMoveBucket2ToBucket3 

	--delete original records
	DELETE FROM rprtEventsBucket2 WHERE EventPrimaryID in (SELECT EventPrimaryID from #rprtMoveBucket2ToBucket3)
	drop table #rprtMoveBucket2ToBucket3
	SELECT @movedRecordCount
END

GO
GRANT VIEW DEFINITION ON [rprtMoveBucket2ToBucket3] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [rprtMoveBucket2ToBucket3] TO [db_dml]
GO
