/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TrackerGetByOffenderID]

	@OffenderID		INT

AS
	
	-- get tracker assigned to offender (if any)
	SELECT	
		ta.TrackerID, t.TrackerNumber
	FROM	
		TrackerAssignment ta
		INNER JOIN Tracker t ON t.TrackerID = ta.TrackerID
		INNER JOIN Offender o ON o.OffenderID = ta.OffenderID
	WHERE	
		ta.TrackerAssignmentID = (SELECT MAX(TrackerAssignmentID) FROM TrackerAssignment ta WHERE ta.OffenderID = @OffenderID)
		AND ta.TrackerAssignmentTypeID = 1
		AND ta.OffenderID = @OffenderID
		AND t.Deleted = 0
		AND o.Deleted = 0 
GO
GRANT EXECUTE ON [TrackerGetByOffenderID] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [TrackerGetByOffenderID] TO [db_object_def_viewers]
GO
