/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TrackerActionArchiveByTrackerID] 
	@TrackerID int
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO TrackerActionArchive
	(TrackerActionID, TrackerActionTypeID, TrackerID, TrackerActionDateTime, CreatedByID)
	SELECT TrackerActionID, TrackerActionTypeID, TrackerID, TrackerActionDateTime, CreatedByID
	FROM TrackerAction
	WHERE TrackerID = @TrackerID
	ORDER BY TrackerActionDateTime

	DELETE TrackerAction
	WHERE TrackerID = @TrackerID

END
GO
GRANT VIEW DEFINITION ON [TrackerActionArchiveByTrackerID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [TrackerActionArchiveByTrackerID] TO [db_dml]
GO
