/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [StaticErrorTypeActions]
 @ErrorTypeID int
AS

select * from LogErrorTypesActions WHERE ErrorTypeID=@ErrorTypeID
    


GO
GRANT VIEW DEFINITION ON [StaticErrorTypeActions] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [StaticErrorTypeActions] TO [db_dml]
GO
