/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [BeaconGetAll]

AS

	SET NOCOUNT ON

	SELECT	b.ID as 'BeaconID',b.Identifier,b.AddressID,
            bo.OffenderID,obt.BeaconThresholdID,
            a.Street1,a.Street2,a.ZipCode,a.City,a.StateID,
            g.Longitude,g.Latitude

	FROM	Beacon b
inner join BeaconOffender bo 	ON bo.beaconid = b.ID
inner join OffenderBeaconThreshold obt ON bo.OffenderID = obt.OffenderID 
inner join Address a ON a.ID = b.AddressID 
inner join GPSLocation g ON g.AddressID = a.ID






GO
GRANT EXECUTE ON [BeaconGetAll] TO [db_dml]
GO
