/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportingIntervalGetByOffenderID] 
@TimeSeconds INT OUTPUT,
@OffenderID INT   

AS  
  
--Procedure returns data about and Agencies billing services.  
  
SET NOCOUNT ON;  
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;  

set @TimeSeconds=(SELECT top 1 rs.TimeSeconds
FROM dbo.OptionalBillingServiceOptionOffender ob 
INNER JOIN dbo.BillingServiceOptionReportingInterval bor ON ob.BillingServiceOptionID = bor.BillingServiceOptionID 
INNER JOIN dbo.refServiceOptionReportingInterval rs ON bor.ReportingIntervalID = rs.ID 

WHERE ob.OffenderID = @OffenderID) 

if @TimeSeconds is NULL 

set @TimeSeconds=(SELECT top 1 rs.TimeSeconds
FROM dbo.BillingService b 
INNER JOIN dbo.BillingServiceOption o ON b.ID = o.BillingServiceID 
INNER JOIN dbo.BillingServiceOptionReportingInterval bor ON o.ID = bor.BillingServiceOptionID 
INNER JOIN dbo.refServiceOptionReportingInterval rs ON bor.ReportingIntervalID = rs.ID 
INNER JOIN dbo.OffenderOptionalBillingService offs ON b.ID = offs.BillingServiceID 
WHERE offs.OffenderID = @OffenderID) 
 
if @TimeSeconds is NULL 

set @TimeSeconds=(SELECT top 1 rs.TimeSeconds 
FROM dbo.BillingService b 
INNER JOIN dbo.BillingServiceOption o ON b.ID = o.BillingServiceID 
INNER JOIN dbo.BillingServiceOptionReportingInterval bor ON o.ID = bor.BillingServiceOptionID 
INNER JOIN dbo.refServiceOptionReportingInterval rs ON bor.ReportingIntervalID = rs.ID 
Inner join dbo.offender ofe on ofe.Agencyid= b.agencyid
WHERE ofe.offenderID = @OffenderID and b.BillingservicetypeID=1)

if @TimeSeconds is NULL
BEGIN
declare @temp2 table (val int)
insert @temp2 (val) exec OffenderServiceGetTimeInterval @offenderID
set @TimeSeconds = (select * from @temp2)
END

if @TimeSeconds is NULL 
set @TimeSeconds=-1

GO
GRANT EXECUTE ON [ReportingIntervalGetByOffenderID] TO [db_dml]
GO
