/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mProtocolActionByID]

	@ProtocolActionID	INT

AS
	select g.AlarmProtocolSetID, g.AlarmProtocolEventID, g.Priority, g.CreatedByID,g.[Type]
			
	from AlarmProtocolAction  g 
	WHERE g.AlarmProtocolActionID=@ProtocolActionID
GO
GRANT EXECUTE ON [mProtocolActionByID] TO [db_dml]
GO
