/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TrackerRmaAdd] 
	-- Add the parameters for the stored procedure here
	@TrackerID int,
	@CreatedByID int
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

IF
	(SELECT 
		COUNT(*)
	FROM 
		[TrackerRma]
	WHERE
		TrackerID = @TrackerID AND RemovedDate IS NULL
	) = 0

	BEGIN

		INSERT INTO [TrackerRma] 
			(TrackerID, CreatedDate , CreatedByID ) 
		VALUES
			(@TrackerID, GETDATE(), @CreatedByID )

		UPDATE [Tracker]
		SET 
			[RmaID] = @@IDENTITY
		WHERE 
			TrackerID = @TrackerID AND Deleted = 0

	END

ELSE

	BEGIN
		UPDATE [Tracker]
		SET 
			[RmaID] = (SELECT TOP (1) RmaID FROM TrackerRma WHERE TrackerID = @TrackerID AND RemovedDate IS NULL)
		WHERE 
			TrackerID = @TrackerID AND Deleted = 0
	END

END
GO
GRANT EXECUTE ON [TrackerRmaAdd] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [TrackerRmaAdd] TO [db_object_def_viewers]
GO
