/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TrackerActionDeleteActiveSiren]
(@TrackerID int)
AS
BEGIN
	SET NOCOUNT ON;	
	DELETE FROM ActiveSirens WHERE TrackerID = @TrackerID
END

GO
GRANT EXECUTE ON [TrackerActionDeleteActiveSiren] TO [db_dml]
GO
