/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [Offender_AlarmProtocolSetGetByOffenderID]

	@OffenderID	INT,
	@AlarmProtocolSetID	INT OUTPUT

AS

	SET @AlarmProtocolSetID = ISNULL
		(
			(
			SELECT TOP 1 AlarmProtocolSetID
			FROM Offender_AlarmProtocolSet
			WHERE OffenderID = @OffenderID AND
				Deleted = 0
			ORDER BY Offender_AlarmProtocolSetID DESC
			),
		0)
GO
GRANT VIEW DEFINITION ON [Offender_AlarmProtocolSetGetByOffenderID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [Offender_AlarmProtocolSetGetByOffenderID] TO [db_dml]
GO
