/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [spAgencyGetAllProtocolSets]

@agencyid int
AS
Select
 AlarmProtocolSetName
,AlarmProtocolSetId

From alarmProtocolset 
Where agencyid = @agencyid
GO
GRANT EXECUTE ON [spAgencyGetAllProtocolSets] TO [db_dml]
GO
