/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OfficerGetGridInfoByAgencyID]

	@AgencyID	INT

AS

	SELECT	o.OfficerID, o.FirstName, o.LastName, r.[Role], a.Agency
		FROM	Officer o
		left JOIN User_Role ur ON o.UserID = ur.UserID
		left JOIN [Role] r ON ur.RoleID = r.RoleID
		LEFT JOIN Agency a ON o.AgencyID = a.AgencyID
		WHERE	
		(
			(@AgencyID = 0)
			or
			(o.AgencyID = @AgencyID )
		)
		AND o.Deleted = 0
		ORDER BY a.Agency, r.[Role], o.LastName, o.FirstName
GO
GRANT VIEW DEFINITION ON [OfficerGetGridInfoByAgencyID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OfficerGetGridInfoByAgencyID] TO [db_dml]
GO
