/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [StaticVictimGetAll]



AS

BEGIN

	SET NOCOUNT ON;

	SELECT 
		o.OffenderID,
		o.SuffixID,
		o.SalutationID,
		o.FirstName,
		o.LastName,
		o.MiddleName,
		o.AgencyID,
		o.CreatedByID,
		o.ModifiedByID,
		o.HomeStateOrProvinceID,
		o.VictimProxViolationDistance,
		o.VictimProxAlertDistance,
		o.VictimAssociatedOffenderID,
		ta.TrackerAssignmentID,
		ta.TrackerID,
		ta.CreatedBy as 'TrackerAssignmentCreatedBy',
		ta.SupervisionOfficerID,
		ta.AssignmentDate as 'TrackerAssignmentDate',
		oo.OfficerID,
		o.Deleted
	FROM 
		Offender o 
		LEFT JOIN TrackerAssignment ta ON ta.OffenderID = o.OffenderID 
			AND ta.TrackerAssignmentID = (SELECT MAX(TrackerAssignmentID) FROM TrackerAssignment ta WHERE ta.OffenderID = o.OffenderID)
		LEFT JOIN Offender_Officer oo ON oo.OffenderID = o.OffenderID
	WHERE 
		o.Victim = 1
END

GO
GRANT EXECUTE ON [StaticVictimGetAll] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [StaticVictimGetAll] TO [db_object_def_viewers]
GO
