/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderGetAllNonVictimsByAgencyID]

	@AgencyID	INT

AS

		SELECT o.OffenderID, 
		ISNULL(o.LastName + ', ', '') + ISNULL(o.FirstName, '') AS 'OffenderName'
		FROM	Offender o  (NOLOCK) 
		WHERE o.AgencyID = @AgencyID
			AND o.Deleted = 0
			AND o.Victim = 0
		ORDER BY o.LastName, o.FirstName	



GO
GRANT VIEW DEFINITION ON [OffenderGetAllNonVictimsByAgencyID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OffenderGetAllNonVictimsByAgencyID] TO [db_dml]
GO
