/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoRuleGetByAreaID]
    @iOffenderID INT,
    @iAreaID INT
AS
    SELECT	GeoRuleID 
	FROM GeoRule_Offender
	WHERE	(OffenderID = @iOffenderID) AND (AreaID = @iAreaID)

GO
GRANT EXECUTE ON [GeoRuleGetByAreaID] TO [db_dml]
GO
