/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mAlarmWorkflowInformation]

@EventTime BigInt,
@DeviceID BigInt,
@EventTypeID BigInt

AS

BEGIN
	
SET NOCOUNT ON;

SELECT 
a.AlarmID,
aas.AlarmAssignmentID,
mca.AlarmID as 'MCAlarmID', 
mcsa.AlarmID as 'MCSubAlarmID',
laa.AlarmID as 'LoggedActions' 
FROM [dbo].Alarm a      
LEFT JOIN AlarmAssignment aas ON aas.AlarmID=a.AlarmID           --alarm was worked has alarm assigment  
LEFT JOIN rprtAlarmMonitorCenterGrid mca ON mca.AlarmID=a.AlarmID        --alarm in in MC center  
LEFT JOIN rprtAlarmMonitorCenterSubGrid mcsa ON mcsa.AlarmID=a.AlarmID       --alram in in MC as sub-alarm  
LEFT JOIN logAutocompletedActions laa ON laa.AlarmID = a.AlarmID and laa.GUID = (select top 1 laa2.guid from logAutocompletedActions laa2 where laa2.AlarmID = a.AlarmID)
WHERE @EventTypeID = a.EventTypeID AND @EventTime = a.EventTime AND @DeviceID = a.TrackerID  --alarm in alarm table  
END
GO
GRANT EXECUTE ON [mAlarmWorkflowInformation] TO [db_dml]
GO
