/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoScheduleItemDelete]
	
        @GeoScheduleItemId uniqueidentifier,
		@ScheduleId uniqueidentifier      

AS
  
SET NOCOUNT ON;
BEGIN
	BEGIN TRAN
		DELETE FROM GeoScheduleItem
		WHERE GeoScheduleItemId = @GeoScheduleItemId and ScheduleId = @ScheduleId
	COMMIT TRAN
END
   




GO
GRANT EXECUTE ON [GeoScheduleItemDelete] TO [db_dml]
GO
