/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportOffenderEventHistory2]
        @TimeZoneOffset int,
        @TrackerID              int,
        @SO                             int,
        @OPR                    int,
        @StartDate              bigint,
        @EndDate                bigint
AS
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

BEGIN
SET NOCOUNT ON;
DECLARE @Start Datetime,@End Datetime;
SET @Start=dbo.convertlongtodate(@StartDate);
SET @End=dbo.convertlongtodate(@EndDate);

WITH Events_CTE(EventDateTime,EventName,GeoRule,Gpsvalid,GpsValidSatellites,Longitude,Latitude,AcceptedDate,TrackerNumber,AgencyID, OfficerID,[Address],AcceptedBy,Eventid)
AS
(

SELECT TOP 5000 EventDateTime,EventName,GeoRule,Gpsvalid,GpsValidSatellites,Longitude,Latitude,AcceptedDate,TrackerNumber,AgencyID, OfficerID,[Address],AcceptedBy,eventid
FROM dbo.OffenderEventHistory
WHERE (EventDateTime BETWEEN @Start AND @End)
            AND (@TrackerID = 0 OR DeviceID = @TrackerID)
            AND (@SO<0 OR SO=@SO)
            AND (@OPR<0 OR OPR=@OPR)
)

SELECT 
--            (CONVERT(DATETIME,DATEADD ( mi,@TimeZoneOffset, (Convert(DateTime,
--            (DATEADD(ms, (EventTime / CAST(10000 AS bigint)) % 86400000,
--            DATEADD(day, EventTime / CAST(864000000000 AS bigint) - 109207, 0)))
--            ))))) 
                     DateAdd(mi,@TimeZoneOffset,EventDateTime)as 'Event Time',
                        EventName AS 'Event Name',
                        GeoRule AS 'Geo-Rule Name',
                        (CASE WHEN  r.eventid  IN (176,177,178,179,180,181,182,184,185,192,193,194,195) or ( Gpsvalid = 1 Or GpsValidSatellites = 1)
THEN [Address]
ELSE 'Unavailable'  
END)
 AS 'Address',
                        Longitude,
						Latitude,
                        DATEADD(mi,@TimeZoneOffset,AcceptedDate) AS 'Accepted Date',
 AcceptedBy AS 'Accepted By',                         
 TrackerNumber as IMEI,
 o.FirstName + ' ' + o.LastName as 'Officer',
 0 Notes,
 a.Agency

 FROM Events_CTE r  LEFT OUTER JOIN Agency a ON r.AgencyID = a.AgencyID
 LEFT OUTER JOIN Officer o ON r.OfficerID = o.OfficerID
 ORDER BY EventDateTime
END



GO
GRANT VIEW DEFINITION ON [ReportOffenderEventHistory2] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [ReportOffenderEventHistory2] TO [db_dml]
GO
