/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoruleGetNewName]


@Offenderid int,
@EventParameter Bigint,
@GeoruleName nvarchar(50) OutPut

AS
Select 
@GeoruleName = gr.GeoruleNAme
From Georule_Offender go
JOIN Georule gr ON gr.Georuleid = go.Georuleid
Where go.Offenderid = @Offenderid AND go.Zoneid = @EventParameter

GO
GRANT EXECUTE ON [GeoruleGetNewName] TO [db_dml]
GO
