/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [UserUpdate]

	@UserID			INT,
	@UserName		NVARCHAR(25),
	@UserPassword	NVARCHAR(50),
	@ModifiedByID	INT,
	@UserPassCode	NVARCHAR(50)

AS

	-- verify UserName does not already exist
--	DECLARE	@RecordCount INT
--	SELECT	@RecordCount = COUNT (*)
--	FROM	[User]
--	WHERE	UserName = @UserName

--	IF @RecordCount > 0
--	BEGIN
--		RAISERROR('User Name "%s" already taken.  Please choose another.', 16, 1, @UserName)
--	END
--	ELSE
	BEGIN
		UPDATE	[User]
		SET		UserName = @UserName,
				UserPassword = @UserPassword,
				ModifiedDate = GETDATE(),
				ModifiedByID = @ModifiedByID,
				UserPassCode	=	@UserPassCode
		WHERE	UserID = @UserID
	END
GO
GRANT VIEW DEFINITION ON [UserUpdate] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [UserUpdate] TO [db_dml]
GO
