/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mAlarmSuspendedUpdate]
	@AlarmSuspendedID bigint,
	@AgencyID	bigint,
	@OfficerID  bigint,
   @OffenderID  bigint,
	@RequestingOfficerID  bigint,
	@AlarmTypeID  int,
	@StartTime  DateTime,
	@EndTime  DateTime,
	@CreatedBy  bigint,
	@ConfirmationNumber bigint
AS

UPDATE AlarmSuspended
SET AgencyID = @AgencyID,
	OfficerID = @OfficerID,
	OffenderID = @OffenderID,
	RequestingOfficerID = @RequestingOfficerID,
	AlarmProtocolEventID = @AlarmTypeID,
	StartTime = @StartTime,
	EndTime = @EndTime,
	CreatedBy = @CreatedBy,
	ConfirmationNumber = @ConfirmationNumber
WHERE AlarmSuspendedID  = @AlarmSuspendedID

GO
GRANT EXECUTE ON [mAlarmSuspendedUpdate] TO [db_dml]
GO
