/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmProtocolActionPriorityGetByRoleID]

	@RoleID	INT

AS

	SELECT	AlarmProtocolActionPriorityID, AlarmProtocolActionPriority
	FROM	AlarmProtocolActionPriority
	WHERE	RoleID <= @RoleID


GO
GRANT VIEW DEFINITION ON [AlarmProtocolActionPriorityGetByRoleID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [AlarmProtocolActionPriorityGetByRoleID] TO [db_dml]
GO
