/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReverseGeoCode_UpdateStreetAddressCache2]
	
	@Latitude int,
	@Longitude int,
	@Address varchar(200),
	@EventPrimaryID bigint = 0,
	@DateRetrieved datetime = null,
	@CacheHits int = 0

AS
INSERT INTO dbo.ReverseGeoCode_StreetAddressCache 
	(Latitude, Longitude, StreetAddress, EventPrimaryID, DateRetrieved, CacheHits)
	VALUES (@Latitude, @Longitude, @Address, @EventPrimaryID, @DateRetrieved, @CacheHits)





GO
GRANT EXECUTE ON [ReverseGeoCode_UpdateStreetAddressCache2] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [ReverseGeoCode_UpdateStreetAddressCache2] TO [db_object_def_viewers]
GO
