/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OfficerGetRolesByAgencyID] 
	@AgencyID int = 0

AS
BEGIN
	SET NOCOUNT ON;

    SELECT 
		r.RoleID, r.[Role]
	FROM
		Officer o
		LEFT JOIN User_Role ur ON o.UserID = ur.UserID
		LEFT JOIN [Role] r ON ur.RoleID = r.RoleID
		LEFT JOIN Agency a ON o.AgencyID = a.AgencyID
	WHERE	
		(
			(@AgencyID = 0)
			OR
			(o.AgencyID = @AgencyID )
		)
		AND (o.Deleted = 0)
	GROUP BY
		r.RoleID, r.[Role]
	ORDER BY 
		r.[Role]
END
GO
GRANT EXECUTE ON [OfficerGetRolesByAgencyID] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [OfficerGetRolesByAgencyID] TO [db_object_def_viewers]
GO
