/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportGetGridReports]
@ReportType int,
@SAuser int,
@AgencyID int



AS
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT     Reports.ReportID, Reports.ReportName, [User].UserName, Reports.CreateDate , Reports.ReportTypeID
FROM         Reports 
INNER JOIN [User] ON Reports.CreatedByID = [User].UserID
left join officer o on  Reports.CreatedByID= o.UserID
left join operator opr on  Reports.CreatedByID= opr.UserID
left join DistributorEmployee de on Reports.CreatedByID= de.UserID
		 
             where  Reports.ReportTypeID=@ReportType
           		and 
					(
						(
							(@AgencyID=0)
							AND
							(
								(@SAuser=0)
								or
								(
									(@SAuser<>0)
									AND
									(
										--ALL THAT THE OWNER IS sauser
										opr.OperatorId is not null
										or
										de.DistributorEmployeeID is not null
									)
								)		
							
							)	
						)
						or
						(
							(@agencyID<>0)
							AND
							(
							 --ALL OF THIS AGENCY
							 o.AgencyID=@AgencyID
							)
						)
					)		
GO
GRANT VIEW DEFINITION ON [ReportGetGridReports] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [ReportGetGridReports] TO [db_dml]
GO
