/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TrackerDeactivationReasonGet] 
        
AS
BEGIN
        SET NOCOUNT ON;

        SELECT
                *
        FROM 
                TrackerDeactivationReason
        
END
GO
GRANT VIEW DEFINITION ON [TrackerDeactivationReasonGet] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [TrackerDeactivationReasonGet] TO [db_dml]
GO
