/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TrackerActionGetAll] 
	@AgencyID	int = 0
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT
		[TrackerActionID],
		[TrackerActionTypeID],
		ta.[TrackerID],
		[TrackerActionDateTime],
		ta.[CreatedByID],
		t.AgencyID
	FROM 
		[TrackerAction] ta
		INNER JOIN Tracker t ON t.TrackerID = ta.TrackerID AND t.Deleted = 0
	WHERE
		@AgencyID = 0 OR t.AgencyID = @AgencyID

	ORDER BY [TrackerActionDateTime]
	OPTION(MAXDOP 1) 
END


GO
GRANT EXECUTE ON [TrackerActionGetAll] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [TrackerActionGetAll] TO [db_object_def_viewers]
GO
