/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [EventNoteAdd]
	@EventNoteID int OUTPUT,
	@DeviceID int, 
	@EventTime bigint,
	@EventID int,
	@Note nvarchar(2000),
	@CreatedByID int

AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO EventNote
	(DeviceID, EventTime, EventID, Note, CreatedByID, CreatedDate)
	VALUES
	(@DeviceID, @EventTime, @EventID, @Note, @CreatedByID, GetDate())

	SET @EventNoteID = @@IDENTITY
END
GO
GRANT EXECUTE ON [EventNoteAdd] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [EventNoteAdd] TO [db_object_def_viewers]
GO
