/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmGetByIncidentID]    
    
 @IncidentID    nvarchar(10),    
 @UserID   INT,    
 @RoleID int     
     
AS    

IF @RoleID =15
 BEGIN    
	SELECT a.alarmID, a.offenderID ,a.eventtime  
	FROM logautocompletedActions as l
	inner join alarm as a on a.alarmid= l.alarmid
	inner JOIN Offender_Officer  oo (NOLOCK) ON a.OffenderID = oo.OffenderID   
	inner JOIN Officer offi ON offi.officerID = oo.Officerid       
	where IncidentID = @IncidentID
	and offi.userid=@UserID;
 END
ELSE IF @RoleID =2 or @RoleID =3
 BEGIN    
	SELECT a.alarmID, a.offenderID ,a.eventtime  
	FROM logautocompletedActions as l
	inner join alarm as a on a.alarmid= l.alarmid
	inner JOIN offender offe ON offe.offenderID = a.offenderID    
	inner join officer offi on offi.AgencyID = offe.AgencyID   
	where IncidentID = @IncidentID
	and offi.userid=@UserID;
 END
ELSE
 BEGIN    
	SELECT a.alarmID, a.offenderID ,a.eventtime  
	FROM logautocompletedActions as l
	inner join alarm as a on a.alarmid= l.alarmid
	where IncidentID = @IncidentID
 END  
GO
GRANT EXECUTE ON [AlarmGetByIncidentID] TO [db_dml]
GO
