/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mAutoCallIncidentIDGetLast]

AS

	SET NOCOUNT ON
	SELECT top 1 IncidentID 
    FROM dbo.AutoCallIncidents order by IncidentID desc
GO
GRANT EXECUTE ON [mAutoCallIncidentIDGetLast] TO [db_dml]
GO
