/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mOffenderCreate]
	@CreatedByID int,
	@AgencyID int,
	@OfficerID int,
	@FirstName NVARCHAR(50),
	@MiddleName NVARCHAR(50) = NULL,
	@LastName NVARCHAR(50), 
	@BirthDate DATETIME,
	@OffenderID int OUTPUT,
	@RiskLevelID int,
	@OffenderPay bit

AS
BEGIN
SET NOCOUNT ON;
	
INSERT INTO [dbo].[Offender] (
	[CreatedDate],
	[CreatedByID],
	[AgencyID],
	[FirstName],
	[MiddleName],
	[LastName],
	[BirthDate],
	[Victim],
	[Deleted],
	[RiskLevelID],
	[OffenderPay]
) 
VALUES 
(
	GETDATE(),
	@CreatedByID,
	@AgencyID,
	@FirstName,
	@MiddleName,
	@LastName,
	@BirthDate,
	0,
	0,
	@RiskLevelID,
	@OffenderPay 
)

SET @OffenderID = SCOPE_IDENTITY()

IF @OfficerID IS NOT NULL
BEGIN

INSERT INTO [dbo].Offender_Officer (
	[OffenderID],
	[OfficerID]
)
VALUES
(	
	@OffenderID,
	@OfficerID
)

END

END

GO
GRANT EXECUTE ON [mOffenderCreate] TO [db_dml]
GO
