/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
-- =============================================
-- Author:		Sajid Abbasi
-- Create date: 21-Oct-2009
-- Description:	The stored procedure gets the WhatsNewVersion field. This is the version of
-- WhatsNew.htm file. Version information is stored as mata tag in the file.
-- =============================================
CREATE PROCEDURE [UserPreferencesGetWhatsNewVersion]  
    @UserID int,
    @WhatsNewVersion varchar(50)OUTPUT
AS  
BEGIN  
SET NOCOUNT ON;
 SELECT @WhatsNewVersion = WhatsNewVersion  
  FROM dbo.UserPreferences   
  WHERE UserID = @UserID  
END

GO
GRANT EXECUTE ON [UserPreferencesGetWhatsNewVersion] TO [db_dml]
GO
