/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OfficerGetAllByAgencyID]

	@AgencyID	INT,
	@RoleID INT

		AS

		SELECT	o.OfficerID, 
				ISNULL(o.LastName + ', ', '') + ISNULL(o.FirstName, '') AS 'OfficerName'
		FROM	Officer o
		left JOIN [User_role] u on o.userid = u.userid 
		WHERE o.Deleted = '0'and 
		(
			(@AgencyID<0)
			or
			(o.AgencyID = @AgencyID)
		)
		and 
		(
			(@RoleID<0) 
			or 
			(u.RoleID=@RoleID)
		)
        and
        (
            (u.RoleID <> '3')
		)
		ORDER BY o.LastName, o.FirstName
GO
GRANT EXECUTE ON [OfficerGetAllByAgencyID] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [OfficerGetAllByAgencyID] TO [db_object_def_viewers]
GO
