/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mTrackerReplaceDeactivate]
        
	@TrackerActivationID INT,
	@TrackerID INT,
	@OffenderID INT,
	@OfficerID INT,
	@ModifiedByID INT,
	@TrackerDeactivationReasonID INT,
	@ReasonText VARCHAR(100),
	@DeactivateDate DATETIME OUTPUT,
	@ApprovedByID INT

AS

SET @DeactivateDate = GETDATE()

SELECT @TrackerActivationID = TrackerActivationID
FROM OffenderTrackerActivation
WHERE 
	TrackerID = @TrackerID
   AND OffenderID = @OffenderID
   AND OfficerID = @OfficerID
   AND DeActivateDate IS NULL

UPDATE OffenderTrackerActivation
SET 
	DeActivateDate = @DeactivateDate,
   ModifiedByID = @ModifiedByID, 
   TrackerDeactivationReasonID = @TrackerDeactivationReasonID, 
   ReasonText = @ReasonText,
   ApprovedById = @ApprovedByID

WHERE 
	TrackerID = @TrackerID
   AND OffenderID = @OffenderID
   AND OfficerID = @OfficerID
   AND DeActivateDate IS NULL



GO
GRANT EXECUTE ON [mTrackerReplaceDeactivate] TO [db_dml]
GO
