/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportInvalidPhone]

@Phone nvarchar(64)
AS
Select 
dp2.Propertyvalue AS SerialNumber
,dp.Propertyvalue As SimPhone
,dp3.propertyvalue As OveridePhone
,d.PhoneNumber AS SMSPhone
,d.MostLikelyPhoneNumber
,dp4.Propertyvalue As ICCID
from 
Gateway.dbo.Devices d
LEFT JOIN Gateway.dbo.Deviceproperties dp ON dp.deviceid = d.deviceid and dp.propertyid = '8203' 
LEFT JOIN Gateway.dbo.Deviceproperties dp2 ON dp2.deviceid = d.deviceid and dp2.propertyid = '8012'
LEFT JOIN Gateway.dbo.Deviceproperties dp3 ON dp3.deviceid = d.deviceid and dp3.propertyid = '8206'
LEFT JOIN Gateway.dbo.Deviceproperties dp4 ON dp4.deviceid = d.deviceid and dp4.propertyid = '8204'
where dp.propertyvalue like '%'+@phone+'%'
Order BY dp.Propertyvalue

GO
GRANT EXECUTE ON [ReportInvalidPhone] TO [db_dml]
GO
