/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoSchedule_QueueLogUpdate]
	@QueueSegmentID				INT,
	@AttemptTime				DATETIME,
	@GatewayRequestID			BIGINT = null,
	@UploadStatus				INT = null



AS



UPDATE GeoScheduleQueueLog
SET AttemptTime = @AttemptTime,
	GatewayRequestID = @GatewayRequestID,
	UploadStatus = @UploadStatus
WHERE
	QueueSegmentID = @QueueSegmentID


GO
GRANT EXECUTE ON [GeoSchedule_QueueLogUpdate] TO [db_dml]
GO
