/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [spAgencyGetAll] 

AS
BEGIN
	SET NOCOUNT ON;
SELECT
Agencyid,
Agency from Agency
Order BY Agency
END


 
 
GO
GRANT EXECUTE ON [spAgencyGetAll] TO [db_dml]
GO
