/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OperatorAdd]

	@OperatorID		INT OUTPUT,
	@UserID			INT,
	@Title			NVARCHAR(50) = null,
	@Department		NVARCHAR(50) = null,
	@SalutationID	INT = null,
	@FirstName		NVARCHAR(50),
	@MiddleName		NVARCHAR(50) = null,
	@LastName		NVARCHAR(50),
	@SuffixID		INT = null,
	@StreetLine1	NVARCHAR(50),
	@StreetLine2	NVARCHAR(50) = null,
	@City			NVARCHAR(50),
	@StateID		INT,
	@PostalCode		NVARCHAR(25),
	@CountryID		INT,
	@DayPhone		NVARCHAR(25),
	@EveningPhone	NVARCHAR(25) = null,
	@MobilePhone	NVARCHAR(25) = null,
	@Pager			NVARCHAR(25) = null,
	@Fax			NVARCHAR(25) = null,
	@EmailAddress1	NVARCHAR(50),
	@EmailAddress2	NVARCHAR(50) = null,
	@CreatedByID	INT,
	@CreatedDate	DATETIME = null OUTPUT,
	@ExtDayPhone    NVARCHAR(20) = null,
	@ExtEveningPhone NVARCHAR(20) = null
AS

	SET @CreatedDate = GETDATE()

	INSERT INTO Operator
	(UserID, Title, Department, SalutationID, FirstName, MiddleName, LastName,
	 SuffixID, StreetLine1, StreetLine2, City, StateID, PostalCode, CountryID,
	 DayPhone, EveningPhone, MobilePhone, Pager, Fax, EmailAddress1, EmailAddress2,
	 CreatedByID,CreatedDate,ExtDayPhone,ExtEveningPhone)
	VALUES
	(@UserID, @Title, @Department, @SalutationID, @FirstName, @MiddleName, @LastName,
	 @SuffixID, @StreetLine1, @StreetLine2, @City, @StateID, @PostalCode, @CountryID,
	 @DayPhone, @EveningPhone, @MobilePhone, @Pager, @Fax, @EmailAddress1, @EmailAddress2,
	 @CreatedByID,@CreatedDate,@ExtDayPhone,@ExtEveningPhone)

	SET @OperatorID = @@IDENTITY
GO
GRANT VIEW DEFINITION ON [OperatorAdd] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OperatorAdd] TO [db_dml]
GO
