/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderGetDetailSubHeader]

	@OffenderID	INT

AS

	SELECT distinct	ISNULL(o.FirstName + ' ', '') + 
			ISNULL(o.MiddleName + ' ', '') +
			ISNULL(o.LastName + ' ', '') AS 'OffenderName',
			ISNULL(o.HomeStreet1 + ' ', '') +
			ISNULL(o.HomeStreet2 + ' ', '') +
			ISNULL(o.HomeCity + ', ', '') +
			ISNULL(s.State + ' ', '') +
			ISNULL(o.HomePostalCode, '') AS 'Address',
			ISNULL(r.RiskLevel, '') AS 'RiskLevel',
			ISNULL(o.FBINumber, 0) AS 'FBINumber',
			ISNULL(o.CaseNumber,'') AS 'CaseNumber',
			ISNULL(t.TrackerNumber, '') AS 'TrackerPALNumber',
			ISNULL(d.[Name], '') AS 'DeviceName',
			ISNULL(ta.TrackerAssignmentTypeID, '') AS 'TrackerAssignmentTypeID'
	FROM	Offender o
	LEFT JOIN TrackerAssignment ta ON ta.OffenderID = o.OffenderID 
			AND ta.TrackerAssignmentID = (SELECT MAX(TrackerAssignmentID) FROM TrackerAssignment ta WHERE ta.OffenderID = o.OffenderID)
	LEFT JOIN State s ON o.HomeStateOrProvinceID = s.StateID
	LEFT JOIN Tracker t ON ta.TrackerID = t.TrackerID
	LEFT JOIN Gateway.dbo.Devices d ON t.TrackerID = d.DeviceID
	LEFT JOIN OffenderRiskLevel r ON o.RiskLevelID = r.RiskLevelID
	WHERE	o.OffenderID = @OffenderID
GO
GRANT EXECUTE ON [OffenderGetDetailSubHeader] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [OffenderGetDetailSubHeader] TO [db_object_def_viewers]
GO
