/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmGetNewestAlarms]
	
	@SO		INT,
	@OPR	INT,
	@DateAfter DateTime,
	@RecordCount INT OUTPUT

AS

set @RecordCount=(SELECT count(*) 
	from rprtAlarmMonitorCenterGrid 
	WHERE (
		(@SO<0)
		OR
		(SO=@SO)
		)
	AND 
		(
			(@OPR<0)
			OR
			(OPR=@OPR)
		) AND
	rprtAlarmMonitorCenterGrid.EventDisplayTime>@DateAfter AND
	rprtAlarmMonitorCenterGrid.AlarmAssignmentStatusID=1)

select @RecordCount
GO
GRANT VIEW DEFINITION ON [AlarmGetNewestAlarms] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [AlarmGetNewestAlarms] TO [db_dml]
GO
