/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [spCreateAlarmsReport] (
	-- Add the parameters for the stored procedure here
	@StartDate DateTime,
	@EndDate DateTime,
	-- Calling stored proc already adjusts for time zone on the range.  This param used
	-- only for data output.
	@TimeZoneOffsetOutput int
)
AS
BEGIN
	-- Subtract the time zone offset on the output.  DK 4-6-07
	SET @TimeZoneOffsetOutput = -@TimeZoneOffsetOutput

	DELETE FROM tempAlarmsReport
	INSERT INTO tempAlarmsReport
	-- Note: CreatedDate includes the time.  DK 4-4-07
	select a.AlarmID,a.AlarmGroupID,
		aa.AssignedDate as 'PickedUpDate',
		aaMax.AssignedDate as 'ClosedDate',
		a.CreatedDate,EventTypeID,
		(datediff(ss,a.CreatedDate,aa.AssignedDate)) as 'ASA(seconds)',
		(datediff(ss,aa.AssignedDate,aaMax.AssignedDate)) as 'AHA(seconds)',
		a.AlarmTypeID
	from Alarm a WITH(NOLOCK)
	LEFT JOIN AlarmAssignment aa WITH(NOLOCK) ON a.alarmId = aa.alarmid 
		AND aa.AssignedDate = (
			SELECT MIN(AssignedDate) FROM AlarmAssignment aad WITH(NOLOCK) WHERE aad.AlarmID = a.AlarmID
			AND aad.AlarmAssignmentStatusID=2
		)
	LEFT JOIN AlarmAssignment aaMax WITH(NOLOCK) ON a.alarmId = aaMax.alarmid 
		AND aaMax.AssignedDate = (
			SELECT MAX(AssignedDate) FROM AlarmAssignment aadMax WITH(NOLOCK) WHERE aadMax.AlarmID = a.AlarmID
			AND aadMax.AlarmAssignmentStatusID=4
		)
	-- WARNING: @StartDate comparison must be greater than or equal to include the start time in
	-- the data.  @EndDate comparison must be less than (not equal) to @EndDate and the passed
	-- in @EndDate be a "to" and not a "thru" value to correctly include all times at the end
	-- of the range in the data.
	--
	-- Note: The @EndDate passed in to the calling parent is a "thru", however.  DK 4-2-07
	WHERE (CreatedDate >= @StartDate) and (CreatedDate < @EndDate)
	-- AlarmGroupID is after AlarmID, because we DON'T want to eliminate alarms in the same group
	-- for this report.  DK 10-19-07
	GROUP BY a.AlarmID,a.AlarmGroupID,aa.AssignedDate,
		aaMax.AssignedDate,a.CreatedDate,a.AlarmTypeID,EventTypeID
	ORDER BY a.AlarmID

	DELETE FROM rprtAlarms
	INSERT INTO rprtAlarms 
	-- We subtract 3 ms from EndDate to show the "thru" and not "to" EndDate.  Original date passed in is "to".
	-- 3 ms is used because SQL rounds to the nearest 3 ms for dates.  DK 4-6-07
	select
		DATEADD(minute, @TimeZoneOffsetOutput, @StartDate) as 'StartDate',
		DATEADD(minute, @TimeZoneOffsetOutput, DATEADD(ms, -3, @EndDate)) as 'EndDate',

		exclv.total as 'excl_violate_total (36)',
		exclv.not_accepted as 'excl_violate_not_accepted (36)',
		exclv.not_completed as 'excl_violate_not_completed (36)',
		exclv.auto_completed as 'excl_violate_auto_completed (36)',
		exclv.asa as 'excl_violate_asa (36)',
		exclv.aha as 'excl_violate_aha (36)', 

		exclc.total as 'excl_compliance_total (37)',
		exclc.not_accepted as 'excl_compliance_not_accepted (37)',
		exclc.not_completed as 'excl_compliance_not_completed (37)',
		exclc.auto_completed as 'excl_compliance_auto_completed (37)',
		exclc.asa as 'excl_compliance_asa (37)',
		exclc.aha as 'excl_compliance_aha (37)',

		vproxv.total as 'victim_prox_violate_total (280)',
		vproxv.not_accepted as 'victim_prox_violate_not_accepted (280)',
		vproxv.not_completed as 'victim_prox_violate_not_completed (280)',
		vproxv.auto_completed as 'victim_prox_violate_auto_completed (280)',
		vproxv.asa as 'victim_prox_violate_asa (280)',
		vproxv.aha as 'victim_prox_violate_aha (280)',
		
		vproxa.total as 'victim_prox_alert_total (282)',
		vproxa.not_accepted as 'victim_prox_alert_not_accepted (282)',
		vproxa.not_completed as 'victim_prox_alert_not_completed (282)',
		vproxa.auto_completed as 'victim_prox_alert_auto_completed (282)',
		vproxa.asa as 'victim_prox_alert_asa (282)',
		vproxa.aha as 'victim_prox_alert_aha (282)',

		vproxc.total as 'victim_prox_compliance_total (281)',
		vproxc.not_accepted as 'victim_prox_compliance_not_accepted (281)',
		vproxc.not_completed as 'victim_prox_compliance_not_completed (281)',
		vproxc.auto_completed as 'victim_prox_compliance_auto_completed (281)',
		vproxc.asa as 'victim_prox_compliance_asa (281)',
		vproxc.aha as 'victim_prox_compliance_aha (281)', 

		inclv.total as 'incl_violate_total (44)',
		inclv.not_accepted as 'incl_violate_not_accepted (44)',
		inclv.not_completed as 'incl_violate_not_completed (44)',
		inclv.auto_completed as 'incl_violate_auto_completed (44)',
		inclv.asa as 'incl_violate_asa (44)',
		inclv.aha as 'incl_violate_aha (44)', 

		inclc.total as 'incl_compliance_total (45)',
		inclc.not_accepted as 'incl_compliance_not_accepted (45)',
		inclc.not_completed as 'incl_compliance_not_completed (45)',
		inclc.auto_completed as 'incl_compliance_auto_completed (45)',
		inclc.asa as 'incl_compliance_asa (45)',
		inclc.aha as 'incl_compliance_aha (45)',

		sdwnpend.total as 'shutdown_pend_total (26)',
		sdwnpend.not_accepted as 'shutdown_pend_not_accepted (26)',
		sdwnpend.not_completed as 'shutdown_pend_not_completed (26)',
		sdwnpend.auto_completed as 'shutdown_pend_auto_completed (26)',
		sdwnpend.asa as 'shutdown_pend_asa (26)',
		sdwnpend.aha as 'shutdown_pend_aha (26)',

		batc.total as 'batt_critical_total (25)',
		batc.not_accepted as 'batt_critical_not_accepted (25)',
		batc.not_completed as 'batt_critical_not_completed (25)',
		batc.auto_completed as 'batt_critical_auto_completed (25)',
		batc.asa as 'batt_critical_asa (25)',
		batc.aha as 'batt_critical_aha (25)',

		rmvd_extbatc.total as 'removed_extBatt_critical_total (18)',
		rmvd_extbatc.not_accepted as 'removed_extBatt_critical_not_accepted (18)',
		rmvd_extbatc.not_completed as 'removed_extBatt_critical_not_completed (18)',
		rmvd_extbatc.auto_completed as 'removed_extBatt_critical_auto_completed (18)',
		rmvd_extbatc.asa as 'removed_extBatt_critical_asa (18)',
		rmvd_extbatc.aha as 'removed_extBatt_critical_aha (18)',

		extbatt.total as 'extBatt_timeout_total (21)',
		extbatt.not_accepted as 'extBatt_timeout_not_accepted (21)',
		extbatt.not_completed as 'extBatt_timeout_not_completed (21)',
		extbatt.auto_completed as 'extBatt_timeout_auto_completed (21)',
		extbatt.asa as 'extBatt_timeout_asa (21)',
		extbatt.aha as 'extBatt_timeout_aha (21)',

		batctp2.total as 'Batt_Crit-TP2_total (210)',
		batctp2.not_accepted as 'Batt_Crit-TP2_not_accepted (210)',
		batctp2.not_completed as 'Batt_Crit-TP2_not_completed (210)',
		batctp2.auto_completed as 'Batt_Crit-TP2_auto_completed (210)',
		batctp2.asa as 'Batt_Crit-TP2_asa (210)',
		batctp2.aha as 'Batt_Crit-TP2_aha (210)',

		batcesctp2.total as 'Batt_Crit_Esc-TP2_total (211)',
		batcesctp2.not_accepted as 'Batt_Crit_Esc-TP2_not_accepted (211)',
		batcesctp2.not_completed as 'Batt_Crit_Esc-TP2_not_completed (211)',
		batcesctp2.auto_completed as 'Batt_Crit_Esc-TP2_auto_completed (211)',
		batcesctp2.asa as 'Batt_Crit_Esc-TP2_asa (211)',
		batcesctp2.aha as 'Batt_Crit_Esc-TP2_aha (211)',

		shutnowtp2.total as 'Shutdown_Now-TP2_total (212)',
		shutnowtp2.not_accepted as 'Shutdown Now-TP2_not_accepted (212)',
		shutnowtp2.not_completed as 'Shutdown Now-TP2_not_completed (212)',
		shutnowtp2.auto_completed as 'Shutdown Now-TP2_auto_completed (212)',
		shutnowtp2.asa as 'Shutdown Now-TP2_asa (212)',
		shutnowtp2.aha as 'Shutdown Now-TP2_aha (212)',

		ebmoved.total as 'eBeaconMoved_total (177)',
		ebmoved.not_accepted as 'eBeaconMoved_not_accepted (177)',
		ebmoved.not_completed as 'eBeaconMoved_not_completed (177)',
		ebmoved.auto_completed as 'eBeaconMoved_auto_completed (177)',
		ebmoved.asa as 'eBeaconMoved_asa (177)',
		ebmoved.aha as 'eBeaconMoved_aha (177)',

		ebopen.total as 'eBeaconOpened_total (178)',
		ebopen.not_accepted as 'eBeaconOpened_not_accepted (178)',
		ebopen.not_completed as 'eBeaconOpened_not_completed (178)',
		ebopen.auto_completed as 'eBeaconOpened_auto_completed (178)',
		ebopen.asa as 'eBeaconOpened_asa (178)',
		ebopen.aha as 'eBeaconOpened_aha (178)',

		ebsinvalid.total as 'eBeacon_Sequence_Invalid_total (179)',
		ebsinvalid.not_accepted as 'eBeacon_Sequence_Invalid_not_accepted (179)',
		ebsinvalid.not_completed as 'eBeacon_Sequence_Invalid_not_completed (179)',
		ebsinvalid.auto_completed as 'eBeacon_Sequence_Invalid_auto_completed (179)',
		ebsinvalid.asa as 'eBeacon_Sequence_Invalid_asa (179)',
		ebsinvalid.aha as 'eBeacon_Sequence_Invalid_aha (179)',	

		ebbattc.total as 'eBeaconBatCrit_total (182)',
		ebbattc.not_accepted as 'eBeaconBatCrit_not_accepted (182)',
		ebbattc.not_completed as 'eBeaconBatCrit_not_completed (182)',
		ebbattc.auto_completed as 'eBeaconBatCrit_auto_completed (182)',
		ebbattc.asa as 'eBeaconBatCrit_asa (182)',
		ebbattc.aha as 'eBeaconBatCrit_aha (182)',		

		eaviolate.total as 'eArrestViol_total (194)',
		eaviolate.not_accepted as 'eArrestViol_not_accepted (194)',
		eaviolate.not_completed as 'eArrestViol_not_completed (194)',
		eaviolate.auto_completed as 'eArrestViol_auto_completed (194)',
		eaviolate.asa as 'eArrestViol_asa (194)',
		eaviolate.aha as 'eArrestViol_aha (194)',	

		eacomply.total as 'eArrestComply_total (195)',
		eacomply.not_accepted as 'eArrestComply_not_accepted (195)',
		eacomply.not_completed as 'eArrestComply_not_completed (195)',
		eacomply.auto_completed as 'eArrestComply_auto_completed (195)',
		eacomply.asa as 'eArrestComply_asa (195)',
		eacomply.aha as 'eArrestComply_aha (195)',	

		strpopt.total as 'strap_optical_total (65)',
		strpopt.not_accepted as 'strap_optical_not_accepted (65)',
		strpopt.not_completed as 'strap_optical_not_completed (65)',
		strpopt.auto_completed as 'strap_optical_auto_completed (65)',
		strpopt.asa as 'strap_optical_asa (65)',
		strpopt.aha as 'strap_optical_aha (65)',

		neventt.total as 'noevent_timeout_total (256)',
		neventt.not_accepted as 'noevent_timeout_not_accepted (256)',
		neventt.not_completed as 'noevent_timeout_not_completed (256)',
		neventt.auto_completed as 'noevent_timeout_auto_completed (256)',
		neventt.asa as 'noevent_timeout_asa (256)',
		neventt.aha as 'noevent_timeout_aha (256)',

		neventtesc.total as 'noevent_timeout_escalate_total (258)',
		neventtesc.not_accepted as 'noevent_timeout_escalate_not_accepted (258)',
		neventtesc.not_completed as 'noevent_timeout_escalate_not_completed (258)',
		neventtesc.auto_completed as 'noevent_timeout_escalate_auto_completed (258)',
		neventtesc.asa as 'noevent_timeout_escalate_asa (258)',
		neventtesc.aha as 'noevent_timeout_escalate_aha (258)',

		commr.total as 'comm_resumed_total (257)',
		commr.not_accepted as 'comm_resumed_not_accepted (257)',
		commr.not_completed as 'comm_resumed_not_completed (257)',
		commr.auto_completed as 'comm_resumed_auto_completed (257)',
		commr.asa as 'comm_resumed_asa (257)',
		commr.aha as 'comm_resumed_aha (257)',

		rmvd_sdwnpend.total as 'removed_shutdown_pend_total (5)',
		rmvd_sdwnpend.not_accepted as 'removed_shutdown_pend_not_accepted (5)',
		rmvd_sdwnpend.not_completed as 'removed_shutdown_pend_not_completed (5)',
		rmvd_sdwnpend.auto_completed as 'removed_shutdown_pend_auto_completed (5)',
		rmvd_sdwnpend.asa as 'removed_shutdown_pend_asa (5)',
		rmvd_sdwnpend.aha as 'removed_shutdown_pend_aha (5)',

		pwrd.total as 'power_down_total (3)',
		pwrd.not_accepted as 'power_down_not_accepted (3)',
		pwrd.not_completed as 'power_down_not_completed (3)',
		pwrd.auto_completed as 'power_down_auto_completed (3)',
		pwrd.asa as 'power_down_asa (3)',
		pwrd.aha as 'power_down_aha (3)',

		pwru.total as 'power_up_total (1)',
		pwru.not_accepted as 'power_up_not_accepted (1)',
		pwru.not_completed as 'power_up_not_completed (1)',
		pwru.auto_completed as 'power_up_auto_completed (1)',
		pwru.asa as 'power_up_asa (1)',
		pwru.aha as 'power_up_aha (1)',

		

		misc.total as 'misc_total',
		misc.not_accepted as 'misc_not_accepted',
		misc.not_completed as 'misc_not_completed',
		misc.auto_completed as 'misc_auto_completed',
		misc.asa as 'misc_asa',
		misc.aha as 'misc_aha',

		dbo.fnASAPReportsMiscAlarmTypesAlarms() as 'misc_alarms_types',

		totl.total as 'total',
		totl.not_accepted as 'total_not_accepted',
		totl.not_completed as 'total_not_completed',
		totl.auto_completed as 'total_auto_completed',
		totl.asa as 'total_asa',
		totl.aha as 'total_aha'

	from 
		fnAlarmRereport(36) as exclv,
		fnAlarmRereport(37) as exclc,
		fnAlarmRereport(280) as vproxv,
		fnAlarmRereport(282) as vproxa,
		fnAlarmRereport(281) as vproxc,
		fnAlarmRereport(44) as inclv,
		fnAlarmRereport(45) as inclc,
		fnAlarmRereport(26) as sdwnpend,
		fnAlarmRereport(25) as batc,
		fnAlarmRereport(18) as rmvd_extbatc,
		fnAlarmRereport(21) as extbatt,
		fnAlarmRereport(210) as batctp2,
      fnAlarmRereport(211) as batcesctp2,
		fnAlarmRereport(212) as shutnowtp2,
		fnAlarmRereport(177) as ebmoved,
		fnAlarmRereport(178) as ebopen,
		fnAlarmRereport(179) as ebsinvalid,
		fnAlarmRereport(182) as ebbattc,
		fnAlarmRereport(194) as eaviolate,
		fnAlarmRereport(195) as eacomply,
		fnAlarmRereport(65) as strpopt,
		fnAlarmRereport(256) as neventt,
		fnAlarmRereport(258) as neventtesc,
		fnAlarmRereport(257) as commr,
		fnAlarmRereport(5) as rmvd_sdwnpend,
		fnAlarmRereport(3) as pwrd,
		fnAlarmRereport(1) as pwru,
		fnAlarmRereport(-1) as misc,
		fnAlarmRereport(0) as totl

	SELECT * FROM rprtAlarms WITH(NOLOCK)
	
	-- Clean up
	DELETE FROM tempAlarmsReport

	-- To be safe on streaming, don't delete table data here, since its data is returned.  DK 8-2-07
	-- DELETE FROM rprtAlarms
END


GO
GRANT EXECUTE ON [spCreateAlarmsReport] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [spCreateAlarmsReport] TO [db_object_def_viewers]
GO
