/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderGetArchivedBySearch]

	@FirstName	NVARCHAR(50),
	@LastName	NVARCHAR(50),
	@AgencyID	INT,
	@OfficerID	INT,
	@RoleID		INT,
	@OffenderID INT = -1,
	@UserID INT
	

AS
	BEGIN
	SELECT     o.OffenderID, ISNULL(o.LastName, '') + ', ' + ISNULL(o.FirstName, '') + ISNULL(' ' + o.MiddleName, '') AS 'OffenderName', ISNULL(o.HomeStreet1, '') 
                      AS 'HomeAddress', a.Agency, o.ModifiedDate AS ArchivedDate, o.OffenderID AS OffenderID, ISNULL(Officer.FirstName, '') + ', ' + ISNULL(Officer.MiddleName, 
                      '') + ISNULL(' ' + Officer.LastName, '') AS 'OfficerName', a.AgencyId, Officer.OfficerId
	FROM         Offender AS o INNER JOIN
                      Agency AS a ON a.AgencyID = o.AgencyID  INNER JOIN
                      Offender_Officer ON o.OffenderID = Offender_Officer.OffenderID INNER JOIN
                      Officer ON Offender_Officer.OfficerID = Officer.OfficerID
	WHERE	o.Deleted = 1 AND
			(
			  (
			  	@OffenderID<0 and
				(( @AgencyID = 0)or(o.AgencyID = @AgencyID)) AND
				(o.FirstName LIKE '%' + @FirstName + '%') AND
				(o.LastName LIKE '%' + @LastName + '%')
			  )
			  or
			  (
				  o.offenderId= @OffenderID
			  )
			)	
	ORDER BY o.LastName, o.FirstName
	END
GO
GRANT EXECUTE ON [OffenderGetArchivedBySearch] TO [db_dml]
GO
