/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmProtocolSetAdd]

	@AlarmProtocolSetID		INT OUTPUT,
	@AlarmProtocolSetTypeID	INT,
	@AlarmProtocolSetName	NVARCHAR(50),
	@AgencyID				INT,
	@OfficerID				INT,
	@OffenderID				INT,
	@CreatedByID			INT

AS

	INSERT INTO AlarmProtocolSet
	(AlarmProtocolSetName, AlarmProtocolSetTypeID,AgencyID, OfficerID, OffenderID, 
	 CreatedByID)
	VALUES
	(@AlarmProtocolSetName, @AlarmProtocolSetTypeID, @AgencyID, @OfficerID, @OffenderID, 
	 @CreatedByID)

	SET @AlarmProtocolSetID = @@IDENTITY
GO
GRANT VIEW DEFINITION ON [AlarmProtocolSetAdd] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [AlarmProtocolSetAdd] TO [db_dml]
GO
