/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportingIntervalDefaultCostAdd] @ReportingIntervalID INT, @DefaultCost FLOAT, @BillingServiceOptionID INT
AS
--Adds new record to ReportingIntervalDefaultCost table.
SET NOCOUNT ON;
--Check for outstanding transactions
IF @@TRANCOUNT > 0
	BEGIN
		ROLLBACK TRANSACTION
	END;

BEGIN TRANSACTION;
BEGIN TRY
	INSERT INTO dbo.ReportingIntervaldefaultCost(ReportingIntervalID, DefaultCost,BillingServiceOptionID)
	VALUES(@ReportingIntervalID, @DefaultCost, @BillingServiceOptionID);
END TRY
BEGIN CATCH
	--Catch and return error.
    SELECT 
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_SEVERITY() AS ErrorSeverity,
        ERROR_STATE() as ErrorState,
        ERROR_PROCEDURE() as ErrorProcedure,
        ERROR_LINE() as ErrorLine,
        ERROR_MESSAGE() as ErrorMessage;
	--Rollback outstanding transactions.
	IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION
		END;
END CATCH;

IF @@TRANCOUNT > 0
	BEGIN
		COMMIT TRANSACTION
	END;

GO
GRANT EXECUTE ON [ReportingIntervalDefaultCostAdd] TO [db_dml]
GO
