/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmProtocolSetIsNotAssigned]
	@AlarmProtocolSetID int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		COUNT(*) AS isOwner		
	FROM    dbo.AlarmProtocolSet 
	WHERE   AlarmProtocolSetID = @AlarmProtocolSetID AND
	AlarmProtocolSetID NOT IN 
	(	SELECT distinct AlarmProtocolSetID
		FROM dbo.Offender_AlarmProtocolSet
		WHERE deleted=0
	)
END


GO
GRANT VIEW DEFINITION ON [AlarmProtocolSetIsNotAssigned] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [AlarmProtocolSetIsNotAssigned] TO [db_dml]
GO
