/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:26 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ActiveDeviceDetail]
AS
Select
dp5.PropertyValue AS 'Gateway Serial Number'
,d.deviceid
,ag.Agency
,Gateway.dbo.HexToBigInt(dp8.propertyvalue) AS 'Firmware'
From Gateway.dbo.devices d
LEFt JOIN Gateway.dbo.DeviceProperties dp8 ON d.DeviceID = dp8.DeviceID AND dp8.PropertyID = '8016'
Join OffendertrackerActivation ota ON ota.trackerid = d.deviceid and ota.deactivatedate is NULL
LEFT JOIN Gateway.dbo.DeviceProperties dp5 ON d.DeviceID = dp5.DeviceID AND dp5.PropertyID = '8012'
LEFt JOIN Offender o on o.Offenderid = ota.offenderid
JOIN Agency ag on ag.agencyid = o.agencyid

GO
GRANT EXECUTE ON [ActiveDeviceDetail] TO [db_dml]
GO
