/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmProtocolActionRetryGetByRoleID]

	@RoleID	INT

AS

	SELECT	AlarmProtocolActionRetryID, AlarmProtocolActionRetry
	FROM	AlarmProtocolActionRetry
	WHERE	RoleID <= @RoleID

GO
GRANT EXECUTE ON [AlarmProtocolActionRetryGetByRoleID] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [AlarmProtocolActionRetryGetByRoleID] TO [db_object_def_viewers]
GO
