/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoScheduleDelete]
	@GeoScheduleId					uniqueidentifier
	
AS
SET NOCOUNT ON;
BEGIN
	BEGIN TRAN
		DELETE FROM GeoSchedule
		WHERE Id = @GeoScheduleId
	COMMIT TRAN
END
GO
GRANT EXECUTE ON [GeoScheduleDelete] TO [db_dml]
GO
