/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mAgencyGetByID]

	@AgencyID	INT,
	@GetDeleted BIT = 0
AS
BEGIN
	SELECT	AgencyID, 
			ISNULL(Agency, '') AS 'Agency',
			ISNULL(StreetLine1, '') AS 'StreetLine1', 
			ISNULL(StreetLine2, '') AS 'StreetLine2',
			ISNULL(City, '') AS 'City',
			ISNULL(StateID, 0) AS 'StateID', 
			ISNULL(PostalCode, '') AS 'PostalCode',
			ISNULL(CountryID, 0) AS 'CountryID',
			ISNULL(Phone, '') AS 'Phone',
			ISNULL(Fax, '') AS 'Fax',
			ISNULL(URL, '') AS 'URL',
			ISNULL(EmailAddress, '') AS 'EmailAddress',
			ISNULL(OnCallPhone, '') AS 'OnCallPhone',
			ISNULL(OnCallPager, '') AS 'OnCallPager',
			ISNULL(OnCallEmail, '') AS 'OnCallEmail',
			ISNULL(TimeZoneID, 0) AS 'TimeZoneID',
			ISNULL(DaylightSavings, 1) AS 'DaylightSavings', --Default to true
			ISNULL(DistributorID, 0) AS 'DistributorID',
			ISNULL(SMSAddress, '') AS 'SMSAddress', --Default to true
			ISNULL(SMSGatewayID, 0) AS 'SMSGateway',
			CreatedDate,
			CreatedByID,
			ModifiedDate,
			ModifiedByID,
			Deleted
	FROM	Agency
	WHERE	AgencyID = @AgencyID AND (@GetDeleted = 1 OR Deleted = 0)
END


GO
GRANT EXECUTE ON [mAgencyGetByID] TO [db_dml]
GO
