/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TrackerAssignmentGetCurrentID] 
	@OffenderID int = 0,
	@TrackerID int = 0
AS
BEGIN
	SET NOCOUNT ON;

DECLARE @TrackerAssignmentID int

	SELECT 
		@TrackerAssignmentID = [TrackerAssignmentID]
	FROM 
		[TrackerAssignment]
	WHERE 
		TrackerAssignmentID = 
		(SELECT 
			MAX(TrackerAssignmentID) 
		 FROM 
			TrackerAssignment 
		 WHERE 
			(@OffenderID > 0 AND OffenderID = @OffenderID)
			OR
			(@TrackerID > 0 AND TrackerID = @TrackerID)
		)
	RETURN 
		@TrackerAssignmentID

END
GO
GRANT VIEW DEFINITION ON [TrackerAssignmentGetCurrentID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [TrackerAssignmentGetCurrentID] TO [db_dml]
GO
