/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmProtocolEventGetByAlarmProtocolSetID]

	@AlarmProtocolSetID	INT

AS
        SELECT  ape.AlarmProtocolEventID,
		                        et.longname AS 'AlarmName',
		                        et.AbbrevEventType AS AbbrAlarmName,
		                        et.EventDescription AS 'AlarmDescription',
		                        (SELECT COUNT(*) FROM AlarmProtocolAction
		                         WHERE  AlarmProtocolSetID = @AlarmProtocolSetID AND
		                                        AlarmProtocolEventID = ape.AlarmProtocolEventID AND
		                                        Deleted = 0) AS 'AlarmProtocolActionRecordCount'
		        FROM    AlarmProtocolEvent ape        
		        INNER JOIN EventType et ON ape.GatewayEventID = et.EventTypeID
		WHERE ape.Visible = 1
        ORDER BY ape.DisplayOrder

GO
GRANT EXECUTE ON [AlarmProtocolEventGetByAlarmProtocolSetID] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [AlarmProtocolEventGetByAlarmProtocolSetID] TO [db_object_def_viewers]
GO
