/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mTrackerRmasAll]
AS
BEGIN

SET NOCOUNT ON;

SELECT
	rma.[RmaID],
	rma.[TrackerID],
	rma.[CreatedDate],
	rma.[CreatedByID],
	rma.[RemovedDate],
	rma.[RemovedByID],
	rma.[TrackerRmaReasonID],
	rma.[ReasonText]
FROM 
	[TrackerRma] rma 
	INNER JOIN Tracker t ON t.RmaID = rma.RmaID AND t.Deleted = 0

END



GO
GRANT EXECUTE ON [mTrackerRmasAll] TO [db_dml]
GO
