/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmGetOffenderIDByTrackerID]

	@TrackerID int

AS

	SELECT	OffenderID
	FROM	TrackerAssignment
	WHERE	TrackerID = @TrackerID AND
			TrackerAssignmentTypeID = 1
			order by assignmentdate desc




GO
GRANT EXECUTE ON [AlarmGetOffenderIDByTrackerID] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [AlarmGetOffenderIDByTrackerID] TO [db_object_def_viewers]
GO
