/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderAcquaintanceUpdate]
	@iAcquaintanceID int,
	@iOffenderID int,
	@iAcquaintSalutationID int = null,
	@sAcquaintFirstName nvarchar(50) = null,
	@sAcquaintMiddleName nvarchar(50) = null,
	@sAcquaintLastName nvarchar(50) = null,
	@iAcquaintSuffixID int = null,
	@sAcquaintRelationship nvarchar(100) = null,
	@sAcquaintAlias1 nvarchar(50) = null,
	@sAcquaintAlias2 nvarchar(50) = null,
	@sAcquaintStreet1 nvarchar(50) = null,
	@sAcquaintStreet2 nvarchar(50) = null,
	@sAcquaintCity nvarchar(50) = null,
	@iAcquaintStateID int = null,
	@sAcquaintPostalCode nvarchar(25) = null,
	@iAcquaintCountryID int = null,
	@iAcquaintPhone1TypeID int = null,
	@iAcquaintPhone2TypeID int = null,
	@sAcquaintPhone1 nvarchar(25) = null,
	@sAcquaintPhone2 nvarchar(25) = null,
	@sAcquaintProfileNotes nvarchar(2000) = null

AS
BEGIN

	SET NOCOUNT ON;

	UPDATE OffenderAcquaintance SET
		OffenderID = @iOffenderID,
		SalutationID = @iAcquaintSalutationID,
		FirstName = @sAcquaintFirstName,
		MiddleName = @sAcquaintMiddleName,
		LastName = @sAcquaintLastName,
		SuffixID = @iAcquaintSuffixID,
		Relationship = @sAcquaintRelationship,
		Alias1 = @sAcquaintAlias1,
		Alias2 = @sAcquaintAlias2,
		Street1 = @sAcquaintStreet1,
		Street2 = @sAcquaintStreet2,
		City = @sAcquaintCity,
		StateID = @iAcquaintStateID,
		PostalCode = @sAcquaintPostalCode,
		CountryID = @iAcquaintCountryID,
		PhoneType1ID = @iAcquaintPhone1TypeID,
		PhoneType2ID = @iAcquaintPhone2TypeID,
		Phone1 = @sAcquaintPhone1,
		Phone2 = @sAcquaintPhone2,
		ProfileNotes = @sAcquaintProfileNotes
	WHERE OffenderAcquaintanceID = @iAcquaintanceID

END


GO
GRANT VIEW DEFINITION ON [OffenderAcquaintanceUpdate] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OffenderAcquaintanceUpdate] TO [db_dml]
GO
