/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [EventMonitor]

AS
BEGIN
	SET NOCOUNT ON;

	SELECT Top 1 EventPrimaryID, ReceivedTime
	FROM rprtEventsBucket1
	ORDER BY ReceivedTime DESC

END

GO
GRANT EXECUTE ON [EventMonitor] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [EventMonitor] TO [db_object_def_viewers]
GO
