/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [spOffenderGetBysearch]

@Agencyid int = -1,
@FirstName varchar(32) =NULL ,
@LastName varchar(32) = NULL
AS
SELECT  

        o.Offenderid
        ,a.agency
        ,o.FirstName+' '+o.LastName AS 'OffenderName'
From Offender o
JOIN Agency a ON a.agencyid = o.agencyid
Where (o.FirstName LIKE '%' + ISNULL(@FirstName,'') + '%') AND
		(o.LastName Like '%' + ISNULL(@LastName,'') + '%') And (o.agencyid = @agencyid
OR @agencyid = -1)
       


GO
GRANT EXECUTE ON [spOffenderGetBysearch] TO [db_dml]
GO
