/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [RoleGetByIDForEdit]

@RoleID int

AS

SET NOCOUNT ON

SELECT DISTINCT 
CASE
	WHEN EXISTS(	
			SELECT r2.ResourceID 
			FROM RoleResourceMap r2
			WHERE RoleID = @RoleID 
			AND r2.ResourceID = r1.ResourceID) THEN 1
	ELSE 0
END
AS HasAccess,
r1.ResourceID,
r3.Resource
FROM RoleResourceMap r1
INNER JOIN Resource r3 ON r3.ResourceID = r1.ResourceID
ORDER BY r1.ResourceID
GO
GRANT VIEW DEFINITION ON [RoleGetByIDForEdit] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [RoleGetByIDForEdit] TO [db_dml]
GO
