/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [BeaconGetAllDetailsByOffenderID] (
	 @OffenderID INT
)
AS
BEGIN
  SET NOCOUNT ON;

    SELECT Beacon.ID as BeaconID, 
           Beacon.Identifier, 
           Beacon.BeaconName AS BeaconName,
	         a.ID,
	         a.Street1,
	         a.Street2,
	         a.ZipCode,
	         a.City,
	         a.StateID,
	         dbo.GPSLocation.Longitude,
	         dbo.GPSLocation.Latitude,			  
	         ERule.ID AS RuleID,
	         ERule.Name AS RuleName,
	         r.UploadStatusID, 	
           r.FileID,
	         Schedule.ID as ScheduleID,
	         Schedule.StartDateTime, 
	         Schedule.EndDateTime,
	         Schedule.AlwaysOn, 
   	       ScheduleRepeatedDay.DayID
    FROM dbo.BeaconOffender  
      INNER JOIN dbo.Beacon ON BeaconOffender.BeaconID = Beacon.ID 
      INNER JOIN dbo.ERule ON Beacon.ID = ERule.BeaconID 
      LEFT OUTER JOIN dbo.[Rule] r ON ERule.RuleID = r.ID 
      INNER JOIN dbo.[Address] a ON Beacon.AddressID = a.ID 
      INNER JOIN dbo.GPSLocation ON a.ID = dbo.GPSLocation.ID 
      LEFT OUTER JOIN dbo.Schedule ON ERule.ID = Schedule.RuleID 
      LEFT OUTER JOIN dbo.ScheduleRepeatedDay ON Schedule.ID = ScheduleRepeatedDay.ScheduleID    
    WHERE BeaconOffender.OffenderID  = @OffenderID 
      AND Beacon.Deleted = 0
END

GO
GRANT EXECUTE ON [BeaconGetAllDetailsByOffenderID] TO [db_dml]
GO
