/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportGetByReportID]
			@ReportID	INT
AS
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT		ReportName,
			FieldSet,
			FilterSet
FROM        Reports
			where reportID=@ReportID 
			
GO
GRANT VIEW DEFINITION ON [ReportGetByReportID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [ReportGetByReportID] TO [db_dml]
GO
