/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OfficerHasOneOffenderAssigned]
@OfficerID int

AS
BEGIN

SET NOCOUNT ON;

IF((Select count(*) from (SELECT DISTINCT ofcr.OfficerID,o.OffenderID
FROM         Officer AS ofcr INNER JOIN
                      Offender_Officer AS oo ON ofcr.OfficerID = oo.OfficerID INNER JOIN
                      Offender AS o ON oo.OffenderID = o.OffenderID INNER JOIN
                      Agency ON ofcr.AgencyID = Agency.AgencyID
WHERE     (o.Deleted = 0) AND (ofcr.Deleted = 0) and ofcr.OfficerID = @OfficerID) as temp) = 1)
BEGIN
select OffenderID from Offender_Officer where OfficerID = @OfficerID
END
ELSE
select 0
END
GO
GRANT EXECUTE ON [OfficerHasOneOffenderAssigned] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [OfficerHasOneOffenderAssigned] TO [db_object_def_viewers]
GO
