/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderCreateRecord]
	@CreatedByID int,
	@AgencyID int,
	@OffenderID int OUTPUT

AS
BEGIN
SET NOCOUNT ON;
	
INSERT INTO [dbo].[Offender] (
	[CreatedDate],
	[CreatedByID],
	[AgencyID],
	[Deleted]
) 
VALUES 
(
	GETDATE(),
	@CreatedByID,
	@AgencyID,
	0
)

SET @OffenderID = SCOPE_IDENTITY()

END



GO
GRANT EXECUTE ON [OffenderCreateRecord] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [OffenderCreateRecord] TO [db_object_def_viewers]
GO
