/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mOffenderByOffenderID]

	@OffenderID bigint

AS
	 select g.OffenderID, g.AgencyID, g.FirstName, g.LastName, g.RiskLevelID , oo.OfficerID , g.OffenderPay
	 from Offender  g 
 	left join offender_officer oo on oo.offenderid = g.Offenderid  
	where g.OffenderID = @OffenderID
	
GO
GRANT EXECUTE ON [mOffenderByOffenderID] TO [db_dml]
GO
