/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmGetMonitorCenterAlarmNote]
@AlarmID int
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	SELECT Note,CreatedByID,CreatedDate
	FROM AlarmNote 
	WHERE AlarmID = @AlarmID

END
GO
GRANT VIEW DEFINITION ON [AlarmGetMonitorCenterAlarmNote] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [AlarmGetMonitorCenterAlarmNote] TO [db_dml]
GO
