/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
/* /////////////////////////////////////////////////////////// --
-- // FileName:     EventTypesGetAllEventGroupsDetails.sql	// -- 
-- // Created On:	unknown                                 // --
-- // Created By:   J.Barrus                                // --
-- // Task #:		SA_                                     // --
-- // Purpose:      Get EventType Details for TrackerMAP    // --
-- //                                                       // --
-- // Modified By:  R.Cole - 11/17/2009                     // --
-- //               Removed the SELECT *                    // --
-- /////////////////////////////////////////////////////////// */

CREATE PROCEDURE [EventTypesGetAllEventGroupsDetails] (
    @SO int, 
    @OPR int
)

AS

SELECT	
    EventTypeGroup.EventTypeGroupID,
    EventTypeGroup.EventTypeGroupName
FROM EventType 
  INNER JOIN  EventTypeGroup ON EventType.EventTypeGroupID = EventTypeGroup.EventTypeGroupID
WHERE VISIBLE = 1 
  AND ( (@SO < 0) OR (EventType.SO = @SO) )
  AND ( (@OPR < 0) OR (EventType.OPR = @OPR) )
GROUP BY 
    EventTypeGroup.EventTypeGroupID, 
    EventTypeGroup.EventTypeGroupName

GO
GRANT EXECUTE ON [EventTypesGetAllEventGroupsDetails] TO [db_dml]
GO
