/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [spICCIDDetail]
@afterdate Datetime

AS
SELECT
d.deviceid
,dp.propertyvalue
,(CASE When d.lasteventtime != 0 THEN trackerpal.dbo.convertlongtodate(d.LastEventTime)
ELSE 0 END) AS 'Lastevent'
INTO #tmpICCID
From gateway.dbo.devices d
JOIN Gateway.dbo.deviceproperties dp ON dp.deviceid = d.deviceid AND dp.Propertyid = '8204'


SELECT
       
          dp4.PropertyValue AS 'ICCID'
         ,gateway.dbo.HexToBigInt(dp9.propertyvalue) As 'Reporting Interval'
         ,dp5.PropertyValue AS 'Serial #'
			,nop.[name] AS 'Sim Provider'
			,a.SFDCAccount AS 'SFDCACCT#'
         ,(CASE When t1.deleted = 0 THEN a.agency 
           ELSE '' END)AS 'Assigned Agency'
         ,(Case When t1.deleted = 0 THEN st.abbreviation
           ELSE '' END) AS 'Statecode'
			,(CASE WHEN ota.deactivatedate IS NULL AND ota.trackeractivationid IS NOT NULL THEN o.FirstName+' '+o.LastName
           ELSE ''END)AS 'CurrentActiveOffender'
         ,(CASE WHEN ota.deactivatedate IS NULL AND ota.trackeractivationid IS NOT NULL THEN ofi.FirstName+' '+ofi.LastName
           ELSE ''END)AS 'CurrentAssignedOfficer'
          ,d.LastEvent AS 'Last'




		  

FROM (SELECT propertyvalue, MAX(lastevent) As maxiccid From #tmpICCID Group BY propertyvalue) d2
JOIN #tmpICCID d ON d.lastevent = d2.maxiccid
LEFT JOIN (SELECT TrackerID, Max(TrackerUniqueID) As uniqueid FROM Tracker WITH (NOLOCK) Group BY Trackerid) AS t ON t.trackerid = d.deviceid
LEFT JOIN tracker t1 on t.uniqueid = t1.trackeruniqueid
LEFt JOIN Offendertrackeractivation ota ON ota.trackerid = t1.trackerid AND ota.deactivatedate is NULL
LEFT JOIN Offender o ON o.Offenderid = ota.Offenderid
LEFt JOIN Officer ofi ON ofi.Officerid = ota.Officerid
LEFT JOIN Agency a ON a.agencyid = t1.agencyid
LEFT JOIN State st ON a.stateid = st.stateid
JOIN Gateway.dbo.DeviceProperties dp3 ON d.DeviceID = dp3.DeviceID AND dp3.PropertyID = '8202'
JOIN Gateway.dbo.DeviceProperties dp4 ON d.DeviceID = dp4.DeviceID AND dp4.PropertyID = '8204'
LEFT JOIN Gateway.dbo.DeviceProperties dp5 ON d.DeviceID = dp5.DeviceID AND dp5.PropertyID = '8012'
JOIN Gateway.dbo.deviceproperties dp9 ON dp9.deviceid = d.deviceid AND dp9.propertyid = '8020'
LEFT JOIN Gateway.dbo.NetworkOperators nop ON nop.MCC+nop.MNC = LEFT(dp3.Propertyvalue,6)
WHERE d.lastevent >= @AfterDate
Order BY 'ICCID'
Drop Table #tmpICCID








GO
GRANT EXECUTE ON [spICCIDDetail] TO [db_dml]
GO
