/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderUpdateVehicleData]
	@iOffenderID int,
	@sVehicleLicensePlate nvarchar(50) = null,
	@sVehicleMake nvarchar(50) = null,
	@sVehicleModel nvarchar(50) = null,
	@iVehicleYear int = null,
	@sVehicleColor nvarchar(50) = null,
	@sVehicleLocationStreet1 nvarchar(50) = null,
	@sVehicleLocationStreet2 nvarchar(50) = null,
	@sVehicleLocationCity nvarchar(50) = null,
	@iVehicleLocationStateID int = null,
	@sVehicleLocationPostalCode nvarchar(50) = null,
	@iVehicleLocationCountryID int = null,
	@sVehicleInsuranceCo nvarchar(50) = null,
	@sVehicleInsurancePolicyNumber nvarchar(50) = null,
	@sVehicleInsuranceAgent nvarchar(50) = null,
	@sVehicleInsurancePrimaryPhone nvarchar(50) = null,
	@sVehicleInsuranceFax nvarchar(50) = null,
	@sVehicleRegisteredOwner nvarchar(50) = null,
	@sVehicleNumber nvarchar(50) = null,
	@sVehiclePrimaryPhone nvarchar(50) = null,
	@sVehicleNotes nvarchar(2000) = null

AS
BEGIN
	SET NOCOUNT ON;

UPDATE Offender SET
	
	LicensePlate = @sVehicleLicensePlate,
	VehicleManufacturer = @sVehicleMake,
	VehicleModel = @sVehicleModel,
	VehicleYear = @iVehicleYear,
	VehicleColor = @sVehicleColor,
	VehicleLocationStreet1 = @sVehicleLocationStreet1,
	VehicleLocationStreet2 = @sVehicleLocationStreet2,
	VehicleLocationCity = @sVehicleLocationCity,
	VehicleLocationStateID = @iVehicleLocationStateID,
	VehicleLocationPostalCode = @sVehicleLocationPostalCode,
	VehicleLocationCountryID = @iVehicleLocationCountryID,
	VehicleInsuranceCompanyName = @sVehicleInsuranceCo,
	VehicleInsurancePolicyNumber = @sVehicleInsurancePolicyNumber,
	VehicleInsuranceAgent = @sVehicleInsuranceAgent,
	VehicleInsurancePhone1 = @sVehicleInsurancePrimaryPhone,
	VehicleInsuranceFax = @sVehicleInsuranceFax,
	VehicleRegisteredOwner = @sVehicleRegisteredOwner,
	VIN = @sVehicleNumber,
	VehicleRegisteredOwnerPhone = @sVehiclePrimaryPhone,
	VehicleSpecialMarkings = @sVehicleNotes
	
WHERE OffenderID = @iOffenderID

END

GO
GRANT VIEW DEFINITION ON [OffenderUpdateVehicleData] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OffenderUpdateVehicleData] TO [db_dml]
GO
