/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [UpdateEventsBucket2]
	@RowCount int = 1000
AS

DECLARE @StartDate datetime

IF @RowCount > 0 BEGIN
	SELECT @StartDate = (SELECT MIN(EventDateTime) 
	FROM rprtEventsBucket2 
	WHERE EventDateTime IN (SELECT TOP (@RowCount) EventDateTime FROM rprtEventsBucket2 WHERE Address IS NULL ORDER BY EventDateTime DESC))
END ELSE BEGIN
	SELECT @StartDate = (SELECT MIN(EventDateTime) FROM rprtEventsBucket2)
END

UPDATE rprtEventsBucket2 
	SET Address = sac.streetAddress
	FROM rprtEventsBucket2 eb1
		INNER JOIN StreetAddressCache sac ON 
			sac.latitude = ROUND(eb1.Latitude, 5)
			AND sac.longitude = ROUND(eb1.Longitude, 5)
			AND eb1.Address IS NULL
			AND sac.streetAddress IS NOT NULL
	WHERE EventDateTime >= @StartDate




GO
GRANT EXECUTE ON [UpdateEventsBucket2] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [UpdateEventsBucket2] TO [db_object_def_viewers]
GO
