/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [StaticCrimeSceneGetAll]
AS
BEGIN
	
	SELECT     cs.ID, cs.[DateTime], cs.CaseNumber, cs.Notes, cs.CreatedByID, csl.Street, csl.City, csl.StateID, csl.Zip, csl.Latitude, csl.Longitude, csc.TimeBefore, 
                      csc.TimeAfter, csc.Proximity, csc.CreatorID, csc.Completed, csl.ID AS LocationID, csc.ID AS CorrelationID, csc.IsMile
FROM         CrimeScene AS cs INNER JOIN
                      CrimeSceneLocation AS csl ON cs.ID = csl.CrimeSceneID INNER JOIN
                      CrimeSceneCorrelation AS csc ON cs.ID = csc.CrimeSceneID
END
GO
GRANT EXECUTE ON [StaticCrimeSceneGetAll] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [StaticCrimeSceneGetAll] TO [db_object_def_viewers]
GO
