/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TrackerAssignmentGetCurrentTrackerID]
	@TrackerID int OUTPUT,
	@OffenderID int = 0
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		@TrackerID = [TrackerID]
	FROM 
		[TrackerAssignment]
	WHERE 
		TrackerAssignmentID = (SELECT MAX(TrackerAssignmentID) FROM TrackerAssignment WHERE OffenderID = @OffenderID)
		AND OffenderID = @OffenderID
		AND TrackerAssignmentTypeID = 1
END
GO
GRANT VIEW DEFINITION ON [TrackerAssignmentGetCurrentTrackerID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [TrackerAssignmentGetCurrentTrackerID] TO [db_dml]
GO
