/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmProtocolActionGetSettings]

	@AlarmProtocolActionID INT,  
 @AlarmID INT,  
 @OffenderID INT  
  
AS  
  
 SELECT et.longname AS 'AlarmName',  
     offend.LastName + ' ' + offend.FirstName AS 'OffenderName',  
     (CASE When DateAdd(mi,tz.UTCOFFSET,a.ReceivedTime) Between ds.start AND ds.[end]

                                THEN DateAdd(mi,tz.DaylightUTCOFFSET,a.ReceivedTime)

                                ELSE DateAdd(mi,tz.UTCOFFSET,a.ReceivedTime)END)AS 'ReceivedTime',

     e.ExternalBatteryVoltage,   
     apas.MessageSubject,  
     apas.MessageBody  
       
   FROM AlarmProtocolAction apa  
   INNER JOIN AlarmProtocolEvent ape ON  
    apa.AlarmProtocolEventID = ape.AlarmProtocolEventID  
   INNER JOIN EventType et ON  
    ape.GatewayEventID = et.EventTypeID  
     INNER JOIN AlarmProtocolActionSettings apas ON  
    apa.AlarmProtocolEventID = apas.AlarmProtocolEventID  
   INNER JOIN Alarm a ON  
    ape.GatewayEventID = a.EventTypeID  
   INNER JOIN Gateway.dbo.Events e ON  
    a.TrackerID = e.DeviceID AND  
    a.EventTypeID = e.EventID AND  
    a.EventTime = e.EventTime  
   INNER JOIN Offender offend ON  
    a.OffenderID = offend.OffenderID  
 iNNER JOIN agency ag On ag.agencyid = offend.agencyid
   iNNER JOIN Timezone tz on tz.timezoneid = ag.timezoneid
	iNNER JOIN DaylightSaving ds ON ds.[year] = DATEPART(yy,a.ReceivedTime)
   WHERE apa.AlarmProtocolActionID = @AlarmProtocolActionID AND  
     a.AlarmID = @AlarmID AND  
     a.OffenderID = @OffenderID AND  
   apa.Deleted = 0
GO
GRANT EXECUTE ON [AlarmProtocolActionGetSettings] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [AlarmProtocolActionGetSettings] TO [db_object_def_viewers]
GO
