/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TrackerGetUnassignedByAgencyID]

	@AgencyID		INT

AS
SELECT	TrackerID, TrackerNumber
	FROM	Tracker 
	WHERE	Deleted = 0 AND 
			AgencyID = @AgencyID AND TrackerID NOT IN
			(SELECT DISTINCT  isnull(TrackerID,0)
			 FROM Offender
			 WHERE Deleted = 0)
GO
GRANT EXECUTE ON [TrackerGetUnassignedByAgencyID] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [TrackerGetUnassignedByAgencyID] TO [db_object_def_viewers]
GO
