/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TrackerGetAllUnassigned]
        @GatewayPort    varchar(10),
        @GatewayIp              varchar(20)
AS
                 SELECT DeviceID INTO #tmp
                 FROM Gateway..DeviceProperties
                 WHERE PropertyValue IN(@GatewayIP,@GatewayPort) AND PropertyID IN('8410','8411')
                 GROUP BY DeviceID
                 HAVING MAX(CASE WHEN PropertyID = '8410' THEN PropertyValue ELSE '' END) <> '';
                 DECLARE @sql VARCHAR(MAX)

                 SET @sql = 'CREATE UNIQUE CLUSTERED INDEX IX_' + REPLACE(CONVERT(VARCHAR(100),(RAND() * 1000000)),'.','0') + ' ON #tmp(DeviceID)'
                 EXEC(@sql)

SELECT
                d.DeviceID AS 'TrackerID',
                UniqueID AS 'TrackerNumber'
        FROM
                Gateway.dbo.Devices d
                INNER JOIN #tmp dp ON dp.DeviceID = d.DeviceID
        WHERE
--              d.DeviceID NOT IN (SELECT TrackerID FROM Tracker t WHERE t.RmaID IS NOT NULL OR t.Deleted = 0)
                d.DeviceID NOT IN (SELECT TrackerID FROM Tracker t WHERE t.Deleted = 0)  AND
                d.Deleted = 0
    ORDER BY UniqueID

DROP TABLE #tmp

--DEPRICATED CODE 2/8/2008
--      SELECT
--              d.DeviceID AS 'TrackerID',
--              UniqueID AS 'TrackerNumber'
--      FROM
--              Gateway.dbo.Devices d
--              LEFT JOIN Gateway.dbo.DeviceProperties dp1 ON dp1.DeviceID = d.DeviceID AND dp1.propertyID='8410'
--              LEFT JOIN Gateway.dbo.DeviceProperties dp2 ON dp2.DeviceID = d.DeviceID AND dp2.propertyID='8411'
--      WHERE
--              d.DeviceID NOT IN (SELECT TrackerID FROM Tracker t WHERE t.RmaID IS NOT NULL OR t.Deleted = 0)
--              d.DeviceID NOT IN (SELECT TrackerID FROM Tracker t WHERE t.Deleted = 0)
--              AND Deleted = 0
--              AND (dp1.PropertyValue = @GatewayIp AND dp2.PropertyValue = @GatewayPort)
--      ORDER BY
--              UniqueID
GO
GRANT VIEW DEFINITION ON [TrackerGetAllUnassigned] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [TrackerGetAllUnassigned] TO [db_dml]
GO
