/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [BeaconDelete]
	@BeaconID INT
AS
BEGIN
	SET NOCOUNT ON;
    BEGIN TRANSACTION 
 
    DELETE  dbo.ScheduleRepeatedDay
	WHERE   ScheduleID in(Select s.ID from Schedule s inner join [Rule]r ON s.RuleID=r.ID inner join ERule e ON e.RuleID=r.ID  where e.BeaconID=@BeaconID)
	
    DELETE  dbo.Schedule
	WHERE   RuleID in (Select r.ID from [Rule] r inner join ERule e ON e.RuleID=r.ID where e.BeaconID=@BeaconID)

    DELETE [Rule]
    WHERE  ID in (Select e.RuleID from [Rule] r inner join ERule e ON e.RuleID=r.ID where e.BeaconID=@BeaconID)
	
    DELETE ERule 
	WHERE  BeaconID=@BeaconID 
 
	DELETE Beacon 
	WHERE ID=@BeaconID

	Delete beaconOffender
	WHERE BEaconID=@BeaconID
	
    COMMIT TRANSACTION
END



GO
GRANT EXECUTE ON [BeaconDelete] TO [db_dml]
GO
