/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoZoneGroupMembersDelete]
	
         @ZoneGroupId          uniqueidentifier ,
         @MemberId              uniqueidentifier

AS
SET NOCOUNT ON;
BEGIN
	BEGIN TRAN
	
		DECLARE @MemberType int;
		SET @MemberType =
			(SELECT [Type] FROM GeoZone WHERE Id = @MemberId);

		DELETE FROM GeoZoneGroupMembers
		WHERE (ZoneGroupId =@ZoneGroupId) and  (MemberId=@MemberId)

		EXEC dbo.GeoZoneUpdateMemberCount @ZoneGroupId, @MemberType

	COMMIT TRAN
END       




GO
GRANT EXECUTE ON [GeoZoneGroupMembersDelete] TO [db_dml]
GO
