/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderVehicleInsert]
	@iOffenderVehicleID int OUTPUT,
	@iOffenderID int,
	@sLicensePlate nvarchar(50) = null,
	@sMake nvarchar(50) = null,
	@sModel nvarchar(50) = null,
	@sYear nvarchar(5) = null,
	@sColor nvarchar(20) = null,
	@sSpecialMarkings nvarchar(2000) = null,
	@sRegisteredOwner nvarchar(50) = null,
	@sRegisteredOwnerPhone nvarchar(25) = null,
	@sVIN nvarchar(50) = null,
	@sLocationStreet1 nvarchar(100) = null,
	@sLocationStreet2 nvarchar(100) = null,
	@sLocationCity nvarchar(50) = null,
	@iLocationStateID int = null,
	@sLocationPostalCode nvarchar(50) = null,
	@iLocationCountryID int = null,
	@sInsuranceCompanyName nvarchar(50) = null,
	@sInsurancePolicyNumber nvarchar(50) = null,
	@sInsuranceAgent nvarchar(50) = null,
	@sInsurancePrimaryPhone nvarchar(25) = null,
	@sInsuranceFax nvarchar(25) = null

AS
BEGIN
	SET NOCOUNT ON;
		
	INSERT INTO OffenderVehicle(
		OffenderID ,
		LicensePlate,
		Make,
		Model,
		Year,
		Color,
		SpecialMarkings,
		RegisteredOwner,
		RegisteredOwnerPhone,
		VIN,
		LocationStreet1,
		LocationStreet2,
		LocationCity,
		LocationStateID,
		LocationPostalCode,
		LocationCountryID	,
		InsuranceCompanyName,
		InsurancePolicyNumber,
		InsuranceAgent,
		InsurancePrimaryPhone,
		InsuranceFax
	) 
	VALUES 
	(
		@iOffenderID,
		@sLicensePlate ,
		@sMake ,
		@sModel ,
		@sYear ,
		@sColor ,
		@sSpecialMarkings ,
		@sRegisteredOwner ,
		@sRegisteredOwnerPhone ,
		@sVIN ,
		@sLocationStreet1 ,
		@sLocationStreet2 ,
		@sLocationCity ,
		@iLocationStateID,
		@sLocationPostalCode,
		@iLocationCountryID ,
		@sInsuranceCompanyName ,
		@sInsurancePolicyNumber ,
		@sInsuranceAgent ,
		@sInsurancePrimaryPhone,
		@sInsuranceFax

	)

SET @iOffenderVehicleID = SCOPE_IDENTITY()

END
GO
GRANT VIEW DEFINITION ON [OffenderVehicleInsert] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OffenderVehicleInsert] TO [db_dml]
GO
