/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [DistributorGetByID]
	@DistributorID	INT
AS

	SELECT	DistributorID, 
			DistributorName, 
			StreetLine1,
			StreetLine2,
			City,
			StateID,
			PostalCode,
			CountryID,
			Phone,
			Fax,
			URL,
			EmailAddress,
			CreatedDate,
			CreatedByID,
			ModifiedDate,
			ModifiedByID,
			Deleted,
			TimeZoneID,
			DaylightSavings,
			ISNULL(TamID,0) AS 'TamID',
			Assign,
			Activate
	FROM	Distributor
	WHERE	DistributorID = @DistributorID
	ORDER BY DistributorName
GO
GRANT VIEW DEFINITION ON [DistributorGetByID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [DistributorGetByID] TO [db_dml]
GO
