/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mTrackerActivationsAll]

AS

SELECT TrackerActivationID, TrackerID, OffenderID, OfficerID, ActivateDate, ModifiedByID, IsDemo, BillableID
FROM OffenderTrackerActivation 
WHERE DeActivateDate IS NULL

GO
GRANT EXECUTE ON [mTrackerActivationsAll] TO [db_dml]
GO
