/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderAcquaintanceGetAllNamesByOffenderID]
	@iOffenderID int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT OffenderAcquaintanceID,
		ISNULL(FirstName + ' ', '') + 
		ISNULL(MiddleName + ' ', '') +
		ISNULL(LastName + ' ', '') AS 'AcquaintanceName'
	FROM OffenderAcquaintance
	WHERE OffenderID = @iOffenderID
END

GO
GRANT VIEW DEFINITION ON [OffenderAcquaintanceGetAllNamesByOffenderID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OffenderAcquaintanceGetAllNamesByOffenderID] TO [db_dml]
GO
