/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:26 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AgencyServicesDelete]    
 @AgencyID INT,      
 @ServiceID INT    
AS      
      
--Adds a new attribute node.      
BEGIN TRAN      
DELETE      
FROM AgencyServices     
WHERE AgencyID=@AgencyID AND ServiceID = @ServiceID    
COMMIT TRAN;
  
  
  
GO
GRANT EXECUTE ON [AgencyServicesDelete] TO [db_dml]
GO
