/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoScheduleZonesAdd]
	@ScheduleId			uniqueidentifier ,
	@ZoneId				uniqueidentifier 
AS

SET NOCOUNT ON;
BEGIN
	BEGIN TRAN
		INSERT INTO GeoScheduleZones (ScheduleId,ZoneId)
		VALUES 	(@ScheduleId,@ZoneId)
	COMMIT TRAN
END
	


GO
GRANT EXECUTE ON [GeoScheduleZonesAdd] TO [db_dml]
GO
