/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:26 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AccessLevelGetAll]

AS

	SET NOCOUNT ON

	SELECT	AccessLevelID, AccessLevel
	FROM	AccessLevel
	ORDER BY AccessLevelID, UserTypeID
GO
GRANT EXECUTE ON [AccessLevelGetAll] TO [db_dml]
GO
GRANT EXECUTE ON [AccessLevelGetAll] TO [WebClient]
GO
GRANT VIEW DEFINITION ON [AccessLevelGetAll] TO [db_object_def_viewers]
GO
