/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [DistributorEmployeeGetByUserID]
	@UserID	INT
AS
BEGIN
	SET NOCOUNT ON;

SELECT *
FROM DistributorEmployee de
WHERE	de.UserID = @UserID AND
		de.Deleted = 0

END
GO
GRANT VIEW DEFINITION ON [DistributorEmployeeGetByUserID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [DistributorEmployeeGetByUserID] TO [db_dml]
GO
