/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoRuleReferencePointAdd]

	@GeoRuleReferencePointID	INT OUTPUT,
	@Street						NVARCHAR(50),
	@City						NVARCHAR(50),
	@StateID					INT,
	@PostalCode					NVARCHAR(25),
	@CountryID					INT,
	@Longitude					FLOAT,
	@Latitude					FLOAT

AS

	INSERT INTO GeoRuleReferencePoint
	(Street, City, StateID, PostalCode, CountryID, Longitude, Latitude)
	VALUES
	(@Street, @City, @StateID, @PostalCode, @CountryID, @Longitude, @Latitude)

	SET @GeoRuleReferencePointID = @@IDENTITY
GO
GRANT VIEW DEFINITION ON [GeoRuleReferencePointAdd] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [GeoRuleReferencePointAdd] TO [db_dml]
GO
