/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mAlarmAssignmentStatusGetAll]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT AlarmAssignmentStatusID, AlarmAssignmentStatusName FROM AlarmAssignmentStatus
END

GO
GRANT EXECUTE ON [mAlarmAssignmentStatusGetAll] TO [db_dml]
GO
