/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mAgencyArchive]

	@AgencyID		INT,
	@ModifiedByID	INT

AS
BEGIN
	UPDATE Agency
	SET	Deleted = 1,
		ModifiedDate = GETDATE(),
		ModifiedByID = @ModifiedByID
	WHERE AgencyID = @AgencyID
	
	IF (SELECT COUNT (*) FROM AgencyProtocolActionsAllowed WHERE AgencyID=@AgencyID) <> 0
	DELETE FROM AgencyProtocolActionsAllowed WHERE AgencyID=@AgencyID
	
END



GO
GRANT EXECUTE ON [mAgencyArchive] TO [db_dml]
GO
