/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:26 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AgencyGetGridInfoByDistributorID]
	@DistributorID int
AS
	SELECT	a.AgencyID, a.Agency, a.City, s.State
	FROM	Agency a(NOLOCK)
	LEFT JOIN State s ON a.StateID = s.StateID
	WHERE	a.Deleted = 0 AND
			a.DistributorID = @DistributorID
	ORDER BY a.Agency
GO
GRANT VIEW DEFINITION ON [AgencyGetGridInfoByDistributorID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [AgencyGetGridInfoByDistributorID] TO [db_dml]
GO
