/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderAddPhoto]
	@iOffenderImageID INT OUTPUT,
	@iOffenderID INT,
	@iImageType INT,
	@sImageName NVARCHAR(100),
	@sImagePath NVARCHAR(260),
	@iItemID INT

AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO OffenderImage
	(OffenderID, ImageType, ImageName, ImagePath,ItemID)
	VALUES
	(@iOffenderID, @iImageType, @sImageName, @sImagePath,@iItemID)

	SET @iOffenderImageID = @@IDENTITY
END
GO
GRANT EXECUTE ON [OffenderAddPhoto] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [OffenderAddPhoto] TO [db_object_def_viewers]
GO
