/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportingNumOfBeaconsGetByOffenderID] 
@NumOfBeacons INT OUTPUT,
@OffenderID INT   

AS  
  
--Procedure returns data about and Agencies billing services.  
  
SET NOCOUNT ON;  
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;  

set @NumOfBeacons=(SELECT top 1 ob.BeaconCount  
FROM dbo.EArrestService eas   
INNER JOIN dbo.ClassicBillingService cbs ON eas.ClassicBillingServiceID = cbs.ID   
INNER JOIN dbo.BillingService bs ON cbs.BillingServiceID = bs.ID  
INNER JOIN dbo.Agency a ON bs.AgencyID = a.AgencyID  
INNER JOIN dbo.Offender o ON a.AgencyID = o.AgencyID
inner join dbo.BillingServiceOption bso on  bso.BillingServiceID=bs.ID  
inner join dbo.OptionalBillingServiceOptionOffender ob on ob.BillingServiceoptionID =  bso.id 
WHERE ob.OffenderID = @OffenderID)

if @NumOfBeacons is NULL 

set @NumOfBeacons=(SELECT top 1 eas.BeaconLimit
FROM dbo.EArrestService eas 
INNER JOIN dbo.ClassicBillingService cbs ON eas.ClassicBillingServiceID = cbs.ID 
INNER JOIN dbo.BillingService bs ON cbs.BillingServiceID = bs.ID
INNER JOIN dbo.Agency a ON bs.AgencyID = a.AgencyID
INNER JOIN dbo.Offender o ON a.AgencyID = o.AgencyID
WHERE o.OffenderID = @OffenderID)

if @NumOfBeacons is NULL 
set @NumOfBeacons = -1

GO
GRANT EXECUTE ON [ReportingNumOfBeaconsGetByOffenderID] TO [db_dml]
GO
