/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoSchedule_GetQueueLogByUploadStatus]
       
AS

	SELECT QueueLogID,QueueSegmentID,AttemptTime,GatewayRequestID,UploadStatus
	FROM GeoScheduleQueueLog
	WHERE UploadStatus = 1
GO
GRANT EXECUTE ON [GeoSchedule_GetQueueLogByUploadStatus] TO [db_dml]
GO
