/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [RolesGetBySearch]

@RoleName nvarchar(50)

AS

SET NOCOUNT ON

	SELECT RoleID, [Role]
	FROM [Role]
	WHERE 
	(LEN(@RoleName) <= 0)
	OR
	([Role] LIKE '%' + @RoleName + '%')
GO
GRANT VIEW DEFINITION ON [RolesGetBySearch] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [RolesGetBySearch] TO [db_dml]
GO
