/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoSchedule_QueueAdd]
	
	@QueueSegmentID             INT OUTPUT,
	@ActiveScheduleID			uniqueidentifier,
	@CreateTime					DATETIME,
	@DeviceID					INT,
	@ActivateTime				DATETIME,
	@TimeThresholdSource		INT,
	@SegmentStatus				INT,
	@RuleXML					NVARCHAR(MAX)


AS





INSERT INTO GeoScheduleQueue
(ActiveScheduleID, CreateTime,DeviceID,ActivateTime,TimeThresholdSource,SegmentStatus,RuleXML)
VALUES
(@ActiveScheduleID,@CreateTime,@DeviceID,@ActivateTime,@TimeThresholdSource,@SegmentStatus,@RuleXML)


SET @QueueSegmentID = @@IDENTITY
GO
GRANT EXECUTE ON [GeoSchedule_QueueAdd] TO [db_dml]
GO
