/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoZoneGroupMembersAdd]

         @ZoneGroupId          uniqueidentifier ,
         @MemberId              uniqueidentifier,
		 @MemberType                        Int

AS
SET NOCOUNT ON;
BEGIN
	BEGIN TRAN

		INSERT INTO GeoZoneGroupMembers(ZoneGroupId,MemberId,MemberType)
		VALUES(@ZoneGroupId,@MemberId,@MemberType)

		EXEC dbo.GeoZoneUpdateMemberCount @ZoneGroupId, @MemberType

	COMMIT TRAN
END



GO
GRANT EXECUTE ON [GeoZoneGroupMembersAdd] TO [db_dml]
GO
