/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [MaintFindDuplicateAlarms]
as
	DECLARE @AlarmID int
	DECLARE @EventTime bigint
	DECLARE @DeviceID int
	DECLARE @EventID int
	DECLARE @EventDisplayTIme datetime
	DECLARE crsr_alarms CURSOR FAST_FORWARD for select EventTypeID,TrackerID,EventTime from Alarm
	OPEN crsr_alarms
	FETCH NEXT FROM crsr_alarms INTO @EventID,@DeviceID,@EventTime
	WHILE @@FETCH_STATUS=0
	BEGIN
		if ((SELECT count(*) from Alarm WHERE EventTIme=@EventTime and TrackerID=@DeviceID and EventTypeID=@EventID)>1)
		BEGIN
			set @AlarmID=(SELECT Top 1 AlarmID from ALarm WHERE EventTIme=@EventTime and TrackerID=@DeviceID and EventTypeID=@EventID)
			PRINT convert(varchar,@AlarmID)+'has duplicate'
			
		END
		
		FETCH NEXT FROM crsr_alarms INTO @EventID,@DeviceID,@EventTime
	END
	CLOSE crsr_alarms
	DEALLOCATE crsr_alarms

GO
GRANT EXECUTE ON [MaintFindDuplicateAlarms] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [MaintFindDuplicateAlarms] TO [db_object_def_viewers]
GO
