/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mAlarmAssignmentInsert]

	@AlarmAssignmentID			INT OUTPUT,
	@AlarmID					INT,
	@AlarmAssignmentStatusID	INT,
	@AssignedToID				INT,
	@AssignedByID				INT

AS

INSERT INTO	AlarmAssignment
	(AlarmID, AlarmAssignmentStatusID, AssignedToID, AssignedByID)
	VALUES
	(@AlarmID, @AlarmAssignmentStatusID, @AssignedToID, @AssignedByID);

	SET @AlarmAssignmentID = @@IDENTITY;

GO
GRANT EXECUTE ON [mAlarmAssignmentInsert] TO [db_dml]
GO
