/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderUpdateVehiclePhoto]

	@OffenderID INT,
	@FileName	NVARCHAR(100)

AS

SET NOCOUNT ON

UPDATE [dbo].[Offender] SET

	VehiclePhotoName = @FileName

WHERE OffenderID = @OffenderID
GO
GRANT EXECUTE ON [OffenderUpdateVehiclePhoto] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [OffenderUpdateVehiclePhoto] TO [db_object_def_viewers]
GO
