/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportPassiveMonitoring]

@Agencyid int

AS
Select
ofi.LastName+', '+ofi.FirstName As 'Officer'
,o.LastName+', '+o.FirstName As 'Offender'
,rpt.EventNAme
,dbo.fnUtcToLocal(@Agencyid,rpt.EventDateTime) AS 'Time'
,rpt.Address AS 'Location'
,rpt.GeoRule AS 'Rule'
,ag.Agency as 'Agency'
From dbo.rprtEventsBucket1 rpt
JOIN Officer ofi ON ofi.officerid = rpt.officerid
JOIN Offender o ON o.Offenderid = rpt.Offenderid
JOIN OptionalBillingServiceOptionOffender obsoo ON obsoo.Offenderid = rpt.Offenderid
JOIN BillingServiceOption bso ON bso.id = obsoo.BillingServiceOptionid
JOIN ClassicBillingservice cbs ON cbs.Billingserviceid = bso.Billingserviceid
JOIN Agency ag ON ag.agencyid = rpt.agencyid
JOIN Timezone tz on tz.timezoneid = ag.timezoneid
--JOIN AgencyServices ags ON ags.Agencyid = ag.agencyid

WHERE dbo.fnUtcToLocal(@Agencyid,rpt.EventDateTime) BETWEEN DATEADD(hh,-24,CONVERT(DATETIME, FLOOR(CONVERT(FLOAT,dbo.fnUtcToLocal(@Agencyid,GETDATE())))))
AND CONVERT(DATETIME, FLOOR(CONVERT(FLOAT,dbo.fnUtcToLocal(@Agencyid,GETDATE()))))

AND rpt.Agencyid = @Agencyid AND rpt.alarmtype > 1 And (cbs.Serviceid = 2 OR @Agencyid IN (1450,1566))
--And ags.Serviceid = 1
ORDER BY ofi.LastName+', '+ofi.FirstName,o.LastName+', '+o.FirstName,rpt.EventDateTime
GO
GRANT EXECUTE ON [ReportPassiveMonitoring] TO [db_dml]
GO
