/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmGetUnacknowledgedAlarms]

AS
BEGIN
	SET NOCOUNT ON;

	SELECT a.AlarmID, a.OffenderID, a.TrackerID, a.EventTypeID, a.EventTime, ROUND(a.Latitude,5), ROUND(a.Longitude,5)
	FROM Alarm a
	WHERE a.AlarmID NOT IN (SELECT AlarmID FROM AlarmAcknowledgement)
END
GO
GRANT VIEW DEFINITION ON [AlarmGetUnacknowledgedAlarms] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [AlarmGetUnacknowledgedAlarms] TO [db_dml]
GO
