/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoRule_OffenderGetZoneID]
    @iGeoRuleID INT,
    @iZoneID INT OUTPUT
AS 
    SELECT @iZoneID = ZoneID
    FROM GeoRule_Offender
    WHERE GeoRuleID=@iGeoRuleID

GO
GRANT EXECUTE ON [GeoRule_OffenderGetZoneID] TO [db_dml]
GO
