/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderTrackerActivationGetByID]

	@TrackerActivationID	INT

AS

	SELECT
		t.TrackerActivationID,
		t.TrackerID, 
		t.OffenderID, 
		t.OfficerID,
		t.ActivateDate,
		t.DeactivateDate,
		t.ModifiedByID,
		t.IsDemo, 
		t.BillableID
	FROM	
		[OffenderTrackerActivation] t
	WHERE
		t.TrackerActivationID = @TrackerActivationID



GO
GRANT EXECUTE ON [OffenderTrackerActivationGetByID] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [OffenderTrackerActivationGetByID] TO [db_object_def_viewers]
GO
