/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OfficerGetGridInfoByDistributorEmployeeID]
	@DistributorEmployeeID INT,
	@FirstName	NVARCHAR(50),
	@LastName	NVARCHAR(50),
	@AgencyID	INT

AS
SELECT	o.OfficerID, o.FirstName, o.LastName, r.[Role], a.Agency
FROM	Officer o
join Agency a on a.AgencyID = o.AgencyID
join Distributor d on d.DistributorID = a.DistributorID
join DistributorEmployee de on de.DistributorID = d.DistributorID
left JOIN User_Role ur ON o.UserID = ur.UserID
left JOIN [Role] r ON ur.RoleID = r.RoleID
WHERE de.DistributorEmployeeID = @DistributorEmployeeID AND
	o.Deleted = 0 
    AND
    (
		(LEN(@FirstName) <= 0)
		OR
		(o.FirstName LIKE '%' + @FirstName + '%')
	)	
	AND
	(
		(LEN(@LastName) <= 0)
		OR
		(o.LastName Like '%' + @LastName + '%')
	)	

	AND
	(
		(@AgencyID = 0)
		OR
		(a.AgencyID = @AgencyID)
	)

GO
GRANT EXECUTE ON [OfficerGetGridInfoByDistributorEmployeeID] TO [db_dml]
GO
