/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoRuleUpdateStatus]

	@GeoRuleID					INT,
	@StatusID					INT

AS

	IF @StatusID != 4 BEGIN 
		UPDATE	GeoRule
		SET		StatusID = @StatusID,
				UpdateInProgress = 0
		WHERE	GeoRuleID = @GeoRuleID
	END
	ELSE
		UPDATE	GeoRule
		SET		StatusID = @StatusID,
				UpdateInProgress = 1
		WHERE	GeoRuleID = @GeoRuleID
GO
GRANT VIEW DEFINITION ON [GeoRuleUpdateStatus] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [GeoRuleUpdateStatus] TO [db_dml]
GO
