/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [UserRoleAdd]

	@EntityID		INT,
	@UserTypeID		INT,
	@RoleID			INT

AS

SET NOCOUNT ON

	-- get UserID based on @EntityID (OperatorID or OfficerID)
	DECLARE @UserID INT
	SET @UserID = 0
	
	IF @UserTypeID = 1 -- Operator
	BEGIN
		SELECT	@UserID = UserID
		FROM	Operator
		WHERE	OperatorID = @EntityID
	END
	ELSE IF @UserTypeID = 2 -- Officer
	BEGIN
		SELECT	@UserID = UserID
		FROM	Officer
		WHERE	OfficerID = @EntityID
	END

	IF @UserID <> 0
	BEGIN
		INSERT INTO UserRoleMap
		( UserID, RoleID )
		VALUES
		( @UserID, @RoleID )
	END
	ELSE
	BEGIN
		RAISERROR('EntityID %s does not have a corresponding OperatorID or OfficerID', 16, 1, @EntityID)
	END
GO
GRANT VIEW DEFINITION ON [UserRoleAdd] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [UserRoleAdd] TO [db_dml]
GO
