/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [DistributorEmployeeGetBySearch]


    @FirstName	NVARCHAR(50),
	@LastName	NVARCHAR(50),
	@DistributorID	INT,
	@UserID INT =-1,
    @RoleID INT =-1

AS

    if(@RoleID <> 19)


	BEGIN
	SELECT	d.DistributorEmployeeId,de.DistributorName, d.FirstName, d.LastName, r.Role
   
      FROM         DistributorEmployee AS d LEFT OUTER JOIN
                      User_Role AS ur ON d.UserID = ur.UserID LEFT OUTER JOIN
                      Role AS r ON ur.RoleID = r.RoleID RIGHT OUTER JOIN
                      Distributor AS de ON de.DistributorID = d.DistributorID
		
				WHERE	
				(
					(LEN(@FirstName) <= 0 )
					OR
					(d.FirstName LIKE '%' + @FirstName + '%')
				)	
				AND
				(
					(LEN(@LastName) <= 0)
					OR
					(d.LastName Like '%' + @LastName + '%')
				)	
				AND
				(
					(@DistributorID =0)
					OR
					(d.DistributorID = @DistributorID)
				)	
				and
				d.Deleted = 0
				ORDER BY  d.LastName, d.FirstName
        END
    ELSE
       BEGIN

       Select d.DistributorEmployeeId,de.DistributorName, d.FirstName, d.LastName
	   FROM  (SELECT	dis.DistributorID, dis.DistributorName
	           FROM	Distributor dis
	
	          LEFT JOIN User_Role ur ON dis.TamID = ur.UserID
	
             WHERE	deleted = 0 AND
			 ur.RoleID = 19 AND 
			 ur.UserID = @UserID)de  left join   DistributorEmployee d on d.DistributorID=de.DistributorID
        WHERE
             (
					(LEN(@FirstName) <= 0 )
					OR
					(d.FirstName LIKE '%' + @FirstName + '%')
				)	
				AND
				(
					(LEN(@LastName) <= 0)
					OR
					(d.LastName Like '%' + @LastName + '%')
				)	
				AND
				(
					(@DistributorID =0)
					OR
					(d.DistributorID = @DistributorID)
				)	
				and
				d.Deleted = 0
				ORDER BY  d.LastName, d.FirstName

end

GO
GRANT EXECUTE ON [DistributorEmployeeGetBySearch] TO [db_dml]
GO
