/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderChargeDeleteByOffenderCurrentChargeID]
	@iOffenderCurrentChargeID int

AS
BEGIN

DELETE FROM OffenderCurrentCharge 
WHERE OffenderCurrentChargeID = @iOffenderCurrentChargeID

END


GO
GRANT VIEW DEFINITION ON [OffenderChargeDeleteByOffenderCurrentChargeID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OffenderChargeDeleteByOffenderCurrentChargeID] TO [db_dml]
GO
