/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ScheduleAdd]
	@ID		             INT OUTPUT,	
	@StartDateTime     DATETIME,
	@EndDateTime    	 DATETIME,
	@AlwaysOn		     BIT,	
	@RuleID	             INT
	

AS
BEGIN

	INSERT INTO dbo.Schedule
	(StartDateTime,EndDateTime,AlwaysOn,RuleID)
	VALUES
	(@StartDateTime,@EndDateTime,@AlwaysOn,@RuleID)

	SET @ID = @@IDENTITY


END





GO
GRANT EXECUTE ON [ScheduleAdd] TO [db_dml]
GO
