/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mCapabilitiesAll]
AS
BEGIN

SELECT tc.CapabilityID,tc.CapabilityName,tv.VersionNumber,tvc.ID
   
FROM  TrackerVersionCapability   tvc
LEFT JOIN TrackerCapability tc  ON tc.CapabilityID = tvc.CapabilityID   
LEFT JOIN TrackerVersion tv ON tv.ID = tvc.VersionID 

	  
END



GO
GRANT EXECUTE ON [mCapabilitiesAll] TO [db_dml]
GO
