/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportAgencyDevices]
        @StartDate		DateTime,
		@TimeZoneOffset	int,
		@GatewayIp		varchar(20)	='02486246',	
		@GatewayPort	varchar(10)='21D9'

AS
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN
	-- Add TZ to the range, but subtract TZ on the output data.  DK 4-7-07
	SET @StartDate = DATEADD(minute, @TimeZoneOffset, @StartDate)

	-- Script to find all the devices per agency
	SELECT 
		a.AgencyID,
		COUNT(DISTINCT t.TrackerID) AS 'TotalAssigned'	
	INTO #AssignedDevices
	FROM Tracker t
		LEFT JOIN Agency a ON t.AgencyID = a.AgencyID
	WHERE t.Deleted = 0
		or (t.deleted=1 and t.modifiedDate>@StartDate)
		and t.trackerUniqueID = (select max(trackerUniqueID) from tracker where trackerid= t.TrackerID) 
	GROUP BY a.AgencyID
	ORDER BY a.AgencyID

	-- Script used to find all active devices per agency
	SELECT DISTINCT
		a.AgencyID
		,count(ota.trackerid) As 'TotalActive'
	INTO #ActiveDevices
	FROM Offendertrackeractivation ota
		JOIN Offender o ON o.Offenderid = ota.offenderid
		JOIN Agency a ON a.agencyid = o.agencyid
		WHERE ota.ActivateDate <= @StartDate AND (ota.DeactivateDate > @StartDate OR ota.DeactivateDate IS NULL)
		GROUP BY a.AgencyID
	ORDER BY a.AgencyID

	SELECT DISTINCT
		a.SFDCAccount AS 'SFDCACCT#',
		REPLACE( a.Agency, ',', ';' ) AS 'Agency',
      st.Abbreviation As 'State',
		ass.TotalAssigned AS 'TotalAssignedDevices',
		isnull(act.TotalActive,0) AS 'ActiveDevices',
		(ass.TotalAssigned - isnull(act.TotalActive,0)) AS 'InactiveDevices'	
	FROM Agency a
		inner JOIN #AssignedDevices ass ON a.AgencyID = ass.AgencyID
		left JOIN #ActiveDevices act ON a.AgencyID = act.AgencyID
      INNER JOIN State st ON st.stateid = a.stateid
	ORDER BY 'Agency'

END



GO
GRANT EXECUTE ON [ReportAgencyDevices] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [ReportAgencyDevices] TO [db_object_def_viewers]
GO
