/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoScheduleAdd]
        @GeoScheduleId                          uniqueidentifier OUTPUT,
        @Name                           nchar(50),
        @Description            nchar(50),
        @ScheduleState          int,
        @ScheduleStateTime      DateTime,
        @AssignedOffender    INT,
		@OwnerID int

AS

SET NOCOUNT ON;
BEGIN
	BEGIN TRAN
		SET @GeoScheduleId= NewId();
			INSERT INTO GeoSchedule(id,Name,Description,ScheduleState,ScheduleStateTime,AssignedOffender,OwnerId)
	        VALUES(@GeoScheduleId,@Name, @Description, @ScheduleState, @ScheduleStateTime, @AssignedOffender,@OwnerID)
	COMMIT TRAN
END









GO
GRANT EXECUTE ON [GeoScheduleAdd] TO [db_dml]
GO
