/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TempOffenderTrackerDeActivate]
	
	@TrackerID		INT,
	@OffenderID		INT,
	@OfficerID		INT,
	@ModifiedByID	INT,
	@ModifiedDate	DateTime
AS

UPDATE OffenderTrackerActivation
SET	DeActivateDate = @ModifiedDate,
	ModifiedByID = @ModifiedByID
WHERE TrackerID = @TrackerID
	AND OffenderID = @OffenderID
	AND OfficerID = @OfficerID
GO
GRANT VIEW DEFINITION ON [TempOffenderTrackerDeActivate] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [TempOffenderTrackerDeActivate] TO [db_dml]
GO
