/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OperatorGetByID]

	@OperatorID	INT,
	@GetDeleted BIT = 0

AS

	SELECT	u.UserID ,--AS 'OperatorUserID',
			u.UserName,
			u.UserPassword,
			u.UserPassCode,
			u.UserTypeID,
			u.CreatedDate,
			u.CreatedByID,
			u.ModifiedDate,
			u.ModifiedByID,
			ur.RoleID,
			o.OperatorID,
			o.Deleted,
			ISNULL(o.Title, '') AS 'Title',
			ISNULL(o.Department, '') AS 'Department',
			ISNULL(o.SalutationID, 0) AS 'SalutationID',
			ISNULL(o.FirstName, '') AS 'FirstName',
			ISNULL(o.MiddleName, '') AS 'MiddleName',
			ISNULL(o.LastName, '') AS 'LastName',
			ISNULL(o.SuffixID, 0) AS 'SuffixID',
			ISNULL(o.StreetLine1, '') AS 'StreetLine1',
			ISNULL(o.StreetLine2, '') AS 'StreetLine2',
			ISNULL(o.City, '') AS 'City',
			ISNULL(o.StateID, 0) AS 'StateID',
			ISNULL(o.PostalCode,'') AS 'PostalCode',
			ISNULL(o.CountryID, 0) AS 'CountryID',
			ISNULL(o.DayPhone, '') AS 'DayPhone',
			ISNULL(o.EveningPhone, '') AS 'EveningPhone',
			ISNULL(o.MobilePhone, '') AS 'MobilePhone',
			Isnull(o.Pager,'') as 'Pager',
			ISNULL(o.Fax, '') AS 'Fax',
			ISNULL(o.EmailAddress1, '') AS 'EmailAddress1',
			ISNULL(o.EmailAddress2, '') AS 'EmailAddress2',
			ISNULL(o.ExtDayPhone, '') AS 'ExtDayPhone',
			ISNULL(o.ExtEveningPhone, '') AS 'ExtEveningPhone',
			Isnull(o.ModifiedByID,'') as 'ModifiedByID',
			ISNULL(o.ModifiedDate,'') as 'ModifiedDate'
	FROM	Operator o
	INNER JOIN [User] u ON o.UserID = u.UserID
	INNER JOIN User_Role ur ON u.UserID = ur.UserID
	WHERE	o.OperatorID = @OperatorID AND (@GetDeleted = 1 OR o.Deleted = 0)
GO
GRANT VIEW DEFINITION ON [OperatorGetByID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OperatorGetByID] TO [db_dml]
GO
