/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OfficerHasOffenderAssigned]
	@OfficerID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT case  when count(o.OffenderID) > 0 then 1  else 0 end
	FROM	Offender o
	INNER JOIN Offender_Officer oo ON o.OffenderID = oo.OffenderID
	where oo.officerID=@OfficerID
	
END
GO
GRANT EXECUTE ON [OfficerHasOffenderAssigned] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [OfficerHasOffenderAssigned] TO [db_object_def_viewers]
GO
