/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [StaticTrackersForTrackerID]
	@TrackerID bigint


AS

BEGIN

	SET NOCOUNT ON;

	select TrackerUniqueID,CreatedDate from Tracker  where TrackerID=@TrackerID
		

END
GO
GRANT VIEW DEFINITION ON [StaticTrackersForTrackerID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [StaticTrackersForTrackerID] TO [db_dml]
GO
