/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderGetAllByOfficerID]  
  
@OfficerID INT  
  
AS  
  
BEGIN  
  
 SET NOCOUNT ON;  
  
 SELECT   
  o.OffenderID,   
  ISNULL(o.LastName, '')   + ', ' +  
  
  ISNULL(o.FirstName, '') AS 'OffenderName',
  o.AgencyID,
  oo.OfficerID,
 ISNULL(offi.LastName, '')   + ', ' +  
  ISNULL(offi.MiddleName, '') + ' ' +  
  ISNULL(offi.FirstName, '') AS 'OfficerName',		
  a.Agency
 FROM   
  Offender_Officer oo  
  JOIN Offender o ON oo.OffenderID = o.OffenderID  
  JOIN Agency a on a.AgencyID= o.AgencyID
  JOIN Officer offi ON offi.officerID = oo.Officerid 		
 WHERE   
  ( @OfficerID<0  OR(oo.OfficerID = @OfficerID))  
  AND   
  (o.Deleted = 0)  
 ORDER BY 'OffenderName'
END


GO
GRANT EXECUTE ON [OffenderGetAllByOfficerID] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [OffenderGetAllByOfficerID] TO [db_object_def_viewers]
GO
