/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [IsAssignedToOtherUser]  
  
 @IsAssigned BIT OUTPUT,  
 @AlarmID     INT  ,
 @UserID     INT  
   
AS
SELECT TOP 1  @IsAssigned=1  
FROM AlarmAssignment  
WHERE AlarmID = @AlarmID 
and AssignedByID <> @UserID
ORDER BY AlarmAssignmentStatusID DESC  
  
IF @IsAssigned IS NULL   
 SET @IsAssigned =0

GO
GRANT EXECUTE ON [IsAssignedToOtherUser] TO [db_dml]
GO
