/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportRecentDeActivations]
@offset int
AS
--Set @offset = 1440
Select

ag.Agency
,ag.SFDCAccount As 'SFDCAccount#'
,dp.Propertyvalue As 'Device Serial'
,dp1.Propertyvalue As 'ICCID'
,nop.[name] AS 'Carrier'
,d.MostLikelyPhoneNumber As 'DevicePhone'
,DateAdd(mi,-360,ota.ActivateDate)As 'ActivateDate'
,DateAdd(mi,-360,ota.deActivateDate)As 'deActivateDate'
,(Case WHEN tr.Trackerid IS NULL THEN 'NO'
  WHEN tr.Trackerid is NOT NULL AND tr.removedDate IS NULL THEN 'YES'
  ELSE 'NO'END)AS 'RMA'
 From Offendertrackeractivation ota
JOIN Offender o ON o.Offenderid = ota.Offenderid
JOIN Agency ag ON ag.agencyid = o.agencyid
JOIN Gateway.dbo.devices d ON d.deviceid = ota.trackerid
LEFT JOIN Gateway.dbo.deviceproperties dp ON dp.deviceid = ota.trackerid and dp.propertyid = '8012'
LEFT JOIN Gateway.dbo.deviceproperties dp1 ON dp1.deviceid = ota.trackerid and dp1.propertyid = '8204' 
LEFT JOIN Gateway.dbo.DeviceProperties dp3 ON d.DeviceID = dp3.DeviceID AND dp3.PropertyID = '8202'
LEFT JOIN Gateway.dbo.NetworkOperators nop ON nop.MCC+nop.MNC = LEFT(dp3.Propertyvalue,6)
LEFT JOIN TrackerRma tr ON tr.Trackerid = ota.Trackerid
Where ota.deactivatedate >= DateADD(mi,-@Offset,GetDate())

Order BY 'deActivateDate'

GO
GRANT EXECUTE ON [ReportRecentDeActivations] TO [db_dml]
GO
