/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoRuleGetAllAvailable]

	@AgencyID	INT,
	@OffenderID	INT,
	@RoleID		INT

AS

	IF @RoleID = 2
	BEGIN
		SELECT	g.GeoRuleID,
				g.GeoRuleName,
				0 AS 'Selected',
				g.StatusID,
				gs.GeoRuleStatusName,
				g.FileID,
				g.UpdateInProgress
		FROM	GeoRule g
		Inner join GeoruleStatus gs on gs.GeoruleStatusID= g.StatusID
		INNER JOIN GeoRule_Agency ga ON g.GeoRuleID = ga.GeoRuleID
		WHERE	ga.AgencyID = @AgencyID AND
				g.Deleted = 0 AND
				g.GeoRuleID NOT IN (
				SELECT	GeoRuleID
				FROM	GeoRule_Offender)
		UNION
		SELECT	g.GeoRuleID,
				g.GeoRuleName,
				1 AS 'Selected',
				g.StatusID,
				gs.GeoRuleStatusName,
				g.FileID,
				g.UpdateInProgress
		FROM	GeoRule g
		INNER JOIN GeoRule_Offender geo_o ON g.GeoRuleID = geo_o.GeoRuleID
		Inner join GeoruleStatus gs on gs.GeoruleStatusID= g.StatusID
		WHERE	geo_o.OffenderID = @OffenderID AND 
				g.Deleted = 0
		ORDER BY 'Selected' DESC, GeoRuleName
	END
	ELSE
	BEGIN
		IF @AgencyID = 0
		BEGIN
			SELECT	g.GeoRuleID,
					g.GeoRuleName,
					0 AS 'Selected',
					g.StatusID,
					gs.GeoRuleStatusName,
					g.FileID,
					g.UpdateInProgress
			FROM	GeoRule g
			Inner join GeoruleStatus gs on gs.GeoruleStatusID= g.StatusID

			WHERE	g.Deleted = 0 AND
					g.GeoRuleID NOT IN (
					SELECT	GeoRuleID
					FROM	GeoRule_Offender)
			UNION
			SELECT	g.GeoRuleID,
					g.GeoRuleName,
					1 AS 'Selected',
					g.StatusID,
					gs.GeoRuleStatusName,
					g.FileID,
					g.UpdateInProgress
			FROM	GeoRule g
			INNER JOIN GeoRule_Offender geo_o ON g.GeoRuleID = geo_o.GeoRuleID
			Inner join GeoruleStatus gs on gs.GeoruleStatusID= g.StatusID
					
			WHERE	geo_o.OffenderID = @OffenderID AND 
					g.Deleted = 0 
			ORDER BY 'Selected' DESC, GeoRuleName
		END
		ELSE
		BEGIN
			SELECT	g.GeoRuleID,
					g.GeoRuleName,
					0 AS 'Selected',
					g.StatusID,
					gs.GeoRuleStatusName,
					g.FileID,
					g.UpdateInProgress
			FROM	GeoRule g
			Inner join GeoruleStatus gs on gs.GeoruleStatusID= g.StatusID

			INNER JOIN GeoRule_Agency ga ON g.GeoRuleID = ga.GeoRuleID
			WHERE	ga.AgencyID = @AgencyID AND
					g.Deleted = 0 AND
					g.GeoRuleID NOT IN (
					SELECT	GeoRuleID
					FROM	GeoRule_Offender)
			UNION
			SELECT	g.GeoRuleID,
					g.GeoRuleName,
					1 AS 'Selected',
					g.StatusID,
					gs.GeoRuleStatusName,
					g.FileID,
					g.UpdateInProgress
			FROM	GeoRule g
			INNER JOIN GeoRule_Offender geo_o ON g.GeoRuleID = geo_o.GeoRuleID
			Inner join GeoruleStatus gs on gs.GeoruleStatusID= g.StatusID

			WHERE	geo_o.OffenderID = @OffenderID AND
					g.Deleted = 0 
			ORDER BY 'Selected' DESC, GeoRuleName
		END
	END
GO
GRANT EXECUTE ON [GeoRuleGetAllAvailable] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [GeoRuleGetAllAvailable] TO [db_object_def_viewers]
GO
