/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmGetRecientAlarms]
	@LastQueryTime bigint

AS
BEGIN
	SET NOCOUNT ON;

	SELECT [AlarmID]
      ,[OffenderID]
      ,[TrackerID]
      ,[EventTypeID]
      ,[EventTime]
      ,[EventDisplayTime]
      ,[AlarmTypeID]
      ,ROUND([Latitude],5) AS 'Latitude'
      ,ROUND([Longitude],5) AS 'Longitude'
      ,[Address]
      ,[EventParameter]
      ,[CreatedDate]
	FROM Alarm
	WHERE EventTime > @LastQueryTime
END
GO
GRANT VIEW DEFINITION ON [AlarmGetRecientAlarms] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [AlarmGetRecientAlarms] TO [db_dml]
GO
