/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderGetAllRiskLevels]
AS
BEGIN

	SET NOCOUNT ON;

	SELECT RiskLevelID, RiskLevel
	FROM OffenderRiskLevel
	ORDER BY RiskPriority DESC
END
GO
GRANT EXECUTE ON [OffenderGetAllRiskLevels] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [OffenderGetAllRiskLevels] TO [db_object_def_viewers]
GO
