/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [DaylightProgressAdd]

	@DaylightUpdateID		INT OUTPUT,
	@TrackerID		INT,
	@OffenderID     INT
	

AS
	
	INSERT INTO DaylightUpdateProgress
	(TrackerID, OffenderID)
	VALUES
	(@TrackerID, @OffenderID)
	
	SET @DaylightUpdateID = @@IDENTITY
	

GO
GRANT EXECUTE ON [DaylightProgressAdd] TO [db_dml]
GO
