/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoRule_OffenderGetByOffenderID]
    @iOffenderID INT
AS 
    SELECT GeoRuleID,ZoneID
    FROM GeoRule_Offender
    WHERE OffenderID=@iOffenderID

GO
GRANT EXECUTE ON [GeoRule_OffenderGetByOffenderID] TO [db_dml]
GO
