/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TrackerActionAddActiveSiren]
(@TrackerActionID bigint, @TrackerID int, @OffenderID int)
--WITH 
--EXECUTE AS CALLER
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO ActiveSirens 
	(TrackerActionID, TrackerID, OffenderID)
	VALUES
	(@TrackerActionID, @TrackerID, @OffenderID)
END

GO
GRANT EXECUTE ON [TrackerActionAddActiveSiren] TO [db_dml]
GO
