/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [DistributorEmployeeUpdate]
	@DistributorEmployeeID		INT,
	@DistributorID		INT,
	@Title			NVARCHAR(50),
	@Department     NVARCHAR(50),
	@SalutationID	INT,
	@FirstName		NVARCHAR(50),
	@MiddleName		NVARCHAR(50),
	@LastName		NVARCHAR(50),
	@SuffixID		INT,
	@StreetLine1	NVARCHAR(50),
	@StreetLine2	NVARCHAR(50),
	@City			NVARCHAR(50),
	@StateID		INT,
	@PostalCode		NVARCHAR(25),
	@CountryID		INT,
	@DayPhone		NVARCHAR(25),
	@ExtDayPhone		NVARCHAR(25),
	@EveningPhone	NVARCHAR(25),
	@ExtEveningPhone	NVARCHAR(25),
	@MobilePhone	NVARCHAR(25),
	@Pager			NVARCHAR(25),
	@Fax			NVARCHAR(25),
	@EmailAddress	NVARCHAR(50),
	@EmailAddress2	NVARCHAR(50),
	@ModifiedByID	INT
AS
	UPDATE	DistributorEmployee
	SET		DistributorID = @DistributorID, 
			Title = @Title,
			Department = @Department,
			SalutationID = @SalutationID,
			FirstName = @FirstName,
			MiddleName = @MiddleName,
			LastName = @LastName,
			SuffixID = @SuffixID,
			StreetLine1 = @StreetLine1,
			StreetLine2 = @StreetLine2,
			City = @City,
			StateID = @StateID,
			PostalCode = @PostalCode,			
			CountryID = @CountryID,
			DayPhone = @DayPhone,
			ExtDayPhone = @ExtDayPhone,
			EveningPhone = @EveningPhone,
			ExtEveningPhone = @ExtEveningPhone,
			MobilePhone = @MobilePhone,
			Pager = @Pager,
			Fax = @Fax,
			EmailAddress = @EmailAddress,
			EmailAddress2 = @EmailAddress2,
			ModifiedDate = GETDATE(),
			ModifiedByID = @ModifiedByID
	WHERE	DistributorEmployeeID = @DistributorEmployeeID
GO
GRANT VIEW DEFINITION ON [DistributorEmployeeUpdate] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [DistributorEmployeeUpdate] TO [db_dml]
GO
