/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderAcquaintanceGetAllNames]

AS
BEGIN
	SET NOCOUNT ON;

	SELECT OffenderAcquaintanceID,
		ISNULL(FirstName + ' ', '') + 
		ISNULL(MiddleName + ' ', '') +
		ISNULL(LastName + ' ', '') AS 'AcquaintanceName'
	FROM OffenderAcquaintance
	
END
GO
GRANT VIEW DEFINITION ON [OffenderAcquaintanceGetAllNames] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OffenderAcquaintanceGetAllNames] TO [db_dml]
GO
