/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [EArrestServiceAdd] 
	@PricePerBeacon FLOAT, 
	@BeaconLimit INT, 
	@ClassicBillingServiceID INT, 
	@Rate FLOAT,
	@NewID INT OUTPUT
AS
--Adds new record to EArrestService table.
SET NOCOUNT ON;
--Check for outstanding transactions
IF @@TRANCOUNT > 0
	BEGIN
		ROLLBACK TRANSACTION
	END;

BEGIN TRANSACTION;
BEGIN TRY
	INSERT INTO dbo.EArrestService(
	PricePerBeacon,
	BeaconLimit,
	ClassicBillingServiceID,
	Rate)
	VALUES(
	@PricePerBeacon,
	@BeaconLimit,
	@ClassicBillingServiceID,
	@Rate);
END TRY
BEGIN CATCH
	--Catch and return error.
    SELECT 
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_SEVERITY() AS ErrorSeverity,
        ERROR_STATE() as ErrorState,
        ERROR_PROCEDURE() as ErrorProcedure,
        ERROR_LINE() as ErrorLine,
        ERROR_MESSAGE() as ErrorMessage;
	--Rollback outstanding transactions.
	IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION
		END;
END CATCH;

IF @@TRANCOUNT > 0
	BEGIN
		COMMIT TRANSACTION
	END;
SET @NewID = (SELECT SCOPE_IDENTITY());

GO
GRANT EXECUTE ON [EArrestServiceAdd] TO [db_dml]
GO
