/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportActiveInterventionAgencySummary]




@Agencyid int
--
--Set @Officerid = 4616
--Set @Agencyid = 830
AS
Select rpt.* INTO 
#tmplast24events
From rprteventsbucket1 rpt
WHERE dbo.fnUtcToLocal(@Agencyid,rpt.EventDateTime) BETWEEN DATEADD(hh,-24,CONVERT(DATETIME, FLOOR(CONVERT(FLOAT,dbo.fnUtcToLocal(@Agencyid,GETDATE())))))
AND CONVERT(DATETIME, FLOOR(CONVERT(FLOAT,dbo.fnUtcToLocal(@Agencyid,GETDATE()))))
ANd rpt.alarmtype > 1
AND rpt.Agencyid = @Agencyid


 
Select
ofi.LastNAme+', '+ofi.firstname AS OfficerName
,SUM(Case When tmp.eventid IS NULL THEN 0 Else 1 END) AS AlarmTotal

From Offender o
Left JOIN #tmplast24events tmp ON tmp.Offenderid = o.Offenderid
JOIN Offender_Officer oo ON oo.Offenderid = o.Offenderid
JOIN Officer ofi on ofi.Officerid = oo.officerid
Where o.deleted = 0 AND o.agencyid = @Agencyid
GROUP BY ofi.LastNAme+', '+ofi.firstname
Order BY ofi.LastNAme+', '+ofi.firstname

drop table #tmplast24events

GO
GRANT EXECUTE ON [ReportActiveInterventionAgencySummary] TO [db_dml]
GO
