/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TrackerActionGetAllByDistEmpUserID]   
 @DistributorID int = 0  
AS  
BEGIN  
 SET NOCOUNT ON;  
   SELECT DISTINCT  
  [TrackerActionID],  
  [TrackerActionTypeID],  
  ta.[TrackerID],  
  [TrackerActionDateTime],  
  ta.[CreatedByID],  
  t.AgencyID   
FROM   
  distributorEmployee de
  inner join agency a on a.distributorid = de.distributorid
  INNER JOIN Tracker t ON  t.Deleted = 0  and   t.AgencyID=a.agencyid
  inner join  [TrackerAction] ta on  t.TrackerID = ta.TrackerID 
 
 WHERE  
  de.userid= @DistributorID

 ORDER BY [TrackerActionDateTime]  
END

GO
GRANT EXECUTE ON [TrackerActionGetAllByDistEmpUserID] TO [db_dml]
GO
