/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TrackerRmaGetByTrackerID] 
	@TrackerID int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		rma.[RmaID],
		rma.[TrackerID],
		rma.[CreatedDate],
		rma.[CreatedByID],
		rma.[RemovedDate],
		rma.[RemovedByID]
	FROM 
		[TrackerRma] rma
	WHERE 
		rma.[RmaID] = (
			SELECT TOP (1)
				t.[RmaID]
			FROM
				[Tracker] t
			WHERE
				t.TrackerID = @TrackerID
			ORDER BY
				t.CreatedDate DESC
		)
END
GO
GRANT VIEW DEFINITION ON [TrackerRmaGetByTrackerID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [TrackerRmaGetByTrackerID] TO [db_dml]
GO
