/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderServicesGetAll] 
AS  
  
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;  
  
SELECT OffenderID, ServiceID, DateAdded, LastModifyDate
FROM offenderservices
  
  
    
GO
GRANT EXECUTE ON [OffenderServicesGetAll] TO [db_dml]
GO
