/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoRuleGetRecentChange]
	@LastQueryTime datetime
AS
BEGIN
	SET NOCOUNT ON;

	SELECT gr.GeoRuleID,
		   gr.GeoRuleName,
		   gr.CreatedDate,
		   gr.ModifiedDate,
		   o.FirstName + ' ' + o.LastName AS Offender,
		   so.FirstName + ' ' + so.LastName AS Officer,
		   a.Agency,
		   u.UserName
	FROM GeoRule gr
	LEFT JOIN GeoRule_Offender gr_o ON gr_o.GeoRuleID = gr.GeoRuleID
	LEFT JOIN Offender o ON gr_o.OffenderID = o.OffenderID
	LEFT JOIN Offender_Officer oo ON oo.OffenderID = o.OffenderID
	LEFT JOIN Officer so ON oo.OfficerID = so.OfficerID
	LEFT JOIN GeoRule_Agency ga ON ga.GeoRuleID = gr.GeoRuleID
	LEFT JOIN Agency a ON a.AgencyID = ga.AgencyID
	LEFT JOIN [User] u ON u.UserID = gr.CreatedByID
	WHERE (gr.CreatedDate > @LastQueryTime) or
		  (gr.ModifiedDate > @LastQueryTime)
END


GO
GRANT VIEW DEFINITION ON [GeoRuleGetRecentChange] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [GeoRuleGetRecentChange] TO [db_dml]
GO
