/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportEarrestBilling]

@StartDate Datetime, 
@EndDate DateTime
--
--Set @StartDate = '2009-03-01'
--SET @EndDate = '2009-04-01'
AS
Select
ag.Agency
--,ofi.FirstNAme+' '+ofi.LastName
,o.FirstNAme+' '+o.LastName AS 'OffenderName'
,DATEADD(mi,-360,ebs.StartDate) AS 'Earrest Start'
,DATEADD(mi,-360,ebs.EndDate)AS 'Earrest End'
,(CASE WHEN ebs.enddate IS NULL AND DATEADD(mi,-360,ebs.StartDate) > @StartDate 
			THEN DATEDIFF(dd,DATEADD(mi,-360,ebs.StartDate),@EndDate)
 WHEN DATEADD(mi,-360,ebs.StartDate) < @StartDate AND ebs.EndDate IS NULL 
			THEN DATEDIFF(dd,@StartDate,@EndDate)
 WHEN ebs.enddate IS NOT NULL AND DATEADD(mi,-360,ebs.StartDate) > @StartDate 
			THEN DATEDIFF(dd,DATEADD(mi,-360,ebs.StartDate),DATEADD(mi,-360,ebs.EndDate))
	ELSE DATEDIFF(dd,@StartDate,DATEADD(mi,-360,ebs.EndDate))END) AS 'Days on Earrest' 

From EarrestBillingStatus ebs
JOIN Offender o ON o.Offenderid = ebs.Offenderid
JOIN Offender_Officer oo ON oo.Offenderid = o.Offenderid
JOIN agency ag ON ag.Agencyid = o.Agencyid
JOIN Officer ofi ON ofi.Officerid = oo.Officerid
WHERE DATEADD(mi,-360,ebs.StartDate) < @EndDate 
AND 
(DATEADD(mi,-360,ebs.EndDate) < @EndDate OR ebs.EndDate IS NULL)

Order BY ag.Agency,'OffenderName'
GO
GRANT EXECUTE ON [ReportEarrestBilling] TO [db_dml]
GO
