/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [spReportOTDAssignmentHistory]

AS
BEGIN
	SET NOCOUNT ON;

SELECT
		   --d.[Name]
		  dp5.PropertyValue AS 'Gateway Serial Number'
      ,nop.[name] AS 'SIM Provider'
		  ,dp2.PropertyValue AS 'APN'
		  ,dp6.PropertyValue AS 'SIMPhoneNumber'
		  ,d.deviceid
      ,d.uniqueid As 'IMEI'
--		  ,dp1.PropertyValue AS 'IMEI'
		  ,dp4.PropertyValue AS 'ICCID'
		  ,LEFT(dp3.PropertyValue,6) AS 'IMSI'
		  ,dp8.propertyvalue AS 'Firmware'
      ,gateway.dbo.HexToBigInt(CONVERT(nvarchar,dp9.propertyvalue)) AS 'Tracking Duration'
      ,dp7.Propertyvalue AS 'Hardware Version'
		,a.SFDCAccount AS 'SFDCACCT#'      
		,a.Agency
      ,(CASE WHEN t1.Deleted = 1
				  THEN 'Un-assigned'
          WHEN t1.deleted IS NULL 
          THEN 'Un-assigned'
          ELSE 'Assigned'
        END) AS 'AgencyAssignmentStatus'
      ,(CASE 
          WHEN t1.CreatedDate IS NULL Then 'N/A' 
          ELSE CONVERT(char(25),DATEADD(mi,-360,t1.CreatedDate),101)
        END) AS 'AgencyAssignmentDate'
		  ,(CASE
					WHEN t1.Deleted = 1
				  THEN CONVERT(char(25),DateADD(mi,-360,t1.ModifiedDate),101)
          ELSE ''
				END )AS 'Un-AssignmentDate'	
		  ,(CASE
			    WHEN ta.trackerassignmenttypeid = 1
				  THEN 'Assigned'
			    ELSE 'Un-Assigned'
	      END) AS 'AssignmentStatus' 
      ,(CASE 
          WHEN ta.AssignmentDate Is NULL Then 'N/A' 
          ELSE CONVERT(char(25),DATEADD(mi,-360,ta.AssignmentDate),101)
        END) AS 'AssignmentDate'
      ,(CASE 
          WHEN ota.deactivatedate IS NULL AND ota.trackeractivationid IS NOT NULL 
          THEN 'Operational'
          ELSE 'Idle' 
        END)AS 'Activation Status'
      ,(CASE 
          WHEN ota.ActivateDate IS NULL 
          THEN 'N/A'ELSE CONVERT(char(25),DATEADD(mi,-360,ota.activatedate),101)
        END)AS 'Activate Date'
	    ,(CASE 
	        WHEN ota.activatedate is NULL And ota.deactivatedate IS NULL 
	        THEN 'N/A'
            WHEN ota.activatedate IS NOT NULL And ota.deactivatedate IS NULL 
            THEN 'Active'
            ELSE CONVERT(char(25),DATEADD(mi,-360,ota.deactivatedate),101) 
        END)AS 'Deactivate Date'
      ,(CASE 
          WHEN t1.isdemo = 1 
          THEN 'Demo'
            WHEN t1.isdemo = 0 
            THEN 'PROD'
            ELSE 'N/A' 
        END)AS 'Device Type'
       ,(CASE When d.LastEventTime !=0 Then CONVERT(char(25),DATEADD(mi,-420,Trackerpal.dbo.Convertlongtodate(d.LastEventTime)),101)
			  ELSE 'N/A' END)As 'LastEvent'
        ,(Case WHEN tra.Rmaid IS NOT NULL THEN 'True' Else 'False' END)AS TrackerRMA 
       ,(CASE When tra.CreatedDate IS Not NULL Then CONVERT(char(25),DATEADD(mi,-420,tra.CreatedDate),101)
			  ELSE 'N/A' END)As 'RMA Date'
			,(CASE When st.State IS NULL THEN 'N/A' ELSE st.State END)AS 'State' 
      
FROM gateway.dbo.devices d WITH (NoLock)
LEFT JOIN (SELECT TrackerID, Max(TrackerActivationID) AS ActivationID FROM OffenderTrackerActivation WITH (NOLOCK) GROUP BY TrackerID) AS ota1 ON ota1.TrackerID = d.deviceID
LEFT JOIN (SELECT TrackerID, Max(TrackerAssignmentID) AS AssignmentID FROM TrackerAssignment WITH (NOLOCK) GROUP BY TrackerID) AS ta1 ON ta1.TrackerID = d.deviceid
LEFT JOIN (SELECT TrackerID, Max(TrackerUniqueID) As uniqueid FROM Tracker WITH (NOLOCK) Group BY Trackerid) AS t ON t.trackerid = d.deviceid
JOIN Gateway.dbo.DeviceProperties dp1 ON d.DeviceID = dp1.DeviceID AND dp1.PropertyID = '8205'
JOIN Gateway.dbo.DeviceProperties dp2 ON d.DeviceID = dp2.DeviceID AND dp2.PropertyID = '8210'
JOIN Gateway.dbo.DeviceProperties dp3 ON d.DeviceID = dp3.DeviceID AND dp3.PropertyID = '8202'
JOIN Gateway.dbo.DeviceProperties dp6 ON d.DeviceID = dp6.DeviceID AND dp6.PropertyID = '8203'
JOIN Gateway.dbo.DeviceProperties dp4 ON d.DeviceID = dp4.DeviceID AND dp4.PropertyID = '8204'
LEFT JOIN Gateway.dbo.DeviceProperties dp5 ON d.DeviceID = dp5.DeviceID AND dp5.PropertyID = '8012'
JOIN Gateway.dbo.DeviceProperties dp7 ON d.DeviceID = dp7.DeviceID AND dp7.PropertyID = '8010'
JOIN Gateway.dbo.DeviceProperties dp8 ON d.DeviceID = dp8.DeviceID AND dp8.PropertyID = '8016'
JOIN Gateway.dbo.deviceproperties dp9 ON dp9.deviceid = d.deviceid AND dp9.propertyid = '8020'
LEFT JOIN Gateway.dbo.NetworkOperators nop ON nop.MCC+nop.MNC = LEFT(dp3.Propertyvalue,6)
LEFT JOIN OffenderTrackerActivation ota ON ota.TrackerActivationID = ota1.ActivationID
LEFT JOIN TrackerAssignment ta ON ta.TrackerAssignmentID = ta1.AssignmentID
LEFT JOIN tracker t1 on t.uniqueid = t1.trackeruniqueid
LEFT JOIN Agency a ON t1.AgencyID = a.AgencyID
LEFT JOIN Trackerrma tra ON tra.trackerid = t1.trackerid AND tra.RemovedDate IS NULL
LEFT JOIN State st ON st.stateid = a.stateid


ORDER BY a.agency

END





GO
GRANT EXECUTE ON [spReportOTDAssignmentHistory] TO [db_dml]
GO
