/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mAlarmTypeProtocolActionRecepientsAll]

	

AS
	select g.AlarmProtocolActionRecipientID, g.AlarmProtocolActionRecipient, g.RoleID, g.displayorder
	from AlarmProtocolActionRecipient  g 
GO
GRANT EXECUTE ON [mAlarmTypeProtocolActionRecepientsAll] TO [db_dml]
GO
