/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OperatorUpdate]

	@OperatorID			INT,
	@Title				NVARCHAR(50) = null,
	@Department			NVARCHAR(50) = null,
	@SalutationID		INT = null,
	@FirstName			NVARCHAR(50),
	@MiddleName			NVARCHAR(50) = null,
	@LastName			NVARCHAR(50),
	@SuffixID			INT = null,
	@StreetLine1		NVARCHAR(50),
	@StreetLine2		NVARCHAR(50) = null,
	@City				NVARCHAR(50) = null,
	@StateID			INT,
	@PostalCode			NVARCHAR(25),
	@CountryID			INT,
	@DayPhone			NVARCHAR(25),
	@EveningPhone		NVARCHAR(25) = null,
	@MobilePhone		NVARCHAR(25) = null,
	@Pager				NVARCHAR(25) = null,
	@Fax				NVARCHAR(25) = null,
	@EmailAddress1		NVARCHAR(50),
	@EmailAddress2		NVARCHAR(50) = null,
	@ModifiedByID		INT,
	@ModifiedDate		DATETIME = null OUTPUT,
	@ExtDayPhone		NVARCHAR(20) = null,
	@ExtEveningPhone	NVARCHAR(20) = null

AS

	SET @ModifiedDate = GETDATE()

	UPDATE	Operator
	SET		Title = @Title,
			Department = @Department,
			SalutationID = @SalutationID,
			FirstName = @FirstName,
			MiddleName = @MiddleName,
			LastName = @LastName,
			SuffixID = @SuffixID,
			StreetLine1 = @StreetLine1,
			StreetLine2 = @StreetLine2,
			City = @City,
			StateID = @StateID,
			PostalCode = @PostalCode,
			CountryID = @CountryID,
			DayPhone = @DayPhone,
			EveningPhone = @EveningPhone,
			MobilePhone = @MobilePhone,
			Pager = @Pager,
			Fax = @Fax,
			EmailAddress1 = @EmailAddress1,
			EmailAddress2 = @EmailAddress2,
			ModifiedDate = @ModifiedDate,
			ModifiedByID = @ModifiedByID,
			ExtDayPhone  =	@ExtDayPhone,
			ExtEveningPhone = @ExtEveningPhone
	WHERE	OperatorID = @OperatorID
	
GO
GRANT VIEW DEFINITION ON [OperatorUpdate] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OperatorUpdate] TO [db_dml]
GO
