/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [spalarmsuspentions]

@confirmationnumber BIGINT
AS
Select 


ag.Agency
,tz.[Name] As 'Agency TimeZone'
,ofi.FirstNAme+' '+ofi.LastNAme As 'OfficerName'
,ofi2.FirstNAme+' '+ofi2.LastName AS 'Requestor'
,o.FirstNAme+' '+o.LastName As 'Offender Name'
,ape.AlarmName
--,StartTime
--,EndTime
,DATEADD(mi,tz.DaylightUTCOFFSET,StartTime)AS 'Agency Start Time' 
,DATEADD(mi,tz.DaylightUTCOFFSET,EndTime)AS 'Agency End Time' 
,DATEADD(mi,tz.DaylightUTCOFFSET,aps.CreatedDate)AS 'Supension Creation Time'
,DATEADD(mi,-360,StartTime)AS 'Mountain Start Time' 
,DATEADD(mi,-360,EndTime)AS 'Mountain End Time' 
,aps.Confirmationnumber

from Alarmsuspended aps
Join Agency ag ON ag.agencyid = aps.agencyid
JOIN Officer ofi ON ofi.Officerid = aps.Officerid
JOIN Offender o ON o.Offenderid = aps.Offenderid
JOIN Officer ofi2 On ofi2.Officerid = aps.RequestingOfficerID
Join Timezone tz ON tz.timezoneid = ag.timezoneid
Join AlarmprotocolEvent ape ON ape.GatewayEventid = aps.AlarmProtocolEventID
Where aps.Confirmationnumber = @confirmationnumber

GO
GRANT EXECUTE ON [spalarmsuspentions] TO [db_dml]
GO
