/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmNoteGetByAlarmID]

	@AlarmID	INT

AS

	SELECT	a.AlarmNoteID,
			a.Note,
			u.UserName,
			a.CreatedDate
	FROM	AlarmNote a
	LEFT JOIN [User] u ON a.CreatedByID = u.UserID
	WHERE	a.AlarmID = @AlarmID
	ORDER BY a.CreatedDate DESC
GO
GRANT VIEW DEFINITION ON [AlarmNoteGetByAlarmID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [AlarmNoteGetByAlarmID] TO [db_dml]
GO
