/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [StaticAlarmAdd]
	@AlarmID			bigint OUTPUT,
	@DeviceID			int,
	@OffenderID			int,
	@AlarmTypeID		int,
	@EventTypeID		int,
	@EventDisplayTime	datetime,
	@EventTime			bigint,
	@Latitude			float,
	@Longitude			float,
	@EventParameter		bigint,
	@GeoRuleName		varchar(200) = NULL,
	@ReceivedTime       datetime,

	@ActivateDate		datetime = NULL, 
	@DeactivateDate		datetime = NULL, 
	@EventName			varchar(200) = NULL, 
	@OffenderName		varchar(200) = NULL, 
	@RiskLevelID		int = NULL,
	@SO					bit = NULL,
	@OPR				bit = NULL,
	@HasProtocol        bit OUTPUT,
	@IsAnExeption		bit
AS
	
	IF @AlarmTypeID > 1
	BEGIN
		DECLARE @latency int
		
		SET @latency = (DATEDIFF(ss,(@EventDisplayTime ),(@ReceivedTime)))
		IF (@latency < 0)
		BEGIN
			SET @latency = 0
		END

		INSERT INTO Alarm
			(OffenderID, TrackerID, EventTypeID, EventTime, ReceivedTime,EventDisplayTime, 
			 AlarmTypeID, Latitude, Longitude, EventParameter, Latency )
		VALUES
			(@OffenderID, @DeviceID, @EventTypeID, @EventTime, @ReceivedTime, @EventDisplayTime, 
			 @AlarmTypeID, @Latitude, @Longitude, @EventParameter, @latency)

		SET @AlarmID = (
			SELECT TOP 1 AlarmID 
			FROM Alarm 
			WHERE TrackerID = @DeviceID AND EventTime = @EventTime AND EventTypeID = @EventTypeID
		)

		SET @HasProtocol = (trackerPAL.dbo.[fnHasAlarmProtocols](@AlarmID,@OffenderID))

		if(@HasProtocol = 1 or @IsAnExeption=1 )
		Begin
			EXEC rptInsertAlarmRecord 
				@AlarmID,@OffenderID,@DeviceID,@EventTypeID,@ReceivedTime,@AlarmTypeID,@Latency,
				@EventDisplayTime,@EventName,@OffenderName,@GeoRuleName,@RiskLevelID,@SO,@OPR,@EventTime
		End

	END
	ELSE
	BEGIN
		RAISERROR( 'The event is not an alarm.', 14, 1 )
	END
GO
GRANT VIEW DEFINITION ON [StaticAlarmAdd] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [StaticAlarmAdd] TO [db_dml]
GO
