/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderGetBillingStatus]
	  
@OffenderID INT  
  
AS  
  
 SET NOCOUNT ON  
  
 SELECT ebs.ID,ebs.OffenderID,ebs.BillingStatus,ebs.StartDate               
 FROM (Select OffenderID, MAX(ID) As lastid From EArrestBillingStatus Group BY Offenderid) ebs1
 JOIN  EArrestBillingStatus ebs ON ebs.id = ebs1.lastid      
 WHERE ebs.OffenderID=@Offenderid

GO
GRANT EXECUTE ON [OffenderGetBillingStatus] TO [db_dml]
GO
