/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [spOffendersGetAllbyAgencyid]
@agencyid int
As 
Select 
o.Offenderid
,o.FirstName+' '+o.LastName as 'OffenderName'
From Offender o
Where agencyid = @agencyid
ORDER BY o.FirstName


GO
GRANT EXECUTE ON [spOffendersGetAllbyAgencyid] TO [db_dml]
GO
