/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderGetAllByTAMUserId]   
 @UserID INT  
AS  
BEGIN  
  
SET NOCOUNT ON;  
SELECT o.OffenderID,
	ISNULL(o.LastName + ', ', '') + 
	ISNULL(o.FirstName, '') 
	AS 'OffenderName'   ,
 o.AgencyID,
  oo.OfficerID,
 ISNULL(offi.LastName, '')   + ', ' +  
  ISNULL(offi.MiddleName, '') + ' ' +  
  ISNULL(offi.FirstName, '') AS 'OfficerName',		
  a.Agency 

FROM Offender o  (NOLOCK)    
INNER JOIN agency a on o.AgencyID = a.AgencyID              
INNER JOIN distributor d on d.DistributorID=a.DistributorID  
JOIN  Offender_Officer oo  on oo.OffenderId = o.Offenderid
JOIN Officer offi ON offi.officerID = oo.Officerid 	  
WHERE o.Deleted = 0 AND o.Victim = 0 AND d.TamID=@UserID    ORDER BY o.LastName, o.FirstName   
     
END  
  
GO
GRANT EXECUTE ON [OffenderGetAllByTAMUserId] TO [db_dml]
GO
