/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mProtocolActionBySetID]

	@ProtocolSetID	INT

AS
	select g.AlarmProtocolActionID, g.AlarmProtocolEventID, g.Priority, g.CreatedByID,g.[Type]
			
	from AlarmProtocolAction  g 
	WHERE g.AlarmProtocolSetID=@ProtocolSetID
GO
GRANT EXECUTE ON [mProtocolActionBySetID] TO [db_dml]
GO
