/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:26 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmAssignmentGetPendingUnacknowledgedAlarms]

AS
BEGIN
	SET NOCOUNT ON;

	SELECT *
	FROM AlarmAssignment
	WHERE AlarmAssignmentStatusID = 4 AND
	AlarmAssignment.AlarmID NOT IN (select AlarmID from AlarmAcknowledgement)
END
GO
GRANT EXECUTE ON [AlarmAssignmentGetPendingUnacknowledgedAlarms] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [AlarmAssignmentGetPendingUnacknowledgedAlarms] TO [db_object_def_viewers]
GO
