/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmProtocolCopy]


@newAgencyid int, @Alarmprotocolsetid int

--SET @oldagencyid = 473
--SET @NewAgencyid = 1038
--SET @Alarmprotocolsetid = 2354
--SET @oldagencyid = 30
--SET @NewAgencyid = 841
--SET @Alarmprotocolsetid = 50



AS

INSERT INTO [TrackerPal].[dbo].[AlarmProtocolSet]
           ([AlarmProtocolSetName]
           ,[AlarmProtocolSetTypeID]
           ,[AgencyID]
           ,[OfficerID]
           ,[OffenderID]
           ,[CreatedByID]
           ,[CreatedDate]
           ,[ModifiedByID]
           ,[ModifiedDate])
SELECT 
		      [AlarmProtocolSetName]
           ,[AlarmProtocolSetTypeID]
           ,@newagencyid
           ,[OfficerID]
           ,[OffenderID]
           ,55
           ,GetDate()
           ,NULL
           ,NULL
From Alarmprotocolset 
Where AlarmProtocolSetID = @Alarmprotocolsetid

DECLARE @newprotocolsetid int

SELECT @newprotocolsetid = (Select TOP 1 Alarmprotocolsetid From alarmprotocolset where createdbyid = 55 ORDER BY createddate desc)

INSERT INTO [TrackerPal].[dbo].[AlarmProtocolAction]
           ([AlarmProtocolSetID]
           ,[AlarmProtocolEventID]
           ,[Type]
           ,[Priority]
           ,[From]
           ,[To]
           ,[Action]
           ,[Recipient]
           ,[ContactInfo]
           ,[Retry]
           ,[Note]
           ,[CreatedDate]
           ,[CreatedByID]
           ,[ModifiedDate]
           ,[ModifiedByID]
           ,[Deleted])

       SELECT     
            @newprotocolsetid
           ,[AlarmProtocolEventID]
           ,[Type]
           ,[Priority]
           ,[From]
           ,[To]
           ,[Action]
           ,[Recipient]
           ,[ContactInfo]
           ,[Retry]
           ,''
           ,GETDATE()
           ,55
           ,NULL
           ,NULL
           ,[Deleted]
From alarmprotocolaction
WHERE Alarmprotocolsetid = @Alarmprotocolsetid
GO
GRANT EXECUTE ON [AlarmProtocolCopy] TO [db_dml]
GO
