/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [RoleResourceDelete]

	@RoleID int

AS

SET NOCOUNT ON

DELETE
FROM RoleResourceMap
WHERE RoleID = @RoleID
GO
GRANT VIEW DEFINITION ON [RoleResourceDelete] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [RoleResourceDelete] TO [db_dml]
GO
