/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderUpdateMugPhoto]

	@OffenderID INT,
	@FileName	NVARCHAR(100)

AS

SET NOCOUNT ON

UPDATE [dbo].[Offender] SET

	MugPhotoName = @FileName

WHERE OffenderID = @OffenderID
GO
GRANT VIEW DEFINITION ON [OffenderUpdateMugPhoto] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OffenderUpdateMugPhoto] TO [db_dml]
GO
