/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmGetEventTypeIDEventParameter]

	@EventTypeID	INT OUTPUT,
	@EventParameter	SMALLINT OUTPUT,
	@AlarmID		INT

AS

	SELECT	@EventTypeID = ISNULL(EventTypeID, 0),
			@EventParameter = ISNULL(EventParameter, 0)
	FROM	Alarm
	WHERE	AlarmID = @AlarmID
GO
GRANT EXECUTE ON [AlarmGetEventTypeIDEventParameter] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [AlarmGetEventTypeIDEventParameter] TO [db_object_def_viewers]
GO
