/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportAlarmGetByOffenderID]

	@StartDate		BIGINT,
	@EndDate		BIGINT,
	@OffenderID		INT,
	@TimeZoneOffset INT
	
AS
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;	
				-- all start/end dates, all event types, all offenders
				SELECT	a.AlarmID, 
						(DATEADD ( mi, @TimeZoneOffset, (Convert(DateTime,a.EventDisplayTime)))) as EventTime,
						et.AbbrevEventType as EventName, 
						ISNULL(a.Longitude, 0) AS 'Longitude',
						ISNULL(a.Latitude, 0) AS 'Latitude',
						ISNULL(o.FirstName + ' ', '') + 
						ISNULL(o.MiddleName + ' ', '') + 
						ISNULL(o.LastName, '') AS 'OffenderName',
						o.OffenderID,
						ISNULL(ofcr.FirstName + ' ', '') + 
						ISNULL(ofcr.MiddleName + ' ', '') + 
						ISNULL(ofcr.LastName, '') AS 'OfficerName',
						ag.Agency,
						(DATEADD ( mi, @TimeZoneOffset, (Convert(DateTime,aak.AcknowledgedDate)))) AS 'Acknowledged'
				FROM	Alarm a
				LEFT JOIN AlarmAcknowledgement aak ON a.AlarmID = aak.AlarmID
				LEFT JOIN EventType et ON a.EventTypeID = et.EventTypeID
				LEFT JOIN Offender o ON a.OffenderID = o.OffenderID
				LEFT JOIN Officer ofcr on (Select OfficerID from Offender_Officer where OffenderID = a.OffenderID) = ofcr.OfficerID
				LEFT JOIN Agency ag ON ofcr.AgencyID = ag.AgencyID
					WHERE (
							( @StartDate = 0 AND @EndDate = 0) 
							or
							(a.EventTime >= @StartDate AND
							a.EventTime <= @EndDate
							)
						 )
					and	(
							(@OffenderID= 0)
							or
							(a.OffenderID = @OffenderID)
						)
		
			ORDER BY a.EventTime DESC, a.AlarmTypeID DESC
GO
GRANT EXECUTE ON [ReportAlarmGetByOffenderID] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [ReportAlarmGetByOffenderID] TO [db_object_def_viewers]
GO
