/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:26 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AlarmAcknowledgementAdd]

	@AlarmAcknowledgementID	INT OUTPUT,
	@AlarmID				INT,
	@AcknowledgedByID		INT

AS

	INSERT INTO	AlarmAcknowledgement
	(AlarmID, AcknowledgedByID)
	VALUES
	(@AlarmID, @AcknowledgedByID)

	SET @AlarmAcknowledgementID = @@IDENTITY
GO
GRANT EXECUTE ON [AlarmAcknowledgementAdd] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [AlarmAcknowledgementAdd] TO [db_object_def_viewers]
GO
