/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mLogAutocompletedActionsUpdate]
@GUID nvarchar(50),
@DN nvarchar(50),
@DailedDate datetime,
@DailedStatus nvarchar(50),
@IVR nvarchar(50),
@StatusID int
AS
BEGIN
	
	SET NOCOUNT ON;   
UPDATE LogAutocompletedActions 
SET
DailedDate= @DailedDate,
DailedStatus=@DailedStatus,
IVR = @IVR,
StatusID = @StatusID
WHERE lower(GUID)=@GUID and DN=@DN

END
GO
GRANT EXECUTE ON [mLogAutocompletedActionsUpdate] TO [db_dml]
GO
