/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OffenderAcquaintanceGetAll]

AS
BEGIN
	SET NOCOUNT ON;

	SELECT *
	FROM OffenderAcquaintance
END

GO
GRANT VIEW DEFINITION ON [OffenderAcquaintanceGetAll] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [OffenderAcquaintanceGetAll] TO [db_dml]
GO
