/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mAlarmTypeProtocolActionRetriesAll]

	

AS
	select g.AlarmProtocolActionRetryID, g.AlarmProtocolActionRetry, g.RoleID
	from AlarmProtocolActionRetry  g 
GO
GRANT EXECUTE ON [mAlarmTypeProtocolActionRetriesAll] TO [db_dml]
GO
