/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReverseGeoCode_UpdateEventAddress]

	@Address varchar(200),
	@EventPrimaryID bigint = -1

AS

UPDATE dbo.rprtEventsBucket1
	SET Address = @Address
	WHERE 
		(@EventPrimaryID > 0 AND EventPrimaryID = @EventPrimaryID)

--	@Latitude int,
--	@Longitude int,
--	@Address varchar(200),
--	@StartDate datetime = NULL,
--	@EndDate datetime = NULL
--
--AS
--
--UPDATE dbo.rprtEventsBucket1
--	SET Address = @Address
--	WHERE FLOOR(Latitude * 100000) = @Latitude AND FLOOR(Longitude * 100000) = @Longitude
--		AND (@StartDate IS NULL OR EventDateTime >= @StartDate)
--		AND (@EndDate IS NULL OR EventDateTime <= @EndDate)

GO
GRANT EXECUTE ON [ReverseGeoCode_UpdateEventAddress] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [ReverseGeoCode_UpdateEventAddress] TO [db_object_def_viewers]
GO
