/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mAlarmProtocolPassiveActionAdd]
@AlarmProtocolActionID INT OUTPUT,  
@AlarmPassiveProtocolSetID  INT, 
@AlarmPassivePlusProtocolSetID  INT, 
@AlarmProtocolEventID INT,  
@Type     NVARCHAR(25),  
@Priority    NVARCHAR(3),  
@From     NVARCHAR(25),  
@To     NVARCHAR(25),  
@Action     NVARCHAR(25),  
@Recipient    NVARCHAR(25),  
@ContactInfo    NVARCHAR(50),  
@Retry     NVARCHAR(3),  
@Note     NVARCHAR(150)=NULL,  
@CreatedByID   INT  

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
  

declare @AlarmProtocolActionID2 INT

BEGIN TRANSACTION;  

--PASSIVE
	 INSERT INTO AlarmProtocolAction  
	 (AlarmProtocolSetID, AlarmProtocolEventID, [Type], Priority,  
	  [From], [To], [Action], Recipient, ContactInfo, Retry,   
	  Note, CreatedByID)  
	 VALUES  
	 (@AlarmPassiveProtocolSetID, @AlarmProtocolEventID, @Type, @Priority,  
	  @From, @To, @Action, @Recipient, @ContactInfo, @Retry,  
	  @Note, @CreatedByID)  
	  
 SET @AlarmProtocolActionID = @@IDENTITY

--PASSIVE PLUS
	INSERT INTO AlarmProtocolAction  
	 (AlarmProtocolSetID, AlarmProtocolEventID, [Type], Priority,  
	  [From], [To], [Action], Recipient, ContactInfo, Retry,   
	  Note, CreatedByID)  
	 VALUES  
	 (@AlarmPassivePlusProtocolSetID, @AlarmProtocolEventID, @Type, @Priority,  
	  @From, @To, @Action, @Recipient, @ContactInfo, @Retry,  
	  @Note, @CreatedByID)  

 SET @AlarmProtocolActionID2 = @@IDENTITY


IF (@AlarmProtocolActionID+1 = @AlarmProtocolActionID2)
BEGIN
	COMMIT TRANSACTION;
END
ELSE
BEGIN
	SET @AlarmProtocolActionID = -1
	ROLLBACK TRANSACTION;
END	


END


GO
GRANT EXECUTE ON [mAlarmProtocolPassiveActionAdd] TO [db_dml]
GO
