/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
-- =============================================
-- Author:		Sajid Abbasi
-- Create date: 16-Dec-2009
-- Description:	This procedure adds ActionInstanceID for the georule that are uploaded.
-- =============================================
CREATE PROCEDURE [GeoRuleOffenderAddActionInstanceID]
	@OffenderID int,
    @ActionInstanceID bigint
AS
BEGIN
	SET NOCOUNT ON;

    UPDATE GeoRule_Offender 
	SET ActionInstanceID = @ActionInstanceID
    WHERE OffenderID = @OffenderID

END

GO
GRANT EXECUTE ON [GeoRuleOffenderAddActionInstanceID] TO [db_dml]
GO
