/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [SalutationGetAll]

AS

	SELECT	SalutationID, Salutation
	FROM	Salutation
	ORDER BY Salutation
GO
GRANT VIEW DEFINITION ON [SalutationGetAll] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [SalutationGetAll] TO [db_dml]
GO
