/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TrackerActionAdd] 
	@TrackerActionID bigint, 
	@TrackerActionTypeID int,
	@TrackerID int,
--	@TrackerActionDateTime DateTime, -- UTC date.
	@CreatedByID int
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO TrackerAction 
	(TrackerActionID, TrackerActionTypeID, TrackerID, TrackerActionDateTime, CreatedByID)
	VALUES
	(@TrackerActionID, @TrackerActionTypeID, @TrackerID, GETDATE(), @CreatedByID)

END
GO
GRANT VIEW DEFINITION ON [TrackerActionAdd] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [TrackerActionAdd] TO [db_dml]
GO
