/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [StaticTrackerAssignmentsGetAll]



AS

BEGIN

	SET NOCOUNT ON;

	SELECT 
		*
		 FROM TrackerAssignment 
		

END
GO
GRANT EXECUTE ON [StaticTrackerAssignmentsGetAll] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [StaticTrackerAssignmentsGetAll] TO [db_object_def_viewers]
GO
