/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [StaticUserGetAll]
	@UserTypeID AS int = 0

AS

SELECT 
	* 
FROM 
	[User] u 
	LEFT JOIN User_Role ur ON u.UserID = ur.UserID
	LEFT JOIN Officer o ON o.UserID = u.UserID
	LEFT JOIN Operator op ON op.UserID = u.UserID
	LEFT JOIN DistributorEmployee de ON de.UserID = u.UserID
WHERE
	@UserTypeID = 0 OR u.UserTypeID = @UserTypeID

GO
GRANT EXECUTE ON [StaticUserGetAll] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [StaticUserGetAll] TO [db_object_def_viewers]
GO
