/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TamGetAll]
AS
	SELECT u.UserID, u.UserName
	FROM [User] u
	LEFT JOIN User_Role ur ON u.UserID = ur.UserID
	WHERE ur.RoleID = 19 AND
		  u.deleted = 0
	ORDER BY u.UserName
	
GO
GRANT VIEW DEFINITION ON [TamGetAll] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [TamGetAll] TO [db_dml]
GO
