/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoRuleDelete]
	@GeoRuleID INT
AS
BEGIN
	SET NOCOUNT ON;

	Update Georule 
	Set deleted = 1
	WHERE GeoRuleID=@GeoRuleID
	
END

GO
GRANT VIEW DEFINITION ON [GeoRuleDelete] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [GeoRuleDelete] TO [db_dml]
GO
