/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mEventInsertBucket1] (
        @EventPrimaryID	BIGINT OUTPUT,
        @EventID BIGINT,
        @EventTypeGroupID BIGINT = NULL,
        @AlarmTypeID INT = NULL,
        @AlarmID BIGINT = NULL,
        @DeviceID BIGINT,
        @TrackerNumber VARCHAR(32)= NULL,
        @EventName VARCHAR(50) = NULL,
        @EventTime BIGINT,
        @EventDateTime DATETIME = NULL,
        @EventParameter BIGINT = NULL,
        @AgencyID INT = NULL,
        @OffenderID BIGINT = NULL,
        @OfficerID BIGINT = NULL,
        @ReceivedTime DATETIME = NULL,
        @Latitude FLOAT = NULL,
        @Longitude FLOAT = NULL,
        @SO BIT = NULL,
        @OPR BIT = NULL,
        @NoteCount INT = NULL,
        @GeoRuleName NVARCHAR(50) = NULL,
        @AlarmAssignmentStatusID INT = NULL,
        @AcceptedBy INT = NULL,
        @ActivateDate DATETIME = NULL,
        @DeActivateDate DATETIME = NULL,
        @GpsValid BIT = NULL,
        @GpsValidSatellites INT = NULL,
        @AcceptedDate DATETIME = NULL,
        @AlarmAssignmentStatus NVARCHAR(50) = NULL,
        @EventQueueID INT = NULL,
        @OffenderName NVARCHAR(100),
        @OffenderDeleted BIT = 0,
        @BeaconSerialNumber VARCHAR(100) = NULL
    )
AS

-- // Declare Var's // --
DECLARE @Address VARCHAR(100)

-- // Get the GeoRule Name // --
IF (@EventID IN (32,33,36,37,40,41,44,45))
    BEGIN
        EXEC GeoruleGetNewName @Offenderid, @EventParameter, @GeoruleName OUTPUT
        
        -- // Ensure we have a GeoRuleName // --
--        IF ((@GeoruleName IS NULL) OR (@GeoruleName = '') OR (@GeoruleName = 'N/A'))
--          BEGIN
--            SET @GeoruleName = ISNULL((SELECT GeoRule.GeoRuleName
--                                FROM GeoRule_Offender
--                                  INNER JOIN GeoRule ON GeoRule.GeoRuleID = GeoRule_Offender.GeoRuleID
--                                WHERE GeoRule_Offender.OffenderID = @OffenderID
--                                  AND GeoRule.GeoRuleID = @EventParameter), 'N/A')
--          END
	END

-- // Get the Beacon Address // --
IF (@EventID IN (176,177,178,179,180,181,182,184,185,192,193,194,195))
	BEGIN
		EXEC mBeaconGetAddressBySerialNumber @BeaconSerialNumber, @OffenderId, @Address OUTPUT, @Latitude OUTPUT, @Longitude OUTPUT
	END

/* =============== Ensure Valid Data ================== */

-- // Fix Offender Name // --
IF ((@OffenderName IS NULL) OR (@OffenderName = ''))
  BEGIN
    SET @OffenderName = (SELECT Offender.FirstName + ' ' + Offender.LastName
                         FROM Offender
                         WHERE Offender.OffenderID = @OffenderID)
  END

-- // Fix OfficerID // --
IF ((@OfficerID IS NULL) OR (@OfficerID = 0))
  BEGIN
    SET @OfficerID = ISNULL((SELECT OfficerID
                             FROM Offender
                               INNER JOIN Offender_Officer ON Offender_Officer.OffenderID = Offender.OffenderID
                             WHERE Offender.OffenderID = @OffenderID),0)
  END

-- // Fix AgencyID // --
IF ((@AgencyID IS NULL) OR (@AgencyID = 0))
  BEGIN
    SET @AgencyID = ISNULL((SELECT Agency.AgencyID
                            FROM Offender 
                              INNER JOIN Agency ON Agency.AgencyID = Offender.AgencyID
                            WHERE Offender.OffenderID = @OffenderID),0)
  END
/* ===================== End Validity Checks =============== */

-- // Insert Event Record // --
INSERT rprtEventsBucket1 (	
       EventID,
	   DeviceID,
	   EventTime,
	   EventDateTime,
	   TrackerNumber,
	   EventName,
	   EventParameter,
	   ReceivedTime,
	   OfficerID,
	   OffenderID,
	   AgencyID,
	   [Address],
	   Latitude,
	   Longitude,
	   OPR,
	   SO,
	   NoteCount,
	   AlarmType,
	   AlarmID,
	   GeoRule,
	   AlarmAssignmentStatusID,
	   AlarmAssignmentStatusName,
	   AcceptedBy,
	   ActivateDate,
	   DeActivateDate,
	   GpsValid,
	   GpsValidSatellites,
	   AcceptedDate,
	   EventTypeGroupID,
	   EventQueueID,
	   OffenderName,
	   OffenderDeleted			
    )
VALUES (@EventID,
		@DeviceID,
		@EventTime,
		@EventDateTime,
		@TrackerNumber,
		@EventName,
		@EventParameter,
		@ReceivedTime,	
		@OfficerID,	
		@OffenderID,
		@AgencyID,
		@Address,
		@Latitude,
		@Longitude,
		@SO,
		@OPR,
		@NoteCount,
		@AlarmTypeID,
		@AlarmID,
		@GeoRuleName,
		@AlarmAssignmentStatusID,
		@AlarmAssignmentStatus,
		@AcceptedBy,
		@ActivateDate,
		@DeActivateDate,
		@GpsValid,
		@GpsValidSatellites,
		@AcceptedDate,
		@EventTypeGroupID,
		@EventQueueID,
		@OffenderName,
		@OffenderDeleted
    )

-- // Set the EventID // --
SET @EventPrimaryID = @@IDENTITY

GO
GRANT EXECUTE ON [mEventInsertBucket1] TO [db_dml]
GO
