/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:26 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [AgencyGetGridInfoByTamUserID]
	@UserID int
AS
	SELECT	a.AgencyID, a.Agency, a.City, s.State
	FROM	Agency a(NOLOCK)
	LEFT JOIN State s ON a.StateID = s.StateID
	LEFT JOIN Distributor d ON d.DistributorID = a.DistributorID
	LEFT JOIN User_Role ur ON d.TamID = ur.UserID
	WHERE	a.Deleted = 0 AND
			ur.UserID = @UserID
	ORDER BY a.Agency
GO
GRANT EXECUTE ON [AgencyGetGridInfoByTamUserID] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [AgencyGetGridInfoByTamUserID] TO [db_object_def_viewers]
GO
