/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [spTrackerActivationHistory]

@SerialNumber varchar(64) = NULL

AS
SELECT
a.Agency
,ofi.firstName+' '+ofi.LastName AS 'Officer Name'
,o.firstName+' '+o.LastName AS 'Offender Name'
,ota.TrackerID
,dp.Propertyvalue As 'Serial #'
,CONVERT(VARCHAR (25),DATEADD(mi,tz.UTCOFFSET,ota.ActivateDate))AS 'Activated Date'
,(CASE When ota.deactivatedate IS NULL THEN 'ACTIVE' ELSE CONVERT(VARCHAR (25),DATEADD(mi,tz.UTCOFFSET,ota.DeActivateDate))END)AS 'Deactivated Date'
,(CASE WHEN ota.deactivateDate IS NULL THEN 'ACTIVE' ELSE opr.FirstName+' '+opr.LastNAme END)AS 'Deactivated By'
From Offendertrackeractivation ota
JOIN Offender o ON o.Offenderid = ota.Offenderid
JOIN Officer ofi ON ofi.officerid = ota.officerid
JOIN Agency a on a.agencyid = o.agencyid
JOIN Timezone tz on tz.timezoneid = a.timezoneid
JOIN gateway.dbo.deviceproperties dp ON dp.deviceid = ota.trackerid AND dp.propertyid = '8012'
LEFT JOIN Operator opr ON opr.userid = ota.ModifiedByid
Where (dp.PropertyValue LIKE '%' + ISNULL(@SerialNumber,'') + '%')
ORDER BY a.Agency,'Offender Name', 'Activated Date'











GO
GRANT EXECUTE ON [spTrackerActivationHistory] TO [db_dml]
GO
