/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GetLatLon]
AS



-- then the procedure look for coordinates that does not have address resolved
        SELECT top 100 latitude lat, longitude lon, StreetAddress
        FROM dbo.StreetAddressCache s
        WHERE len(StreetAddress)=0 OR StreetAddress IS NULL
GO
GRANT EXECUTE ON [GetLatLon] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [GetLatLon] TO [db_object_def_viewers]
GO
