/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [OfficerUpdate]

	@OfficerID		INT,
	@AgencyID		INT,
	@Title			NVARCHAR(50),
	@Department     NVARCHAR(50),
	@SalutationID	INT,
	@FirstName		NVARCHAR(50),
	@MiddleName		NVARCHAR(50),
	@LastName		NVARCHAR(50),
	@SuffixID		INT,
	@StreetLine1	NVARCHAR(50),
	@StreetLine2	NVARCHAR(50),
	@City			NVARCHAR(50),
	@StateID		INT,
	@PostalCode		NVARCHAR(25),
	@CountryID		INT,
	@DayPhone		NVARCHAR(25),
	@EveningPhone	NVARCHAR(25),
	@ExtDayPhone	NVARCHAR(20),
	@ExtEveningPhone NVARCHAR(20),
	@MobilePhone	NVARCHAR(25),
	@Pager			NVARCHAR(25),
	@Fax			NVARCHAR(25),
	@EmailAddress1	NVARCHAR(50),
	@EmailAddress2	NVARCHAR(50),
	@ModifiedByID	INT,
	@ModifiedDate    DATETIME = null OUTPUT,
	@SMSAddress		NVARCHAR(50),
	@SMSGatewayID   INT
	

AS
	SET @ModifiedDate = GETDATE()

	UPDATE	Officer
	SET		AgencyID = @AgencyID, 
			Title = @Title,
			Department = @Department,
			SalutationID = @SalutationID,
			FirstName = @FirstName,
			MiddleName = @MiddleName,
			LastName = @LastName,
			SuffixID = @SuffixID,
			StreetLine1 = @StreetLine1,
			StreetLine2 = @StreetLine2,
			City = @City,
			StateID = @StateID,
			PostalCode = @PostalCode,			
			CountryID = @CountryID,
			DayPhone = @DayPhone,
			EveningPhone = @EveningPhone,
            ExtDayPhone = @ExtDayPhone,
            ExtEveningPhone = @ExtEveningPhone,
			MobilePhone = @MobilePhone,
			Pager = @Pager,
			Fax = @Fax,
			EmailAddress1 = @EmailAddress1,
			EmailAddress2 = @EmailAddress2,
			ModifiedDate = @ModifiedDate,
			ModifiedByID = @ModifiedByID,
			SMSAddress	= @SMSAddress,
			SMSGatewayID = @SMSGatewayID
			
	WHERE	OfficerID = @OfficerID
GO
GRANT EXECUTE ON [OfficerUpdate] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [OfficerUpdate] TO [db_object_def_viewers]
GO
