/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [BillingServiceDelete] 
@BillingServiceID INT
AS
--Adds new Billing Service record to BillingService.
SET NOCOUNT ON;

--Check for latent transcations.
IF @@TRANCOUNT > 0
	BEGIN
		ROLLBACK TRANSACTION
	END;

BEGIN TRANSACTION;
BEGIN TRY
	DELETE dbo.BillingServiceOptionReportingInterval
	WHERE BillingServiceOptionID in (SELECT ID FROM BillingServiceOption WHERE BillingServiceID = @BillingServiceID)

	DELETE dbo.BillingServiceOption
	WHERE BillingServiceID = @BillingServiceID

	DELETE dbo.EArrestService
	WHERE	ClassicBillingServiceID in (SELECT ID FROM ClassicBillingService WHERE BillingServiceID = @BillingServiceID)

	DELETE dbo.ClassicBillingService
	WHERE	BillingServiceID = @BillingServiceID

	DELETE dbo.BillingService
	WHERE	ID = @BillingServiceID
END TRY
BEGIN CATCH
	--Catch and return error.
    SELECT 
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_SEVERITY() AS ErrorSeverity,
        ERROR_STATE() as ErrorState,
        ERROR_PROCEDURE() as ErrorProcedure,
        ERROR_LINE() as ErrorLine,
        ERROR_MESSAGE() as ErrorMessage;
	--Rollback outstanding transactions.
	IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION
		END;
END CATCH;

IF @@TRANCOUNT > 0
	BEGIN
		COMMIT TRANSACTION
	END;



GO
GRANT EXECUTE ON [BillingServiceDelete] TO [db_dml]
GO
