/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [UserUpdateUserName]

        @UserID                 INT,
        @UserName               NVARCHAR(25),
        @ModifiedByID   INT

AS

        -- verify UserName does not already exist
        DECLARE @RecordCount INT
        SELECT  @RecordCount = COUNT (*)
        FROM    [User]
        WHERE   UserName = @UserName
        AND     UserID <> @UserID

        IF @RecordCount > 0
        BEGIN
                RAISERROR('User Name "%s" already taken.  Please choose another.', 16, 1, @UserName)
        END
        ELSE
        BEGIN
                UPDATE  [User]
                SET             UserName = @UserName,
                                ModifiedDate = GETDATE(),
                                ModifiedByID = @ModifiedByID
                WHERE   UserID = @UserID
        END

GO
GRANT VIEW DEFINITION ON [UserUpdateUserName] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [UserUpdateUserName] TO [db_dml]
GO
