/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GeoRuleRetrieveLibraryInfo]
	
	@LibraryId uniqueidentifier
	
AS

BEGIN
	SELECT
		GeoZone.Name,
		GeoZone.Description,
		GeoZone.GroupChildCount,
		GeoRuleGroupOwner.OwnerType,
		GeoRuleGroupOwner.OwnerID

	FROM
		GeoZone INNER JOIN GeoRuleGroupOwner 
		ON GeoRuleGroupOwner.GeoRuleGroupID = GeoZone.Id
	WHERE
		GeoZone.id = @LibraryId

END










GO
GRANT EXECUTE ON [GeoRuleRetrieveLibraryInfo] TO [db_dml]
GO
