/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [mOffenderContactAdd]
	@ID int output,
	@FirstName nvarchar(35),
	@LastName nvarchar(40),
	@RelationShip nvarchar(50) = null,
	@HomePhone nvarchar(15) = null,
	@MobilePhone nvarchar(15) = null,
	@WorkPhone nvarchar(15) = null,
    @AltPhone1 nvarchar(15) = null,
	@AltPhone2 nvarchar(15) = null,
	@Email1 nvarchar(15) = null,
	@Email2 nvarchar(15) = null,
	@OffenderID int

AS
BEGIN
	
	SET NOCOUNT ON;
    	INSERT INTO Contacts 
		values(@FirstName, @LastName, @RelationShip,@HomePhone,@MobilePhone,@WorkPhone,@AltPhone1,@AltPhone2,@Email1,@Email2)
		
		SET @ID  = @@IDENTITY

		INSERT INTO OffenderContact values(@ID,@OffenderID)
END




GO
GRANT EXECUTE ON [mOffenderContactAdd] TO [db_dml]
GO
