/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ERuleGetByBeaconID]
@BeaconID	INT

AS

	SET NOCOUNT ON

	SELECT	e.ID as 'ERuleID',e.[Name],
            r.UploadStatusID,
            g.GeoRuleStatusName as 'StatusName'
	FROM	dbo.ERule e
    inner join [Rule] r ON r.ID = e.RuleID
    inner join GeoRuleStatus g ON g.GeoRuleStatusID = r.UploadStatusID

    WHERE   e.BeaconID=@BeaconID ORDER BY e.[Name] DESC
	






GO
GRANT EXECUTE ON [ERuleGetByBeaconID] TO [db_dml]
GO
