/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ETrackerAdd]
	@ETrackerID		 INT OUTPUT,	
	@TrackerID       INT
	


AS

	INSERT INTO dbo.ETracker
	(TrackerID)
	VALUES
	(@TrackerID)

	SET @ETrackerID = @@IDENTITY



GO
GRANT EXECUTE ON [ETrackerAdd] TO [db_dml]
GO
