/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ETrackerUpdateTrackerID]

	@OffenderID	    INT,	
	@TrackerID		INT

AS

DECLARE @ETrackerID int 
set   @ETrackerID =( select  etrackerid
	from etracker where trackerid=
	(
		select top 1 t.trackeruniqueid 
		from trackerAssignment ta
		join tracker t on t.trackerid=ta.trackerid 
		where trackerAssignmentTypeid=2 
		and offenderid= @OffenderID
		order by assignmentDate desc
	)
)

if( @ETrackerID is not null )
begin
update  etracker set Trackerid= @TrackerID where etrackerid=@ETrackerID
end



GO
GRANT EXECUTE ON [ETrackerUpdateTrackerID] TO [db_dml]
GO
