/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
/* /////////////////////////////////////////////////////////// --
-- // FileName:     EventTypesGetAllDetails.sql	            // -- 
-- // Created On:	unknown                                 // --
-- // Created By:   J.Barrus                                // --
-- // Task #:		SA_                                     // --
-- // Purpose:      Get EventType Details for TrackerMAP    // --
-- //                                                       // --
-- // Modified By:  R.Cole - 11/17/2009                     // --
-- //               Removed the SELECT *                    // --
-- /////////////////////////////////////////////////////////// */
CREATE PROCEDURE [EventTypesGetAllDetails] (
    @SO INT, 
    @OPR INT
)

AS

SELECT EventTypeID,
       AbbrevEventType,
       EventTypeGroupID,
       SO,
       OPR,
       EventDescription,
       BringOver,
       LongName,
       Visible	
FROM EventType
WHERE Visible = 1
  AND ( (@SO < 0) OR (SO = @SO) )
  AND ( (@OPR < 0) OR (OPR = @OPR) )	
ORDER BY AbbrevEventType
GO
GRANT EXECUTE ON [EventTypesGetAllDetails] TO [db_dml]
GO
