/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [EventGetByOfficerID]

	@StartDate		datetime,
	@EndDate		datetime,
	@EventTypeID	INT,
	@OfficerID		INT,
	@SO				INT,
	@OPR			INT,
	@EventTypeGroupID int 
	
AS
WITH Events_CTE
AS
(
SELECT *
FROM rprtEventsBucket2
WHERE EventDateTime BETWEEN @StartDate AND @EndDate AND OfficerID = @OfficerID
UNION
SELECT *
FROM rprtEventsBucket1
WHERE EventDateTime BETWEEN @StartDate AND @EndDate AND OfficerID = @OfficerID
)

SELECT * INTO #tmp FROM Events_CTE
SELECT
	e.DeviceID, 
	e.TrackerNumber,
	e.EventTime, 
	e.EventDateTime,
	e.EventID,
	ISNULL(e.AlarmType, 1) AS 'AlarmType', -- 1: notification
	ISNULL(e.[AlarmAssignmentStatusName],'Unassigned') AS 'AlarmAssignmentStatusName',
	et.AbbrevEventType as EventName,
	ISNULL(ROUND(e.Longitude,5), 0) AS 'Longitude',
	ISNULL(ROUND(e.Latitude,5), 0) AS 'Latitude',
	e.Address AS 'Address',
--	ISNULL(o.FirstName+' ','')+ISNULL(o.MiddleName+' ','')+ISNULL(o.LastName,'') AS 'OffenderName',
	e.OffenderName,
	e.OffenderID,
	( (SELECT COUNT (*) FROM AlarmNote WHERE AlarmID = e.AlarmID )
		+ (SELECT COUNT (*) FROM EventNote WHERE DeviceID=e.DeviceID and EventTime=e.EventTime and	EventID=e.eventid)) 
		as 'NoteCount',
	e.AlarmID,
	ISNULL(e.GpsValid,0) AS 'GpsValid',
	ISNULL(e.GpsValidSatellites,0) AS 'GpsValidSatellites',
	e.GeoRule
	
FROM 
   #tmp e
--	[fnEvents] ( @StartDate, @EndDate ) e
--	LEFT JOIN Offender o ON o.OffenderID = e.OffenderID
	LEFT JOIN EventType et ON et.EventtypeID= e.EventID
WHERE
	((@EventTypeID <0) OR (EventID = @EventTypeID))
--	AND (
--		(@StartDate = 0 AND @EndDate = 0)
--		OR
--		(EventDateTime >= @StartDate AND EventDateTime <= @EndDate)
--	)
--	AND
--	((@OfficerID = 0) OR (OfficerID = @OfficerID))
	AND ((@SO<0) OR (e.SO=@SO))
	AND ((@OPR<0) OR (e.OPR=@OPR))
	AND	(
		(@EventTypeGroupID < 0)
		OR
		(e.EventTypeGroupID = @EventTypeGroupID )
	)
	AND e.OffenderDeleted = 0
ORDER BY
	EventDateTime DESC, AlarmType
Drop table #tmp





GO
GRANT EXECUTE ON [EventGetByOfficerID] TO [db_dml]
GO
