/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [EventGetByEventTypeIDDistributor]    
    
 @StartDate  datetime,    
 @EndDate   datetime,    
 @EventTypeID INT,    
 @SO    INT,    
 @OPR    INT,    
 @UserID   INT,    
 @EventTypeGroupID int     
     
AS    
Select *     
INTO #Eventstemp    
From fnallevents()    
where EventdateTime >= @StartDate And EventDatetime <=@EndDate    
    
SELECT    
  e.EventParameter,      
   e.DeviceID,     
 e.TrackerNumber,    
 e.EventTime,     
 e.EventDateTime,    
 e.EventID,    
 ISNULL(e.AlarmType, 1) AS 'AlarmType', -- 1: notification    
 ISNULL(e.[AlarmAssignmentStatusName],'Unassigned') AS 'AlarmAssignmentStatusName',    
 et.AbbrevEventType as EventName,    
 ISNULL(ROUND(e.Longitude,5), 0) AS 'Longitude',    
 ISNULL(ROUND(e.Latitude,5), 0) AS 'Latitude',    
  (CASE 
	when e.EventID = 195 then isnull(addrs.Street1,'')+' '+isnull(addrs.Street2,'')+' '+isnull(addrs.ZipCode,'')+' '+isnull(addrs.City,'')+' '+isnull(st.State,'')
	else e.Address 
	end
 )
 as 'Address'	,	    
-- ISNULL(o.FirstName+' ','')+ISNULL(o.MiddleName+' ','')+ISNULL(o.LastName,'') AS 'OffenderName',    
 e.OffenderName,    
 e.OffenderID,    
 ( (SELECT COUNT (*) FROM AlarmNote WHERE AlarmID = e.AlarmID )    
  + (SELECT COUNT (*) FROM EventNote WHERE DeviceID=e.DeviceID and EventTime=e.EventTime and EventID=e.eventid))     
  as 'NoteCount',    
 e.AlarmID,    
 (
  case
	WHEN e.EventID =195 
	then '1'
	else ISNULL(e.GpsValid,0) 
  end
 )AS 'GpsValid',  
 (
  case
	WHEN e.EventID =195  
	then '1'
	else ISNULL(e.GpsValidSatellites,0) 
  end
 )AS 'GpsValidSatellites',  
    
(    
  CASE    
 WHEN e.EventTypeGroupID = 5    
 THEN e.GeoRule    
 WHEN e.EventTypeGroupID =10   
 THEN isnull(er.[Name],'N/A')    
   ELSE 'N/A'    
  END    
 ) AS 'GeoRule'     
         
       
FROM     
 #Eventstemp e    
left join schedule s on  s.id =  e.eventparameter  
left join ERule er ON er.ID=s.RuleID   
 LEFT JOIN EventType et ON et.EventtypeID= e.EventID    
 left join beacon b on b.id = er.Beaconid  
left join address addrs on b.addressid =addrs.id
left join state st on st.stateid  = addrs.stateid   
WHERE    
 ((@EventTypeID <0) OR (EventID = @EventTypeID))    
 AND    
 (    
  (@StartDate = 0 AND @EndDate = 0)    
  OR    
  (EventDateTime >= @StartDate AND EventDateTime <= @EndDate)    
 )    
 AND ((@SO<0) OR (e.SO=@SO))    
 AND ((@OPR<0) OR (e.OPR=@OPR))    
 AND (    
  (@EventTypeGroupID < 0)    
  OR    
  (e.EventTypeGroupID = @EventTypeGroupID)    
 )    
 AND e.OffenderDeleted = 0    
 AND e.AgencyID IN (SELECT AgencyID FROM Agency WHERE DistributorID IN (SELECT DistributorID FROM DistributorEmployee WHERE UserId = @UserId ) )    
ORDER BY    
 EventDateTime DESC, AlarmType    
Drop table #Eventstemp    
  
GO
GRANT EXECUTE ON [EventGetByEventTypeIDDistributor] TO [db_dml]
GO
