/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [EventTypesGetAllEventGroups]
	@SO				INT,
	@OPR			INT
AS

	SELECT	'G' + Convert(varchar ,e.EventTypeGroupID) as EventID,
			e.EventTypeGroupName as  EventName
	FROM	EventType et
	join    EventTypeGroup e on et.eventtypegroupid = e.eventtypegroupid
	WHERE	VISIBLE=1 AND (
				(@SO<0)
				or
				 (et.SO=@SO)
			)
		and (
				(@OPR<0)
				or
				(et.OPR=@OPR)
			)
	group by e.EventTypeGroupID ,e.EventTypeGroupName 
GO
GRANT VIEW DEFINITION ON [EventTypesGetAllEventGroups] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [EventTypesGetAllEventGroups] TO [db_dml]
GO
