/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GatewayEventGenerator]
		

      @Deviceid int,
		@EventID int,
		@EventParameter int,
      @EventTime Bigint


AS
--	DECLARE @EventTime bigint
	DECLARE @ReceivedTime Datetime
	DECLARE @TransmittedTime Datetime
	DECLARE @GpsValid bit
	DECLARE @GpsValidSatellites bit
	DECLARE @Latitude float
	DECLARE @Longitude float
	DECLARE @EventName varchar(64)
	DECLARE @AlarmType int
	DECLARE @Enabled bit
	DECLARE @GpsSatellites tinyint
	DECLARE @Speed tinyint
	DECLARE @Heading tinyint
	DECLARE @Hdop smallint
	DECLARE @InternalBatteryVoltage smallint
	DECLARE @ExternalBatteryVoltage smallint
	DECLARE @SignalStrength tinyint
	DECLARE @Status int
   DECLARE @BeaconSerialNumber char(6)



--	SET @EventTime = TrackerPal.dbo.ConvertDateToLong (GETDATE())
	SET @ReceivedTime = GETDATE()
	SET @TransmittedTime = GETDATE()
	SET @GpsValid = 1
	SET @GpsValidSatellites = 1
	SET @Latitude = '40.2078866666667'
	SET @Longitude = '-111.645133333333'
	SET @EventName = (Select EventName From Gateway.dbo.eventtypes Where eventid = @EventID)
	SET @AlarmType = (Select AlarmType From Gateway.dbo.eventtypes WHERE eventid = @EventID)
	SET @Enabled = 1
	SET @GpsSatellites = 5
	SET @Speed = 0
	SET @Heading = 0
	SET @Hdop = 0
	SET @InternalBatteryVoltage = 0
	SET @ExternalBatteryVoltage = 0
	SET @SignalStrength = 0
	SET @Status = 0
   SET @BeaconSerialNumber = 'B2001A'



	BEGIN

	INSERT INTO [Gateway].[dbo].[TrackerPalQueue1]
           ([EventTime]
           ,[DeviceID]
           ,[EventID]
           ,[EventParameter]
           ,[GpsValid]
           ,[GpsValidSatellites]
           ,[ReceivedTime]
           ,[TransmittedTime]
           ,[Latitude]
           ,[Longitude]
           ,[EventName]
           ,[AlarmType]
           ,[Enabled]
           ,[GpsSatellites]
           ,[Speed]
           ,[Heading]
           ,[Hdop]
           ,[InternalBatteryVoltage]
           ,[ExternalBatteryVoltage]
           ,[SignalStrength]
           ,[Status]
           ,[BeaconSerialNumber])
     VALUES
           (@EventTime,@DeviceID,@EventID,@EventParameter,@GpsValid,@GpsValidSatellites,@ReceivedTime,
           @TransmittedTime,@Latitude,@Longitude,@EventName,@AlarmType,@Enabled,@GpsSatellites,@Speed,
           @Heading,@Hdop,@InternalBatteryVoltage,@ExternalBatteryVoltage,@SignalStrength,@Status,@BeaconSerialNumber)

END





GO
GRANT EXECUTE ON [GatewayEventGenerator] TO [db_dml]
GO
