/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [GetProtocolAlarmIsInProgress]
    @alarmProtocolEventID int,
	@alarmProtocolSetID int
AS
BEGIN
	SET NOCOUNT ON;

select count(*) from alarm a
INNER JOIN AlarmAssignment aa ON a.alarmId = aa.alarmid 
			AND aa.AssignedDate = (SELECT MAX(AssignedDate) FROM AlarmAssignment AAD WHERE aad.AlarmID 
in (select alarmid from rprtAlarmMonitorCenterGrid 
where a.EventTypeID IN (SELECT DISTINCT AlarmProtocolEvent.GatewayEventID
                            FROM          AlarmProtocolEvent INNER JOIN
                                                   AlarmProtocolAction ON AlarmProtocolEvent.AlarmProtocolEventID = AlarmProtocolAction.AlarmProtocolEventID INNER JOIN
                                                   AlarmProtocolSet ON AlarmProtocolAction.AlarmProtocolSetID = AlarmProtocolSet.AlarmProtocolSetID
                            WHERE      (AlarmProtocolSet.AlarmProtocolSetID = @alarmProtocolSetID) AND (AlarmProtocolAction.AlarmProtocolEventID =@alarmProtocolEventID))
and offenderid IN(SELECT OffenderID FROM Offender_AlarmProtocolSet WHERE (AlarmProtocolSetID = @alarmProtocolSetID) AND (Deleted = 0)
)))

END


GO
GRANT EXECUTE ON [GetProtocolAlarmIsInProgress] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [GetProtocolAlarmIsInProgress] TO [db_object_def_viewers]
GO
