/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [HairColorGetAllHairColor]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT *
	FROM HairColor
END

GO
GRANT EXECUTE ON [HairColorGetAllHairColor] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [HairColorGetAllHairColor] TO [db_object_def_viewers]
GO
