/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [refDayGetAll]

AS

	SET NOCOUNT ON

	SELECT	ID, RTrim(Short_Name) as Short_Name
	FROM	dbo.refDay
	



GO
GRANT EXECUTE ON [refDayGetAll] TO [db_dml]
GO
