/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReportCourt2]

@StartDate			datetime,
	@EndDate			datetime,
	@OffenderID			int,
	@AgencyID			int


AS
set @StartDate = trackerpal.dbo.fnLocalToUtc(@AgencyID, @StartDate)
set @EndDate = trackerpal.dbo.fnLocalToUtc(@AgencyID, @EndDate)

Select e.*
INTO #tempcourt2
FROM
(Select * from rprteventsbucket1 WITH (NOLOCK)
UNION ALL
Select * from rprteventsbucket2 WITH (NOLOCK)
) e


Where e.EventDatetime >= @StartDate And e.EventDatetime <= @EndDate
And e.Offenderid = @offenderid

/*EventNotes*/
DECLARE
@EventNotesTemp
TABLE 
(
NOTES INT , EVENTID int, EVENTTIME BIGINT, DEVICEID INT, USERID INT,CREATEDDATE DATETIME 
)

INSERT INTO 
@EventNotesTemp 
(
NOTES , EVENTID, EVENTTIME, DEVICEID,USERID,CREATEDDATE
)
SELECT
COUNT(EN.EVENTNOTEID),
E.EVENTID,
E.EVENTTIME,
E.DEVICEID,
EN.CreatedByID,
en.CreatedDate  

FROM EVENTNOTE EN WITH(NOLOCK)
	LEFT JOIN #tempcourt2 e ON en.DeviceID = e.DeviceID AND en.EventTime = e.EventTime AND en.EventID = e.EventID
	LEFt JOIN EventType et WITH(NOLOCK) ON e.EventID = et.EventTypeID
	LEFT JOIN Offender o WITH(NOLOCK) ON o.OffenderID = e.OffenderID AND o.Deleted = 0

WHERE
	(Convert(Datetime,(DATEADD(ms, (e.EventTime / CAST(10000 AS bigint)) % 86400000,
	DATEADD(day, e.EventTime / CAST(864000000000 AS bigint) - 109207, 0))))
	>= @StartDate 
	AND 
	Convert(DateTime,(DATEADD(ms, (e.EventTime / CAST(10000 AS bigint)) % 86400000,
	DATEADD(day, e.EventTime / CAST(864000000000 AS bigint) - 109207, 0))))
	<= @EndDate)

	and o.OffenderID = @OffenderID
	AND ((et.SO = 1)) /*only the events that are available to So*/


GROUP BY E.EVENTID,
E.EVENTTIME,
E.DEVICEID,
EN.CreatedByID,
en.CreatedDate  
/*end eventNotes*/

/*AlarmNotes*/
DECLARE
@AlarmNoteTemp
TABLE 
(
 NOTES INT , ALARMID int, USERID INT 
)

INSERT INTO 
@AlarmNoteTemp 
(
NOTES , ALARMID,USERID
)
SELECT
COUNT(AN.ALARMNOTEID),
A.ALARMID,
AN.CreatedByID

FROM ALARMNOTE AN WITH(NOLOCK)
	LEFT JOIN Alarm a WITH(NOLOCK)ON A.ALARMID = AN.ALARMID
	LEFT JOIN #tempcourt2 e ON 
	e.DeviceID = a.TrackerID 
		AND e.EventTime = a.EventTime 
		AND e.EventID = a.EventTypeID

	LEFT JOIN EventType et WITH(NOLOCK) ON e.EventID = et.EventTypeID
	LEFT JOIN Offender o ON o.OffenderID = e.OffenderID AND o.Deleted = 0	

WHERE
	(Convert(Datetime,(DATEADD(ms, (e.EventTime / CAST(10000 AS bigint)) % 86400000,
	DATEADD(day, e.EventTime / CAST(864000000000 AS bigint) - 109207, 0))))
	>= @StartDate 
	AND 
	Convert(DateTime,(DATEADD(ms, (e.EventTime / CAST(10000 AS bigint)) % 86400000,
	DATEADD(day, e.EventTime / CAST(864000000000 AS bigint) - 109207, 0))))
	<= @EndDate)
	and o.OffenderID = @OffenderID
	AND (et.SO = 1)/*only the events that are available to So*/


GROUP BY A.ALARMID,
AN.CreatedByID
--AN.CreatedDate

/*end alarmnotes*/

SELECT	
TOP 5000
e.Offendername AS 'Offender',
	ISNULL(so.FirstName + ' ', '') + 
	ISNULL(so.LastName, '') AS 'Officer',
	ag.Agency,
	trackerpal.dbo.fnUtcToLocal(@AgencyID,e.eventdatetime) AS 'Event Time', 
	(
		CASE
			WHEN a.EventTypeID = 256 AND a.EventParameter > 0
			THEN et.AbbrevEventType + ' ' + CONVERT(nvarchar(4),a.EventParameter)
			ELSE et.AbbrevEventType
		END
	) AS 'Event Name',
	(
		CASE
			WHEN et.EventTypeGroupID = 5
			THEN gr.GeoRuleName 
			ELSE 'N/A'
		END
	) AS 'Geo Rule',

    (CASE WHEN e.Gpsvalid > 0  OR e.eventid IN (176,177,178,179,180,181,182,184,185,192,193,194,195)
    THEN e.Address
     ELSE 'Unavailable' END) AS 'Location',

	ISNULL(ROUND(e.Latitude,5), 0) AS 'Latitude',
	ISNULL(ROUND(e.Longitude,5), 0) AS 'Longitude',
	ISNULL(e.GpsValid,0) as 'GpsValid',
	ISNULL(e.GpsValidSatellites,0) as 'GpsValidSatellites',
	case when dbo.fnIsAlarmAutoCompleted(e.AlarmID) > 0 then
		trackerpal.dbo.fnUtcToLocal(@AgencyID,aa2.AssignedDate)
	else
		trackerpal.dbo.fnUtcToLocal(@AgencyID,aa.AssignedDate)  		
	END as 'Accepted Date',
	case when oa.FirstName is null then
		ISNULL(op.FirstName + ' ', '') + 
		ISNULL(op.MiddleName + ' ', '') + 
		ISNULL(op.LastName, '')
	else
		ISNULL(oa.FirstName + ' ', '') + 
		ISNULL(oa.MiddleName + ' ', '') + 
		ISNULL(oa.LastName, '')
	END AS 'Operator',
	ISNULL(AN.nOTES,0) +ISNULL(EN.nOTES,0) AS 'Notes Count',
	--case when dbo.fnIsAlarmAutoCompleted(e.AlarmID) > 0 then 'Autocompleted Alarms' 
	--else 'Regular Alarms' end as 'IsAlarmsAutoCompleted',
	@StartDate as 'StartDateAgency',
	@EndDate as 'EndDateAgency',
	dbo.fnGetUtcOffset(@AgencyID) as 'utcoffset',
	e.EventID,
	e.offenderID

FROM
	#tempcourt2 e
	LEFT JOIN EventType et WITH(NOLOCK) ON e.EventID = et.EventTypeID
	LEFT JOIN Alarm a WITH(NOLOCK) ON 
		e.DeviceID = a.TrackerID 
		AND e.EventTime = a.EventTime 
		AND e.EventID = a.EventTypeID
	LEFT JOIN Offender_Officer oo WITH(NOLOCK) ON oo.OffenderID = e.OffenderID
	LEFT JOIN Officer so WITH(NOLOCK) ON so.OfficerID = e.OfficerID
	LEFT JOIN Agency ag WITH(NOLOCK) ON ag.AgencyID = e.AgencyID
	LEFT JOIN AlarmAssignment aa WITH(NOLOCK) on a.alarmId = aa.alarmid AND aa.AssignedDate = 
	(
		SELECT MAX(AssignedDate) FROM AlarmAssignment AAD WITH(NOLOCK) WHERE aad.AlarmID = a.AlarmID and aad.alarmassignmentStatusID = 2
	) 
	and  aa.alarmassignmentStatusID = 2
	LEFT JOIN AlarmAssignment aa2 WITH(NOLOCK) on a.alarmId = aa2.alarmid AND aa2.AssignedDate = 
	(
		SELECT MAX(AssignedDate) FROM AlarmAssignment AAD2 WITH(NOLOCK) WHERE aad2.AlarmID = a.AlarmID and aad2.alarmassignmentStatusID = 4
	) 
	and  aa.alarmassignmentStatusID = 4

	LEFT JOIN GeoRule gr WITH(NOLOCK) ON gr.GeoRuleID = e.EventParameter
	LEFT JOIN @EventNotesTemp EN ON en.DeviceID = e.DeviceID AND en.EventTime = e.EventTime AND en.EventID = e.EventID
	LEFT JOIN @AlarmNoteTemp AN ON A.ALARMID=AN.ALARMID
	LEFT JOIN operator oa WITH(NOLOCK) on aa.AssignedToID = oa.userid
	LEFT JOIN operator op on AN.USERID = op.userid
WHERE
	(Convert(Datetime,(DATEADD(ms, (e.EventTime / CAST(10000 AS bigint)) % 86400000,
	DATEADD(day, e.EventTime / CAST(864000000000 AS bigint) - 109207, 0))))
	>= @StartDate 
	AND 
	Convert(DateTime,(DATEADD(ms, (e.EventTime / CAST(10000 AS bigint)) % 86400000,
	DATEADD(day, e.EventTime / CAST(864000000000 AS bigint) - 109207, 0))))
	<= @EndDate)
	and e.OffenderID = @OffenderID
	AND ( et.SO = 1)/*only the events that are available to So*/
ORDER BY e.EventDateTime asc, e.AlarmType
--IsAlarmsAutoCompleted,

drop table #tempcourt2




GO
GRANT EXECUTE ON [ReportCourt2] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [ReportCourt2] TO [db_object_def_viewers]
GO
