/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ResourceRightsGetBySearch]

@ResourceName nvarchar(50)

AS

SET NOCOUNT ON

	SELECT ResourceID, Resource
	FROM Resource
	WHERE (LEN(@ResourceName) <= 0) or (Resource LIKE '%' + @ResourceName + '%')
GO
GRANT EXECUTE ON [ResourceRightsGetBySearch] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [ResourceRightsGetBySearch] TO [db_object_def_viewers]
GO
