/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ResourceRightsGetGridInfo]

AS

SET NOCOUNT ON

SELECT ResourceID, Resource
FROM Resource
GO
GRANT EXECUTE ON [ResourceRightsGetGridInfo] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [ResourceRightsGetGridInfo] TO [db_object_def_viewers]
GO
