/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ReverseGeoCode_CleanUpStreetAddressCache2]

	@StartDate datetime = null,
	@EndDate datetime = null

AS

DELETE dbo.ReverseGeoCode_StreetAddressCache
WHERE (@StartDate IS NOT NULL AND DateRetrieved < @StartDate)
	AND (@EndDate IS NOT NULL AND DateRetrieved > @EndDate)

GO
GRANT EXECUTE ON [ReverseGeoCode_CleanUpStreetAddressCache2] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [ReverseGeoCode_CleanUpStreetAddressCache2] TO [db_object_def_viewers]
GO
