/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [RoleAdd]

	@RoleID int OUTPUT,	
	@RoleName varchar(50)

AS

SET NOCOUNT ON

INSERT INTO [dbo].[Role] 
(
	[Role]
)
VALUES
(
	@RoleName
)

SET @RoleID = SCOPE_IDENTITY()
GO
GRANT VIEW DEFINITION ON [RoleAdd] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [RoleAdd] TO [db_dml]
GO
