/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [RolesGetGridInfo]

AS

SET NOCOUNT ON

SELECT RoleID, [Role]
FROM [Role]
GO
GRANT VIEW DEFINITION ON [RolesGetGridInfo] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [RolesGetGridInfo] TO [db_dml]
GO
