/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:27 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [ScheduleGetRepeatedDayByScheduleID]
@ScheduleID			INT

AS

SELECT s.ID, rd.Short_Name
FROM Schedule s
INNER JOIN ScheduleRepeatedDay sr ON sr.ScheduleID=s.ID
INNER JOIN refDay rd ON rd.ID = sr.DayID
WHERE s.ID = @ScheduleID






GO
GRANT EXECUTE ON [ScheduleGetRepeatedDayByScheduleID] TO [db_dml]
GO
