/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [spTrackingDuration]
@AgencyName varchar(32) = NULL
AS
SELECT Distinct
a.agency
,ISNULL(o.FirstName, '') + ' ' +
ISNULL(o.LastName, '') AS 'OffenderName'
,ta.trackerid
,o.TrackingDurationStartDate
,o.TrackingDurationEndDate
From Offender o
JOIN Agency a on a.agencyid = o.agencyid
LEFT JOIN (SELECT OffenderID, Max(TrackerAssignmentID) AS AssignmentID FROM trackerassignment GROUP BY OffenderID) AS ta1 ON ta1.OffenderID = o.offenderID
JOIN trackerassignment ta on ta.offenderid = ta1.offenderid
Where (a.agency LIKE '%' + ISNULL (@agencyName,'') +'%')

GO
GRANT EXECUTE ON [spTrackingDuration] TO [db_dml]
GO
