/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [StateGetByID]

	@State		NVARCHAR(50) OUTPUT,
	@StateID	INT

AS

	SELECT	@State = State
	FROM	State
	WHERE	StateID = @StateID
GO
GRANT VIEW DEFINITION ON [StateGetByID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [StateGetByID] TO [db_dml]
GO
