/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TempOffenderTrackerActivate]

	@TrackerActivationID		INT OUTPUT,
	@TrackerID		INT,
	@OffenderID		INT,
	@OfficerID		INT,
	@ModifiedByID	INT,
	@ActivateDate	DATETIME
AS
	DECLARE @Check INT

    SELECT @Check = ota.OffenderID
	FROM dbo.OffenderTrackerActivation ota
		inner join Offender_Officer oo
		ON oo.OffenderID = ota.OffenderID
		inner join Offender o
		ON o.OffenderID = oo.OffenderID
	WHERE ota.OffenderID = @OffenderID
	AND ota.OfficerID = @OfficerID
	AND ota.TrackerID = @TrackerID

	if @Check is null
	BEGIN
		INSERT INTO OffenderTrackerActivation
		(TrackerID, OffenderID, OfficerID, ActivateDate, ModifiedByID)
		VALUES
		(@TrackerID, @OffenderID, @OfficerID, @ActivateDate, @ModifiedByID)

		SET @TrackerActivationID = @@IDENTITY
	END
	ELSE
	BEGIN
		SET @TrackerActivationID = -1
	END
GO
GRANT EXECUTE ON [TempOffenderTrackerActivate] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [TempOffenderTrackerActivate] TO [db_object_def_viewers]
GO
