/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [TempTrackerAssignmentGetAll]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT TrackerAssignmentID, 
			TrackerID, 
			OffenderID, 
			SupervisionOfficerID, 
			AssignmentDate, 
			TrackerAssignmentTypeID, 
			CreatedBy, 
			CreatedDate
	FROM TrackerAssignment
	ORDER BY TrackerAssignmentID
END
GO
GRANT VIEW DEFINITION ON [TempTrackerAssignmentGetAll] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [TempTrackerAssignmentGetAll] TO [db_dml]
GO
