/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [UpdateStreetAddressCache]

	@RowCount int = 1000

AS

DECLARE @Date datetime
SET @Date = GETDATE()

INSERT INTO dbo.StreetAddressCache (Latitude, Longitude, Date)
    SELECT DISTINCT TOP (@RowCount)
		ROUND(eb1.Latitude, 5)
		,ROUND(eb1.Longitude, 5)
		,@Date
    FROM dbo.rprtEventsBucket1 eb1
    WHERE NOT EXISTS (
		SELECT sac.Latitude FROM StreetAddressCache sac
        WHERE ROUND(eb1.Latitude, 5) = ROUND(sac.LATITUDE, 5)
        AND ROUND(eb1.Longitude, 5) = ROUND(sac.LONGITUDE, 5)
	)
GO
GRANT VIEW DEFINITION ON [UpdateStreetAddressCache] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [UpdateStreetAddressCache] TO [db_dml]
GO
