/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [UpdateContactInfo]
as
	declare  @contactBackupID int,
	@contactPhone nvarchar(max),
	@contactEmail nvarchar(max),
	@contactPhoneType nvarchar(max),
	@contactEmailType nvarchar(max)

	DECLARE crsr_contacts CURSOR FAST_FORWARD for select contactbackupid,contactPhone,contactEmail from contactbackup 
where (contactPhone <>'0' or contactEmail <>'0') 
	and (
		(contactPhone <>'EveningPhone' 
		and contactPhone <>'DayPhone'	
		and contactPhone <>'MobilePhone')
		or
		(
			contactEmail<>'EmailAddress1'
			and contactEmail<>'EmailAddress2'
		)
)
	OPEN crsr_contacts
	FETCH NEXT FROM crsr_contacts INTO @contactbackupid,@contactPhone,@contactEmail 
	WHILE @@FETCH_STATUS=0
	BEGIN
		set @contactPhoneType = 
(select 
	case @contactPhone  
	when isnull(o.DayPhone,op.DayPhone) then 'DayPhone'
	when isnull(o.EveningPhone,op.EveningPhone) then 'EveningPhone'
	when isnull(o.MobilePhone,op.MobilePhone) then 'MobilePhone'
	end
  from  contactbackup cb
	left join officer o on  o.userid=	cb.ContactUserid
    left join operator op on  op.userid= cb.ContactUserid

where contactbackupid=@contactBackupID)


set @contactEmailType = 
(select 
	case @contactEmail  
	when isnull(o.EmailAddress1,op.EmailAddress1) then 'EmailAddress1'
	when isnull(o.EmailAddress2,op.EmailAddress2) then 'EmailAddress2'
	end
  from  contactbackup cb
	left join officer o on  o.userid=	cb.ContactUserid
    left join operator op on  op.userid= cb.ContactUserid

where contactbackupid=@contactBackupID)

update contactbackup set  ContactPhone= @contactPhoneType, ContactEmail =@contactEmailType
where contactbackupid=@contactBackupID
		
		FETCH NEXT FROM crsr_contacts INTO @contactbackupid,@contactPhone,@contactEmail 
	END
	CLOSE crsr_contacts
	DEALLOCATE crsr_contacts
GO
GRANT EXECUTE ON [UpdateContactInfo] TO [db_dml]
GO
