/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [UserGetSessionTimeOut]
	 @UserId int, 
	 @SessionTimeOut int OUTPUT
AS
BEGIN
	SET NOCOUNT ON;
	SELECT   @SessionTimeOut = u.SessionTimeOut
	FROM [dbo].[User] u
	WHERE @UserId = u.UserId
END


GO
GRANT EXECUTE ON [UserGetSessionTimeOut] TO [db_dml]
GO
