/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [UserGetResourceRights]

	@UserID	INT

AS

	SELECT DISTINCT rr.ResourceID, r.Resource
	FROM	User_Role ur
	INNER JOIN	Role_Resource rr on ur.RoleID = rr.RoleID
	LEFT JOIN Resource r ON rr.ResourceID = r.ResourceID
	WHERE	ur.UserID = @UserID
	ORDER BY rr.ResourceID
GO
GRANT VIEW DEFINITION ON [UserGetResourceRights] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [UserGetResourceRights] TO [db_dml]
GO
