/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [User_RoleAdd]

	@UserID		INT,
	@RoleID		INT

AS

	INSERT INTO User_Role
	(UserID, RoleID)
	VALUES
	(@UserID, @RoleID)
GO
GRANT EXECUTE ON [User_RoleAdd] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [User_RoleAdd] TO [db_object_def_viewers]
GO
