/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [UserGetByUserID]
	@UserID int
	
AS
BEGIN
	SET NOCOUNT ON;

	 SELECT u.*, ur.RoleID    
 		FROM [User] u   
 		LEFT JOIN User_Role ur on ur.UserID=u.UserID    
 		WHERE u.UserID = @UserID and u.Deleted = 0;    
END
GO
GRANT VIEW DEFINITION ON [UserGetByUserID] TO [db_object_def_viewers]
GO
GRANT EXECUTE ON [UserGetByUserID] TO [db_dml]
GO
