/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [VictimGetAllByAgencyID]
        @AgencyID       INT
AS

                SELECT o.OffenderID,
                ISNULL(o.LastName + ', ', '') + ISNULL(o.FirstName, '') AS 'OffenderName'
                FROM    Offender o  (NOLOCK)
                WHERE
                        o.AgencyID = @AgencyID
                        AND
                        o.Deleted = 0
                        AND
                        o.Victim =1 and o.FirstName is not null--it validate that the offender has name
                ORDER BY o.LastName, o.FirstName



GO
GRANT EXECUTE ON [VictimGetAllByAgencyID] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [VictimGetAllByAgencyID] TO [db_object_def_viewers]
GO
