/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:50:28 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: PROCEDURE
*/
CREATE PROCEDURE [VictimGetOffenderByVictimID]
        @VictimID       INT
AS

                SELECT o.OffenderID,
                ISNULL(o.LastName + ', ', '') + ISNULL(o.FirstName, '') AS 'OffenderName'
                FROM    Offender o  (NOLOCK)
                INNER JOIN Offender victim (NOLOCK) on o.OffenderID = victim.VictimAssociatedOffenderID
                WHERE
                        o.Deleted = 0
                        AND
                        victim.offenderID=@VictimID

                ORDER BY o.LastName, o.FirstName


GO
GRANT EXECUTE ON [VictimGetOffenderByVictimID] TO [db_dml]
GO
GRANT VIEW DEFINITION ON [VictimGetOffenderByVictimID] TO [db_object_def_viewers]
GO
