/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:28:09 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: INDEX
*/
CREATE INDEX [_dta_index_AlarmAssignment_9_589245154__K2_K12_K1]
	ON [dbo].[AlarmAssignment]([AlarmID], [AssignedDate], [AlarmAssignmentID])
GO
