/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:24:57 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: TRIGGER
*/
CREATE TRIGGER [dbo].[GeoRuleActionCreate] 

   ON  dbo.[GeoRule] 
   AFTER DELETE, UPDATE
AS 
BEGIN

    -- Insert statements for trigger here

		BEGIN
			INSERT INTO GeoRuleChangeLog (ModifiedDate,
            ModifiedByID,OriginalValues,NewValues,GeoRuleID,TrackerID,OffenderID)
			SELECT GetDate(),d.ModifiedByID,			
				'GeoRuleID:' +cast(d.GeoRuleID as varchar) + ' - ' +
				'GeoRuleName:'+d.GeoRuleName + ' - ' +
				'GeoRuleShapeID:'+cast(d.GeoRuleShapeID as varchar) + ' - ' +
				'GeoRuleTypeID:'+cast(d.GeoRuleTypeID as varchar) + ' - ' +
				'Longitude:'+cast(d.Longitude as varchar) + ' - ' +
				'Latitude:'+cast(d.Latitude as varchar) + ' - ' +
				'Radius:'+cast(d.Radius as varchar)+ ' - ' +
				'Width:'+cast(d.Width as varchar) + ' - ' +
				'Height:'+cast(d.Height as varchar) + ' - ' +
				'Latitudes:'+ cast(d.Latitudes as varchar) + ' - ' +
				'Longitudes:'+ cast(d.Longitudes as varchar) + ' - ' +
				'AlarmInstructions:'+ d.AlarmInstructions + ' - ' +
				'CreatedDate:'+ cast(d.CreatedDate as varchar) + ' - ' +
				'CreatedByID:'+ cast(d.CreatedByID as varchar) + ' - ' +
				'Deleted:'+ cast(d.Deleted as varchar) + ' - ' +
				'StatusID:'+cast(d.StatusID as varchar)+ ' - ' +
				'FileID:'+cast(d.FileID as varchar) + ' - ' +
				'UpdateInProgress:'+cast(d.UpdateInProgress as varchar),

 				'GeoRuleID:' +cast(i.GeoRuleID as varchar) + ' - ' +
				'GeoRuleName:'+i.GeoRuleName + ' - ' +
				'GeoRuleShapeID:'+cast(i.GeoRuleShapeID as varchar) + ' - ' +
				'GeoRuleTypeID:'+cast(i.GeoRuleTypeID as varchar) + ' - ' +
				'Longitude:'+cast(i.Longitude as varchar) + ' - ' +
				'Latitude:'+cast(i.Latitude as varchar) + ' - ' +
				'Radius:'+cast(i.Radius as varchar)+ ' - ' +
				'Width:'+cast(i.Width as varchar) + ' - ' +
				'Height:'+cast(i.Height as varchar) + ' - ' +
				'Latitudes:'+ cast(i.Latitudes as varchar) + ' - ' +
				'Longitudes:'+ cast(i.Longitudes as varchar) + ' - ' +
				'AlarmInstructions:'+ i.AlarmInstructions + ' - ' +
				'CreatedDate:'+ cast(i.CreatedDate as varchar) + ' - ' +
				'CreatedByID:'+ cast(i.CreatedByID as varchar) + ' - ' +
				'Deleted:'+ cast(i.Deleted as varchar) + ' - ' +
				'StatusID:'+cast(i.StatusID as varchar)+ ' - ' +
				'FileID:'+cast(i.FileID as varchar) + ' - ' +
				'UpdateInProgress:'+cast(i.UpdateInProgress as varchar),
				d.GeoRuleID,
				o.TrackerID,
				o.OffenderID
			FROM deleted d
				left join inserted i ON d.GeoRuleID = i.GeoRuleID
				inner join GeoRule_Offender geo_o ON d.GeoRuleID = geo_o.GeoRuleID
				inner join Offender o ON geo_o.OffenderID = o.OffenderID
			If @@Error<> 0
			BEGIN
				RAISERROR ('Error update change log', 16, 1)
				Rollback Transaction
			END
		END
END
GO
