/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:24:57 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: TRIGGER
*/
CREATE TRIGGER [dbo].[tgUpdateEvent] ON [dbo].[rprtEventsBucket1] AFTER UPDATE  
AS
	DECLARE @updateEventPrimaryID int
	DECLARE @AlarmID bigint
	DECLARE @Address varchar(100);
	--set @updateEventPrimaryID=(SELECT EventPrimaryID  FROM inserted)
	
	IF UPDATE(Address) 
	BEGIN 
--		set @AlarmID=(SELECT AlarmID FROM inserted)
--		set @Address=(SELECT Address FROM inserted)
--		IF (@AlarmID > 0)
--		BEGIN
--			UPDATE alarm SET Address=@Address WHERE  alarm.AlarmID=@AlarmID
--		END
		UPDATE alarm SET Address = inserted.Address
		from alarm inner join inserted
		on inserted.alarmid = alarm.alarmid

	END




GO
