/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:24:57 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: TRIGGER
*/
CREATE TRIGGER [dbo].[tgUpdateSequentialProtocols] 
   ON  [dbo].[AlarmProtocolAction] 
   AFTER INSERT,UPDATE
AS 

BEGIN
	DECLARE @AlarmProtocolActionID	INT
	DECLARE @AlarmProtocolSetID		INT
	DECLARE @AlarmProtocolEventID	INT
	DECLARE @Priority				INT 
    DECLARE @RowCount               INT
	DECLARE @Delete					INT
	
	SELECT  
		@AlarmProtocolActionID = AlarmProtocolActionID,
		@AlarmProtocolSetID = AlarmProtocolSetID,	
		@AlarmProtocolEventID = AlarmProtocolEventID,
		@Priority = CASE 
						WHEN ISNUMERIC(Priority)=1 THEN CAST(Priority as INT)
						ELSE NULL
					END
	FROM inserted

	IF (@Priority is NULL)
		RETURN
    
    SET @RowCount = (Select COUNT(*)
					FROM [AlarmProtocolAction]
					WHERE AlarmProtocolActionID <> @AlarmProtocolActionID AND
						  AlarmProtocolSetID = @AlarmProtocolSetID AND
						  AlarmProtocolEventID = @AlarmProtocolEventID AND
						  Type='Sequential' AND
						  Priority <> '*' AND
						  CAST(Priority as INT) = @Priority )

   SET @Delete = (Select COUNT(*)
					FROM [AlarmProtocolAction]
					WHERE AlarmProtocolActionID = @AlarmProtocolActionID AND
						  AlarmProtocolSetID = @AlarmProtocolSetID AND
						  AlarmProtocolEventID = @AlarmProtocolEventID AND
						  Type='Sequential' AND
						  Priority <> '*' AND
						  CAST(Priority as INT) = @Priority and Deleted=1)
    IF(@RowCount > 0)
	BEGIN
		UPDATE [AlarmProtocolAction]
		SET Priority = CAST(Priority as INT) + 1
		WHERE AlarmProtocolActionID <> @AlarmProtocolActionID AND
			  AlarmProtocolSetID = @AlarmProtocolSetID AND
			  AlarmProtocolEventID = @AlarmProtocolEventID AND
			  Type='Sequential' AND
			  Priority <> '*'  AND
			  CAST(Priority as INT)>= @Priority and CAST(Priority as INT)<= dbo.[fnUpdatePriority](@Priority,@AlarmProtocolSetID,@AlarmProtocolEventID ,@AlarmProtocolActionID) 
	END
					 
    IF(@Delete > 0)
	BEGIN
		UPDATE [AlarmProtocolAction]
		SET Priority = CAST(Priority as INT) - 1
		WHERE AlarmProtocolActionID <> @AlarmProtocolActionID AND
			  AlarmProtocolSetID = @AlarmProtocolSetID AND
			  AlarmProtocolEventID = @AlarmProtocolEventID AND
			  Type='Sequential' AND
			  Priority <> '*' AND
			  CAST(Priority as INT)> @Priority  and CAST(Priority as INT)<= dbo.[fnUpdatePriority](@Priority,@AlarmProtocolSetID,@AlarmProtocolEventID ,@AlarmProtocolActionID) 
	END

END








GO
