/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:24:57 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: TRIGGER
*/
CREATE TRIGGER [dbo].[trgBillingServiceArchive]
ON BillingService
FOR UPDATE, DELETE
NOT FOR REPLICATION
AS
SET NOCOUNT ON;
BEGIN TRAN;
INSERT INTO dbo.BillingService_Historical(ID,CreatedByID,CreatedDate,AgencyID,StartDateTime,BillingServiceTypeID)
SELECT ID,CreatedByID,CreatedDate,AgencyID,StartDateTime,BillingServiceTypeID
FROM deleted;
COMMIT TRAN;
GO
