/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:24:57 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: TRIGGER
*/
CREATE TRIGGER [dbo].[trgUpdateEventsBucket1] 
   ON  [dbo].[AlarmAssignment]
   AFTER INSERT
AS 
BEGIN

	SET NOCOUNT ON;

   	DECLARE @AlarmID int
	DECLARE @AlarmAssignmentStatusID int
--	SET @AlarmID = (SELECT TOP 1 AlarmID FROM inserted)
--	SET @AlarmAssignmentStatusID = (SELECT TOP 1 AlarmAssignmentStatusID FROM inserted)

	DECLARE curse CURSOR FORWARD_ONLY FOR (SELECT AlarmID,AlarmAssignmentStatusID FROM inserted)
	OPEN curse
	FETCH NEXT FROM curse INTO @AlarmID, @AlarmAssignmentStatusID
	WHILE @@FETCH_STATUS = 0
	BEGIN

		IF (SELECT COUNT(AlarmID) FROM [dbo].[rprtEventsBucket1] (NOLOCK) WHERE AlarmID = @AlarmID) > 0
		BEGIN
			UPDATE [dbo].[rprtEventsBucket1]
			SET AlarmAssignmentStatusID = @AlarmAssignmentStatusID,
				AlarmAssignmentStatusName = (
					SELECT TOP(1) AlarmAssignmentStatusName 
					FROM AlarmAssignmentStatus (NOLOCK)
					WHERE AlarmAssignmentStatusID = @AlarmAssignmentStatusID
				)
			WHERE AlarmID = @AlarmID
		END
--		ELSE
--		BEGIN
--			UPDATE [dbo].[rprtEventsBucket2]
--			SET AlarmAssignmentStatusID = @AlarmAssignmentStatusID,
--				AlarmAssignmentStatusName = (
--					SELECT TOP(1) AlarmAssignmentStatusName 
--					FROM AlarmAssignmentStatus 
--					WHERE AlarmAssignmentStatusID = @AlarmAssignmentStatusID
--				)
--			WHERE AlarmID = @AlarmID
--		END

		FETCH NEXT FROM curse INTO @AlarmID, @AlarmAssignmentStatusID
	END
	CLOSE curse
	DEALLOCATE curse
	
END


GO
