/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:21:39 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: VIEW
*/
CREATE VIEW [dbo].[DeviceManufacturer]
AS
SELECT     DeviceID, PropertyValue
FROM         dbo.DevicePropertyView
WHERE     (PropertyID = '8207')

GO
