/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:21:39 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: VIEW
*/
CREATE VIEW [dbo].[DistributorReportView]
AS

SELECT DISTINCT
	dbo.Agency.Agency as AgencyName,
	dbo.Agency.City as AgencyCity,
    dbo.Agency.PostalCode as AgencyPostalCode,
	dbo.State.Abbreviation as AgencyState,
	dbo.Distributor.DistributorName,
	dbo.Distributor.TamID,
	dbo.[User].UserName AS TAMUserName,
	dbo.Officer.AgencyID,
	dbo.Officer.FirstName + ' ' + dbo.Officer.LastName AS OfficerName,
	dbo.Offender.FirstName AS OffenderFirstName,
	dbo.Offender.LastName AS OffenderLastName,
	dbo.OffenderTrackerActivation.OffenderID,
	convert(varchar,DATEADD(mi,dbo.fnGetUtcOffset(dbo.Agency.AgencyID),dbo.OffenderTrackerActivation.ActivateDate),101) + ' ' + convert(varchar,DATEADD(mi,dbo.fnGetUtcOffset(dbo.Agency.AgencyID),dbo.OffenderTrackerActivation.ActivateDate),108) as ActivateDate,
	convert(varchar,DATEADD(mi,dbo.fnGetUtcOffset(dbo.Agency.AgencyID),dbo.OffenderTrackerActivation.DeActivateDate),101) + ' ' + convert(varchar,DATEADD(mi,dbo.fnGetUtcOffset(dbo.Agency.AgencyID),dbo.OffenderTrackerActivation.DeActivateDate),108) as DeActivateDate,
	dbo.Tracker.TrackerID,
	dbo.DevicePropertiesView.HardwareVersion,
	dbo.DevicePropertiesView.IMSI,
    dbo.DevicePropertiesView.SerialNo,
	dbo.DevicePropertiesView.Manufacturer,
	dbo.DistributorEmployee.UserID as DistributorEmployeeUserID
FROM dbo.Agency 
	 LEFT JOIN dbo.State ON dbo.Agency.StateID = dbo.State.StateID
	 LEFT JOIN dbo.Distributor ON dbo.Distributor.DistributorID = dbo.Agency.DistributorID
	 LEFT JOIN dbo.DistributorEmployee on 	dbo.DistributorEmployee.DistributorID= dbo.Agency.DistributorID
	 LEFT JOIN dbo.[User] ON dbo.Distributor.TamID = dbo.[User].UserID
	 LEFT JOIN dbo.Officer ON dbo.Officer.AgencyID = dbo.Agency.AgencyID
	 LEFT JOIN dbo.Offender_Officer ON dbo.Offender_Officer.OfficerID = dbo.Officer.OfficerID    
     LEFT JOIN dbo.Offender ON dbo.Offender_Officer.OffenderID = dbo.Offender.OffenderID
	 LEFT JOIN dbo.OffenderTrackerActivation 
		ON dbo.OffenderTrackerActivation.OffenderID = dbo.Offender.OffenderID 
		AND dbo.OffenderTrackerActivation.ActivateDate = (SELECT MAX(ActivateDate) FROM OffenderTrackerActivation OTA WHERE OTA.OffenderID = dbo.Offender.OffenderID)
     LEFT JOIN dbo.Tracker ON dbo.OffenderTrackerActivation.TrackerID = dbo.Tracker.TrackerID
     LEFT JOIN dbo.DevicePropertiesView ON dbo.Tracker.TrackerID = dbo.DevicePropertiesView.DeviceID

--SELECT     dbo.Agency.Agency, dbo.Tracker.TrackerID, dbo.DevicePropertiesView.HardwareVersion, dbo.DevicePropertiesView.IMSI,
--                      dbo.DevicePropertiesView.SerialNo, dbo.DevicePropertiesView.Manufacturer, dbo.Agency.City, dbo.Agency.PostalCode, dbo.State.Abbreviation, 
--                      dbo.Distributor.DistributorName, dbo.Distributor.TamID, dbo.[User].UserName AS TAMUserName, dbo.Offender.FirstName AS OffenderFirstName,
--                      dbo.Offender.LastName AS OffenderLastName, dbo.Officer.AgencyID, dbo.Officer.FirstName + ' ' + dbo.Officer.LastName AS OfficerName,
--                      dbo.OffenderTrackerActivation.OffenderID, dbo.OffenderTrackerActivation.ActivateDate, dbo.OffenderTrackerActivation.DeActivateDate,
--                      dbo.Accounting.CustomerName, dbo.Accounting.ID AS CustomerID, dbo.AccountingBillingPerType.BillingPerTypeName
--FROM         dbo.AccountingBillingPerType INNER JOIN
--                      dbo.Accounting INNER JOIN
--                      dbo.OffenderTrackerActivation INNER JOIN
--                      dbo.Offender_Officer INNER JOIN
--                      dbo.Offender ON dbo.Offender_Officer.OffenderID = dbo.Offender.OffenderID INNER JOIN
--                      dbo.Officer ON dbo.Offender_Officer.OfficerID = dbo.Officer.OfficerID INNER JOIN
--                      dbo.Distributor INNER JOIN
--                      dbo.Agency ON dbo.Distributor.DistributorID = dbo.Agency.DistributorID INNER JOIN
--                      dbo.[User] ON dbo.Distributor.TamID = dbo.[User].UserID ON dbo.Officer.AgencyID = dbo.Agency.AgencyID ON 
--                      dbo.OffenderTrackerActivation.OffenderID = dbo.Offender.OffenderID ON dbo.Accounting.AccountID = dbo.Agency.AgencyID ON
--                      dbo.AccountingBillingPerType.BillingPerTypeID = dbo.Accounting.BillingPer LEFT OUTER JOIN
--                      dbo.State ON dbo.Agency.StateID = dbo.State.StateID RIGHT OUTER JOIN
--                      dbo.Tracker ON dbo.Offender.TrackerID = dbo.Tracker.TrackerID LEFT OUTER JOIN
--                      dbo.DevicePropertiesView ON dbo.Tracker.TrackerID = dbo.DevicePropertiesView.DeviceID



GO
