/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:21:39 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: VIEW
*/
CREATE VIEW [dbo].[EventReportView] (EventType, EventTime, GeoRule, 
	EventNote,UserName,CreatedDate,
	OffenderName, OffenderPhone, OffenderAddress, OffenderCity,OffenderState,OffenderPostalCode ,
	OfficerName , OfficerPhone, OfficerAddress, OfficerCity,OfficerState, OfficerPostalCode , OfficerEmail,
	AgencyName , AgencyPhone , AgencyAddress, AgencyCity,AgencyState,AgencyPostalCode ,AgencyOnCallPhone,AgencyOnCallPager,AgencyOnCallEmail,AgencyID,OfficerID,SO

)AS 

SELECT DISTINCT	
	et.AbbrevEventType,
	Convert(varchar,dbo.ConvertLongToDate(e.EventTime),101)+ ' ' + Convert(varchar,dbo.ConvertLongToDate(e.EventTime),108) as EventTime, 
	(
		CASE
			WHEN et.EventTypeGroupID =5
			THEN gr.GeoRuleName 
			ELSE 'N/A'
		END
	) as georule ,
	en.Note,
	u.UserName,
	convert(varchar,en.CreatedDate,101) + ' ' + convert(varchar,en.CreatedDate,108) as CreatedDate,
	ISNULL(o.FirstName + ' ', '') + 
	ISNULL(o.MiddleName + ' ', '') + 
	ISNULL(o.LastName, '')as offender ,
	o.homePhone1,
	o.HomeStreet1 + ' ' + o.HomeStreet2,
	o.HomeCity,
	oState.Abbreviation , 
	o.HomePostalCode,
	ISNULL(ofcr.FirstName + ' ', '' ) +
	ISNULL(ofcr.MiddleName + ' ', '' ) +
	ISNULL(ofcr.LastName, '') as officer,
	ofcr.DayPhone,
	ofcr.StreetLine1 + ' ' + ofcr.StreetLine2, 
	ofcr.City,
	ofcrState.Abbreviation , 
	ofcr.PostalCode,
	ofcr.EmailAddress1,
	ag.Agency,
	ag.Phone,
	ag.StreetLine1 + ' ' + ag.StreetLine2,
	ag.City,
	agState.Abbreviation, 
	ag.PostalCode,
	ag.OnCallPhone,
	ag.OnCallPager,
	ag.OnCallEmail,
	ag.AgencyID,
	ofcr.OfficerID,
	et.SO
	
	
FROM
	Gateway.dbo.Events e
	INNER JOIN OffenderTrackerActivation ota on ota.trackerid = e.DeviceID AND (
		 (ota.activateDate< Convert(DateTime,
				(DATEADD(ms, (e.EventTime / CAST(10000 AS bigint)) % 86400000,
				DATEADD(day, e.EventTime / CAST(864000000000 AS bigint) - 109207, 0))))
		 and ota.DeActivateDate> Convert(DateTime,
				(DATEADD(ms, (e.EventTime / CAST(10000 AS bigint)) % 86400000,
				DATEADD(day, e.EventTime / CAST(864000000000 AS bigint) - 109207, 0)))))
		or
		(ota.activateDate<Convert(DateTime,
				(DATEADD(ms, (e.EventTime / CAST(10000 AS bigint)) % 86400000,
				DATEADD(day, e.EventTime / CAST(864000000000 AS bigint) - 109207, 0))))
		and ota.DeActivateDate is null))
	LEFT JOIN EventType et ON e.EventID = et.EventTypeID
	LEFT JOIN EventNote en on e.Eventid = en.Eventid
	LEFT JOIN Offender o ON o.offenderID = ota.OffenderID AND o.Deleted = 0
	LEFT JOIN State oState ON oState.StateID = o.HomeStateOrProvinceID
	LEFT JOIN Country oCountry ON oCountry.CountryID = o.HomeCountryID
	LEFT JOIN Agency ag ON o.AgencyID = ag.AgencyID
	LEFT JOIN State agState ON agState.StateID = ag.StateID
	LEFT JOIN Country agCountry ON agCountry.CountryID = ag.CountryID
	LEFT JOIN Offender_Officer oo ON o.OffenderID = oo.OffenderID
	LEFT JOIN Officer ofcr ON ofcr.OfficerID = oo.OfficerID
	LEFT JOIN State ofcrState ON ofcrState.StateID = ofcr.StateID
	LEFT JOIN Country ofcrCountry ON ofcrCountry.CountryID = ofcr.CountryID
	LEFT JOIN [User] u ON u.UserID = en.createdbyID
	LEFT JOIN GeoRule gr ON gr.GeoRuleID = e.EventParameter
--    LEFT JOIN Gateway.dbo.Events e2 on e2.deviceid= e.deviceid and e2.eventtime = (select max(e3.eventtime) from Gateway.dbo.Events e3 where e3.deviceid= e2.deviceid and e3.eventtime<e.eventtime )
WHERE
	( 
		(e.EventTime >= 127961856000000000)
	)

GO
