/*
Script generated by Aqua Data Studio 8.0.2 on Jan-15-2010 01:21:39 PM
Database: TrackerPal
Schema: <All Schemas>
Objects: VIEW
*/
CREATE VIEW [dbo].[SupportSuiteExportInfo]
AS
SELECT    t.TrackerID,
       t.TrackerNumber,
       a.Agency,
       d.name as DeviceName,
       ISNULL(o.FirstName, '')+ ' '+
       ISNULL(o.MiddleName, '')+' '+
       ISNULL(o.LastName, '') AS 'OffenderName',
       ISNULL(officer.FirstName, '')+ ' '+
       ISNULL(officer.MiddleName, '')+' '+
       ISNULL(officer.LastName, '') AS 'officerName',
       isnull(P2.propertyValue,'') AS PhoneNumber1
       FROM    Tracker t
       LEFT JOIN Agency a ON t.AgencyID = a.AgencyID
       Left join Gateway.dbo.Devices d on t.TrackerID = d.DeviceID
       LEFT JOIN Offender o ON (t.TrackerID = o.TrackerID AND o.Deleted = 0)
       left JOIN Offender_Officer oo ON o.OffenderID = oo.OffenderID
       left join officer  on officer.OfficerID = oo.OfficerID
       LEFT JOIN Gateway.dbo.deviceProperties P ON P.deviceid =t.TrackerID  and P.propertyID='8203'
       LEFT JOIN Gateway.dbo.deviceProperties P2 ON P2.deviceid =t.TrackerID  and P2.propertyID='8206'
       left join Gateway.dbo.DeviceProperties dp1 on dp1.DeviceID = d.DeviceID and  dp1.propertyID='8410'
       left join Gateway.dbo.DeviceProperties dp2 on dp2.DeviceID = d.DeviceID and dp2.propertyID='8411'
       WHERE    t.Deleted = 0

GO
